package com.creditharmony.approve.rule.auditrating.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-03-30T13:51:05.731+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://www.ibm.com/rules/decisionservice/AuditRating_ruleapp/AuditRating_rules", name = "AuditRating_rulesDecisionService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AuditRatingRulesDecisionService {

    @WebResult(name = "AuditRating_rulesResponse", targetNamespace = "http://www.ibm.com/rules/decisionservice/AuditRating_ruleapp/AuditRating_rules", partName = "AuditRating_rulesResponse")
    @WebMethod(operationName = "AuditRating_rules", action = "AuditRating_rules")
    public AuditRatingRulesResponse auditRatingRules(
        @WebParam(partName = "AuditRating_rulesRequest", name = "AuditRating_rulesRequest", targetNamespace = "http://www.ibm.com/rules/decisionservice/AuditRating_ruleapp/AuditRating_rules")
        AuditRatingRulesRequest auditRatingRulesRequest
    ) throws AuditRatingRulesSoapFault;
}
