
package com.creditharmony.approve.rule.auditrating.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-03-30T13:51:05.724+08:00
 * Generated source version: 3.0.0-milestone2
 */

@WebFault(name = "AuditRating_rulesException", targetNamespace = "http://www.ibm.com/rules/decisionservice/AuditRating_ruleapp/AuditRating_rules")
public class AuditRatingRulesSoapFault extends Exception {

	private static final long serialVersionUID = 4656950371309065508L;
	private AuditRatingRulesException auditRatingRulesException;

    public AuditRatingRulesSoapFault() {
        super();
    }
    
    public AuditRatingRulesSoapFault(String message) {
        super(message);
    }
    
    public AuditRatingRulesSoapFault(String message, Throwable cause) {
        super(message, cause);
    }

    public AuditRatingRulesSoapFault(String message, AuditRatingRulesException auditRatingRulesException) {
        super(message);
        this.auditRatingRulesException = auditRatingRulesException;
    }

    public AuditRatingRulesSoapFault(String message, AuditRatingRulesException auditRatingRulesException, Throwable cause) {
        super(message, cause);
        this.auditRatingRulesException = auditRatingRulesException;
    }

    public AuditRatingRulesException getFaultInfo() {
        return this.auditRatingRulesException;
    }
}
