version: '2'
services:
  boss-logs-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: microservice-boss-logs
        source_port: 7004
        target_port: 7004
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  microservice-config:
    start_on_create: true
  microservice-fegin-ribbon-test:
    start_on_create: true
  microservice-eureka01:
    start_on_create: true
  microservice-eureka02:
    start_on_create: true
  microservice-boss-logs:
    scale: 2
    start_on_create: true
  microservice-eureka:
    start_on_create: true
