// 这是一个jenkins pipline 文件
node {

// 定义环境变量 TAG 为docker私库标签 ；TAG1 是docker 阿里云仓库标签
withEnv(['TAG=registry.docker.me/sourcegarden/$JOB_NAME:$BUILD_NUMBER','TAG1=registry.cn-hangzhou.aliyuncs.com/sourcegarden/$JOB_NAME:$BUILD_NUMBER']) {

//下面的工具均在jenkins 设置菜单的“Global Tool Configuration”选项下配置，其中rancher-compose为自定义工具
//在”Global Tool Configuration“中自定义工具需要安装插件”extra tool installers plugin"
//定义maven工具路径到变量
def mvnHome = tool 'maven350'
//查看工具是否存在
sh "ls -l ${mvnHome}"

//定义rancher-compose工具路径到变量
def RancherHome = tool 'rancher-compose'
//def RancherHome = "/var/jenkins_home/jobs/rancher-compose"
//查看工具是否存在
sh "ls -lh  ${RancherHome}/"


// 设置时间戳
timestamps {

//拉取代码
stage 'Code Checkout'
checkout([$class: 'SubversionSCM', additionalCredentials: [], excludedCommitMessages: '', excludedRegions: '', excludedRevprop: '', excludedUsers: '', filterChangelog: false, ignoreDirPropChanges: false, includedRegions: '', locations: [[credentialsId: 'adc7d86c-4482-4a5d-bf8c-04f5ad4fc360', depthOption: 'infinity', ignoreExternalsOption: true, local: 'car-approve', remote: 'https://10.167.210.231/svn/chp-approve/branch/4.1car'], [credentialsId: 'adc7d86c-4482-4a5d-bf8c-04f5ad4fc360', depthOption: 'infinity', ignoreExternalsOption: true, local: 'chp-parent-ext', remote: 'https://10.167.210.231/svn/chp-parent-ext/trunk'], [credentialsId: 'adc7d86c-4482-4a5d-bf8c-04f5ad4fc360', depthOption: 'infinity', ignoreExternalsOption: true, local: 'chp-parent', remote: 'https://10.167.210.231/svn/chp-parent/trunk']], workspaceUpdater: [$class: 'UpdateWithCleanUpdater']])

//Maven 构建
stage 'Maven Build'

sh "pwd && ls -l && cd ./car-approve && ${mvnHome}/bin/mvn -version && ${mvnHome}/bin/mvn clean install  -P dev -Dmaven.test.skip=true"

//Docker镜像打包
stage 'Image Build'
sh 'ls -l && cp car-approve/target/chp-approve.war car-approve/prebuild-docker/'
dir('car-approve/prebuild-docker/') {
sh "pwd && ls -l && docker build -t $TAG1 -f Dockerfile_jre7_tomcat7 . "
}

//推送Docker镜像到仓库
stage 'Push Image'
dir(' car-approve/prebuild-docker/') {
sh "docker push $TAG1 "
}

//开始编排容器========Rancher dev 环境
stage 'Deploy dev'
//设置工作路径 （注意这里是相对“WORKSPACE”的相对路径
dir('car-approve/prebuild-docker/'){
//替换地址   使其镜像地址为阿里云的镜像仓库地址
//key为rancher 中 rancher node for Uatbeta 环境中的key;
sh "sed -i s/192.168.130.2/registry.aliyuncs.com/g docker-compose.yml"

sh "${RancherHome}/rancher-compose  --url http://10.167.210.186:8080 --access-key 151C1C655D539F037078  --secret-key Djdfg79297spfcL9WuXb8hXe6K9Ftujexdoouyyo   -p dev-car up -p -d -u "
sh "${RancherHome}/rancher-compose  --url http://10.167.210.186:8080 --access-key 151C1C655D539F037078  --secret-key Djdfg79297spfcL9WuXb8hXe6K9Ftujexdoouyyo   -p dev-car up  -d -c "
}

//开始编排容器============Rancher Test 环境
stage 'Deploy Test'
//设置超时时间，时间到如果未操作则后面的动作将取消
timeout(time: 59, unit: 'SECONDS') {
input '是否部署到测试环境?'
}
dir('car-approve/prebuild-docker/'){
sh "sed -i s/192.168.130.2/registry.aliyuncs.com/g docker-compose.yml "
//key为rancher 中 rancher node for Test 环境中的key;
tool name: 'rancher-compose', type: 'com.cloudbees.jenkins.plugins.customtools.CustomTool'
sh "${RancherHome}/rancher-compose  --url http://10.167.210.186:8080 --access-key CA075164770E50350829 --secret-key myPae4EBdnEDXWPjAYK96aWe1hocn4wpcBBvjs9A  -p dev-car up -p -d -u "
sh "${RancherHome}/rancher-compose  --url http://10.167.210.186:8080 --access-key CA075164770E50350829 --secret-key myPae4EBdnEDXWPjAYK96aWe1hocn4wpcBBvjs9A  -p dev-car up -d -c "
}

}
}
}
