version: '2'
.catalog:
  name: tomcat-lb
  version: 0.0.1-rancher-proxy
  description: |
    前端使用Rancher-proxy，后端tomcat容器数量可以随意定义
services:
  tomcat-lb:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: tcp
        service: tomcat
        source_port: 8080
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
    tomcat:
      scale: 1
      start_on_create: true
