package com.creditharmony.approve.phone.entity;

import java.util.List;

import com.creditharmony.approve.common.entity.CityInfo;
import com.creditharmony.core.persistence.DataEntity;

/**
 * 本人核实-本人居住地
 * @Class Name DhzhDhgxbrshd
 * @author 王浩
 * @Create In 2016年5月20日
 */
public class DhzhDhgxbrshd extends DataEntity<DhzhDhgxbrshd> {
	
	private static final long serialVersionUID = -1023884896388005269L;
	
    private String rCustomerCoborrowerId;
    private String liveProvince;
    private String liveCity;
    private String liveArea;
    private String liveAddress;
    private String isRepeat;
    private String isInPool;
    private String editRemark;
    private String netCheckResult; // 居住地址核查结果
    private String netCheckRemark; // 居住地址核查备注
    private String loanId; //汇金来源表id
        
    private List<CityInfo> cityList;
	private List<CityInfo> districtList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_dhzh_dhgxbrshd.r_customer_coborrower_id
     *
     * @return the value of jk.t_jk_dhzh_dhgxbrshd.r_customer_coborrower_id
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public String getrCustomerCoborrowerId() {
        return rCustomerCoborrowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_dhzh_dhgxbrshd.r_customer_coborrower_id
     *
     * @param rCustomerCoborrowerId the value for jk.t_jk_dhzh_dhgxbrshd.r_customer_coborrower_id
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public void setrCustomerCoborrowerId(String rCustomerCoborrowerId) {
        this.rCustomerCoborrowerId = rCustomerCoborrowerId == null ? null : rCustomerCoborrowerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_dhzh_dhgxbrshd.live_province
     *
     * @return the value of jk.t_jk_dhzh_dhgxbrshd.live_province
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public String getLiveProvince() {
        return liveProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_dhzh_dhgxbrshd.live_province
     *
     * @param liveProvince the value for jk.t_jk_dhzh_dhgxbrshd.live_province
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public void setLiveProvince(String liveProvince) {
        this.liveProvince = liveProvince == null ? null : liveProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_dhzh_dhgxbrshd.live_city
     *
     * @return the value of jk.t_jk_dhzh_dhgxbrshd.live_city
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public String getLiveCity() {
        return liveCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_dhzh_dhgxbrshd.live_city
     *
     * @param liveCity the value for jk.t_jk_dhzh_dhgxbrshd.live_city
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public void setLiveCity(String liveCity) {
        this.liveCity = liveCity == null ? null : liveCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_dhzh_dhgxbrshd.live_area
     *
     * @return the value of jk.t_jk_dhzh_dhgxbrshd.live_area
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public String getLiveArea() {
        return liveArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_dhzh_dhgxbrshd.live_area
     *
     * @param liveArea the value for jk.t_jk_dhzh_dhgxbrshd.live_area
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public void setLiveArea(String liveArea) {
        this.liveArea = liveArea == null ? null : liveArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_dhzh_dhgxbrshd.live_address
     *
     * @return the value of jk.t_jk_dhzh_dhgxbrshd.live_address
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public String getLiveAddress() {
        return liveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_dhzh_dhgxbrshd.live_address
     *
     * @param liveAddress the value for jk.t_jk_dhzh_dhgxbrshd.live_address
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public void setLiveAddress(String liveAddress) {
        this.liveAddress = liveAddress == null ? null : liveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_dhzh_dhgxbrshd.is_repeat
     *
     * @return the value of jk.t_jk_dhzh_dhgxbrshd.is_repeat
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public String getIsRepeat() {
        return isRepeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_dhzh_dhgxbrshd.is_repeat
     *
     * @param isRepeat the value for jk.t_jk_dhzh_dhgxbrshd.is_repeat
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public void setIsRepeat(String isRepeat) {
        this.isRepeat = isRepeat == null ? null : isRepeat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_dhzh_dhgxbrshd.is_in_pool
     *
     * @return the value of jk.t_jk_dhzh_dhgxbrshd.is_in_pool
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public String getIsInPool() {
        return isInPool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_dhzh_dhgxbrshd.is_in_pool
     *
     * @param isInPool the value for jk.t_jk_dhzh_dhgxbrshd.is_in_pool
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public void setIsInPool(String isInPool) {
        this.isInPool = isInPool == null ? null : isInPool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_dhzh_dhgxbrshd.edit_remark
     *
     * @return the value of jk.t_jk_dhzh_dhgxbrshd.edit_remark
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public String getEditRemark() {
        return editRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_dhzh_dhgxbrshd.edit_remark
     *
     * @param editRemark the value for jk.t_jk_dhzh_dhgxbrshd.edit_remark
     *
     * @mbggenerated Wed Mar 02 20:17:30 CST 2016
     */
    public void setEditRemark(String editRemark) {
        this.editRemark = editRemark == null ? null : editRemark.trim();
    }

	public List<CityInfo> getCityList() {
		return cityList;
	}

	public void setCityList(List<CityInfo> cityList) {
		this.cityList = cityList;
	}

	public List<CityInfo> getDistrictList() {
		return districtList;
	}

	public void setDistrictList(List<CityInfo> districtList) {
		this.districtList = districtList;
	}

	public String getNetCheckResult() {
		return netCheckResult;
	}

	public void setNetCheckResult(String netCheckResult) {
		this.netCheckResult = netCheckResult;
	}

	public String getNetCheckRemark() {
		return netCheckRemark;
	}

	public void setNetCheckRemark(String netCheckRemark) {
		this.netCheckRemark = netCheckRemark;
	}

	public String getLoanId() {
		return loanId;
	}

	public void setLoanId(String loanId) {
		this.loanId = loanId;
	}	
	
}