
package com.creditharmony.approve.rule.applyengine.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-04-06T14:46:43.571+08:00
 * Generated source version: 3.0.0-milestone2
 */

@WebFault(name = "Applyengine_rulesException", targetNamespace = "http://www.ibm.com/rules/decisionservice/Applyengine_ruleapp/Applyengine_rules")
public class ApplyengineRulesSoapFault extends Exception {
    
	private static final long serialVersionUID = -6195849399225830468L;
	private ApplyengineRulesException applyengineRulesException;

    public ApplyengineRulesSoapFault() {
        super();
    }
    
    public ApplyengineRulesSoapFault(String message) {
        super(message);
    }
    
    public ApplyengineRulesSoapFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ApplyengineRulesSoapFault(String message, ApplyengineRulesException applyengineRulesException) {
        super(message);
        this.applyengineRulesException = applyengineRulesException;
    }

    public ApplyengineRulesSoapFault(String message, ApplyengineRulesException applyengineRulesException, Throwable cause) {
        super(message, cause);
        this.applyengineRulesException = applyengineRulesException;
    }

    public ApplyengineRulesException getFaultInfo() {
        return this.applyengineRulesException;
    }
}
