DROP FUNCTION antifraudcheck(character varying);
/**
 * 入池操作（号码、单位名称
 * @修改履历  V1.0 2016/2/20 创建
 *        V2.0 
 */
CREATE OR REPLACE FUNCTION antifraudcheck(IN loancode character varying, OUT outvalue character varying)
RETURNS character varying AS
$BODY$
DECLARE BACKVALUE varchar(32);
DECLARE T_COUNT INT;
DECLARE SUM_COUNT INT;
BEGIN
	BACKVALUE:='0';
	SUM_COUNT:=0;
/*****************************查重规则匹配开始******************************/
---C系列规则
WITH TEMP_C_RULE AS (
SELECT A.LOAN_CODE N_LOAN_CODE,COALESCE(A.CUSTOMER_PHONE_FIRST,'') N_PHONE_ONE,COALESCE(A.CUSTOMER_PHONE_SECOND,'') N_PHONE_TWO,
       A.CUSTOMER_NAME N_CUSTOMER_NAME,A.CUSTOMER_REGISTER_PROVINCE||A.CUSTOMER_REGISTER_CITY||A.CUSTOMER_REGISTER_AREA||A.CUSTOMER_REGISTER_ADDRESS N_HOMEPLACE,
       A.CUSTOMER_LIVE_PROVINCE||A.CUSTOMER_LIVE_CITY||A.CUSTOMER_LIVE_AREA||A.CUSTOMER_ADDRESS N_LIVE_ADDRESS,A.ID N_CUSTOMTER_ID,CN.COMP_NAME N_COMP_NAME,
       CN.COMP_TEL N_COMP_TEL,CN.COMP_PROVINCE||CN.COMP_CITY||CN.COMP_ARER||CN.COMP_ADDRESS N_COMP_ADDRESS,EN.MATE_NAME N_MATE_NAME,EN.MATE_CERT_NUM N_MATE_IDENTITY,
       EN.MATE_TEL N_MATE_TEL,FN.CONTACT_NAME N_CONTACT_NAME,FN.RELATION_TYPE N_RELATION_TYPE,FN.CONTACT_MOBILE N_CONTACT_MOBILE,GN.PRODUCT_TYPE AS N_PRODUCT_TYPE,
       B.LOAN_CODE O_LOAN_CODE,COALESCE(B.CUSTOMER_PHONE_FIRST,'') O_PHONE_ONE,COALESCE(B.CUSTOMER_PHONE_SECOND,'') O_PHONE_TWO,
       B.CUSTOMER_NAME O_CUSTOMER_NAME,B.CUSTOMER_REGISTER_PROVINCE||B.CUSTOMER_REGISTER_CITY||B.CUSTOMER_REGISTER_AREA||B.CUSTOMER_REGISTER_ADDRESS O_HOMEPLACE,
       B.CUSTOMER_LIVE_PROVINCE||B.CUSTOMER_LIVE_CITY||B.CUSTOMER_LIVE_AREA||B.CUSTOMER_ADDRESS O_LIVE_ADDRESS,B.ID O_CUSTOMTER_ID,CO.COMP_NAME AS O_COMP_NAME,
       CO.COMP_TEL O_COMP_TEL,CO.COMP_PROVINCE||CO.COMP_CITY||CO.COMP_ARER||CO.COMP_ADDRESS O_COMP_ADDRESS,EO.MATE_NAME O_MATE_NAME,EO.MATE_CERT_NUM O_MATE_IDENTITY,
       EO.MATE_TEL O_MATE_TEL,FO.CONTACT_NAME O_CONTACT_NAME,FO.RELATION_TYPE O_RELATION_TYPE,FO.CONTACT_MOBILE O_CONTACT_MOBILE,GO.PRODUCT_TYPE AS O_PRODUCT_TYPE,
       B.CUSTOMER_CERT_NUM,COALESCE(DATE_PART('DAY',CN.COMP_ENTRY_DAY - CO.COMP_ENTRY_DAY),0) DIFF_COMP_ENTRY_DAY,GO.CUSTOMER_INTO_TIME,CO.COMP_ENTRY_DAY,
       COALESCE(DATE_PART('DAY',GN.CUSTOMER_INTO_TIME - GO.CUSTOMER_INTO_TIME),0) AS DATE_DIFF,H.OPERATE_RESULT
FROM JK.T_JK_LOAN_CUSTOMER A INNER JOIN JK.T_JK_LOAN_CUSTOMER B ON A.LOAN_CODE='JK2016021600000049' AND A.CUSTOMER_CERT_NUM=B.CUSTOMER_CERT_NUM AND A.LOAN_CODE<>B.LOAN_CODE
                              LEFT JOIN JK.T_JK_LOAN_COMPANY CN ON A.LOAN_CODE=CN.LOAN_CODE AND A.ID=CN.R_ID
                              LEFT JOIN JK.T_JK_LOAN_COMPANY CO ON B.LOAN_CODE=CO.LOAN_CODE AND B.ID=CO.R_ID
                              LEFT JOIN JK.T_JK_LOAN_MATE EN ON A.LOAN_CODE=EN.LOAN_CODE
                              LEFT JOIN JK.T_JK_LOAN_MATE EO ON B.LOAN_CODE=EO.LOAN_CODE
			                  LEFT JOIN JK.T_JK_CONTACT FN ON A.LOAN_CODE=FN.LOAN_CODE AND A.ID=FN.R_CUSTOMER_COBORROWER_ID AND COALESCE(FN.RELATION_TYPE,'')<>''
                              LEFT JOIN JK.T_JK_CONTACT FO ON B.LOAN_CODE=FO.LOAN_CODE AND B.ID=FO.R_CUSTOMER_COBORROWER_ID AND FN.RELATION_TYPE=FO.RELATION_TYPE
                              LEFT JOIN JK.T_JK_LOAN_INFO GN ON A.LOAN_CODE=GN.LOAN_CODE
                              LEFT JOIN JK.T_JK_LOAN_INFO GO ON B.LOAN_CODE=GO.LOAN_CODE
                              LEFT JOIN JK.T_JK_AUDIT_RECORD H ON GO.AUDIT_ID=H.ID
)
INSERT INTO T_JK_ANTIFRAUD_REPEAT(ID,LOAN_CODE_NOW,RULES_CODE,LOAN_CODE,CUSTOMER_NAME,REPEAT_CERT_NUM,REPEAT_INTO_TIME,REPEAT_RESULT, 
                                 REPEAT_RESULT_MSG,REPEAT_RELATION,REPEAT_NAME_DIFF_FLAG,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME)
SELECT GETUUID32(),N_LOAN_CODE,'C001',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'户籍地址:'||O_HOMEPLACE,'本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE
WHERE N_HOMEPLACE!=O_HOMEPLACE
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_HOMEPLACE,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C002',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'手机号码:'||CONCAT_WS(',',NULLIF(O_PHONE_ONE,''),NULLIF(O_PHONE_TWO,'')),'本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE DATE_DIFF<180 AND ((N_PHONE_ONE||N_PHONE_TWO)!=(O_PHONE_ONE||O_PHONE_TWO) OR (N_PHONE_ONE||N_PHONE_TWO)!=(O_PHONE_TWO||O_PHONE_ONE))
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_PHONE_ONE,O_PHONE_TWO,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C003',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'入职时间:'||TO_CHAR(COMP_ENTRY_DAY,'YYYY-MM-DD'),'本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE DATE_DIFF<180 AND N_COMP_NAME!=O_COMP_NAME AND DIFF_COMP_ENTRY_DAY<0
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,COMP_ENTRY_DAY,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C004',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'单位名称:'||O_COMP_NAME,'本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE DATE_DIFF<180 AND N_COMP_NAME!=O_COMP_NAME AND N_COMP_ADDRESS=O_COMP_ADDRESS AND N_COMP_TEL=O_COMP_TEL
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_COMP_NAME,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C005',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'单位固话:'||O_COMP_TEL,'本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE DATE_DIFF<180 AND N_COMP_TEL!=O_COMP_TEL AND N_COMP_ADDRESS=O_COMP_ADDRESS AND N_COMP_NAME=O_COMP_NAME
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_COMP_TEL,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C006',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'单位地址:'||O_COMP_ADDRESS,'本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE DATE_DIFF<180 AND N_COMP_ADDRESS!=O_COMP_ADDRESS AND N_COMP_NAME=O_COMP_NAME AND N_COMP_TEL=O_COMP_TEL
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_COMP_ADDRESS,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C007',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'单位名称:'||O_COMP_NAME,'工作证明人('||O_CONTACT_NAME||')','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE DATE_DIFF<180 AND N_RELATION_TYPE='1' AND O_RELATION_TYPE='1' AND N_COMP_NAME!=O_COMP_NAME AND N_CONTACT_NAME=O_CONTACT_NAME AND N_CONTACT_MOBILE=O_CONTACT_MOBILE
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_COMP_NAME,O_CONTACT_NAME,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C008',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','工作证明人('||O_CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE DATE_DIFF<180 AND N_RELATION_TYPE='1' AND O_RELATION_TYPE='1' AND N_CONTACT_NAME!=O_CONTACT_NAME AND N_CONTACT_MOBILE=O_CONTACT_MOBILE AND N_COMP_NAME=O_COMP_NAME
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C009',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'手机号码:'||O_CONTACT_MOBILE,'工作证明人('||O_CONTACT_NAME||')','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE DATE_DIFF<180 AND N_RELATION_TYPE='1' AND O_RELATION_TYPE='1' AND N_CONTACT_MOBILE!=O_CONTACT_MOBILE AND N_CONTACT_NAME=O_CONTACT_NAME AND N_COMP_NAME=O_COMP_NAME
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,O_CONTACT_MOBILE,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C010',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'手机号码:'||O_CONTACT_MOBILE||';单位名称:'||O_COMP_NAME,'工作证明人('||O_CONTACT_NAME||')','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE DATE_DIFF<180 AND N_RELATION_TYPE='1' AND O_RELATION_TYPE='1' AND N_CONTACT_MOBILE!=O_CONTACT_MOBILE AND N_CONTACT_NAME=O_CONTACT_NAME AND N_COMP_NAME!=O_COMP_NAME
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,O_CONTACT_MOBILE,O_COMP_NAME,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C011',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'手机号码:'||O_MATE_TEL,'配偶('||O_MATE_NAME||')','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE N_MATE_TEL!=O_MATE_TEL AND N_MATE_IDENTITY=O_MATE_IDENTITY AND N_MATE_NAME=O_MATE_NAME
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_MATE_NAME,O_MATE_TEL,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C012',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'身份证号:'||O_MATE_IDENTITY,'配偶('||O_MATE_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE N_MATE_IDENTITY!=O_MATE_IDENTITY AND N_MATE_NAME!=O_MATE_NAME AND N_MATE_TEL=O_MATE_TEL
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_MATE_NAME,O_MATE_IDENTITY,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C013',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'手机号码:'||O_MATE_TEL||';身份证号:'||O_MATE_IDENTITY,'配偶('||O_MATE_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE N_MATE_IDENTITY!=O_MATE_IDENTITY AND N_MATE_NAME!=O_MATE_NAME AND N_MATE_TEL!=O_MATE_TEL
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_MATE_NAME,O_MATE_IDENTITY,O_MATE_TEL,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C014',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','家庭联系人('||O_CONTACT_NAME||')','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE O_RELATION_TYPE='0' AND (N_PHONE_ONE=O_CONTACT_MOBILE OR N_PHONE_TWO!=O_CONTACT_MOBILE)
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C015',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','工作证明人('||O_CONTACT_NAME||')','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE O_RELATION_TYPE='1' AND (N_PHONE_ONE=O_CONTACT_MOBILE OR N_PHONE_TWO!=O_CONTACT_MOBILE)
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C016',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','其他联系人('||O_CONTACT_NAME||')','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE O_RELATION_TYPE='2' AND (N_PHONE_ONE=O_CONTACT_MOBILE OR N_PHONE_TWO!=O_CONTACT_MOBILE)
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C017',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','家庭联系人('||O_CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE N_RELATION_TYPE='0' AND O_RELATION_TYPE='0' AND N_CONTACT_NAME!=O_CONTACT_NAME AND N_CONTACT_MOBILE=O_CONTACT_MOBILE
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C018',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'手机号码:'||O_CONTACT_MOBILE,'家庭联系人('||O_CONTACT_NAME||')','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE N_RELATION_TYPE='0' AND O_RELATION_TYPE='0' AND N_CONTACT_MOBILE!=O_CONTACT_MOBILE AND N_CONTACT_NAME=O_CONTACT_NAME
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,O_CONTACT_MOBILE,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C019',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'单位名称:'||O_COMP_NAME,'工作证明人('||O_CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE N_RELATION_TYPE='1' AND O_RELATION_TYPE='1' AND N_CONTACT_NAME!=O_CONTACT_NAME AND N_CONTACT_MOBILE=O_CONTACT_MOBILE
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,O_COMP_NAME,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C021',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','其他联系人('||O_CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE N_RELATION_TYPE='2' AND O_RELATION_TYPE='2' AND N_CONTACT_NAME!=O_CONTACT_NAME AND N_CONTACT_MOBILE=O_CONTACT_MOBILE
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C022',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'手机号码:'||O_CONTACT_MOBILE,'其他联系人('||O_CONTACT_NAME||')','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE N_RELATION_TYPE='2' AND O_RELATION_TYPE='2' AND N_CONTACT_MOBILE!=O_CONTACT_MOBILE AND N_CONTACT_NAME=O_CONTACT_NAME
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,O_CONTACT_NAME,O_CONTACT_MOBILE,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C026',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE (N_PRODUCT_TYPE='老板' OR N_PRODUCT_TYPE='企业') AND N_COMP_ADDRESS!=N_LIVE_ADDRESS AND N_COMP_NAME=O_COMP_NAME AND O_COMP_ADDRESS=O_LIVE_ADDRESS
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C027',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE (N_PRODUCT_TYPE='老板' OR N_PRODUCT_TYPE='企业') AND O_COMP_ADDRESS!=O_LIVE_ADDRESS AND N_COMP_NAME=O_COMP_NAME AND N_COMP_ADDRESS=N_LIVE_ADDRESS
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,OPERATE_RESULT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'C028',O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_C_RULE 
WHERE (N_PRODUCT_TYPE='老板' OR N_PRODUCT_TYPE='企业') AND N_COMP_NAME!=O_COMP_NAME AND N_COMP_ADDRESS=N_LIVE_ADDRESS AND O_COMP_ADDRESS=O_LIVE_ADDRESS
GROUP BY N_LOAN_CODE,O_LOAN_CODE,O_CUSTOMER_NAME,CUSTOMER_INTO_TIME,CUSTOMER_CERT_NUM,OPERATE_RESULT;
---R系列规则
WITH TEMP_R_RULE AS (
SELECT A.LOAN_CODE,A.CUSTOMER_CERT_NUM CERT_NUM,COALESCE(A.CUSTOMER_PHONE_FIRST,'') PHONE_ONE,COALESCE(A.CUSTOMER_PHONE_SECOND,'') PHONE_TWO,C.CUSTOMER_INTO_TIME,
       A.CUSTOMER_NAME,A.ID N_CUSTOMTER_ID,COALESCE(B.MATE_NAME,'') MATE_NAME,COALESCE(B.MATE_CERT_NUM,'') MATE_CERT_NUM,COALESCE(B.MATE_TEL,'') MATE_TEL
FROM JK.T_JK_LOAN_CUSTOMER A LEFT JOIN JK.T_JK_LOAN_MATE B ON A.LOAN_CODE=B.LOAN_CODE AND LOAN_CUSTOMTER_TYPE='0' 
                             LEFT JOIN JK.T_JK_LOAN_INFO C ON A.LOAN_CODE=C.LOAN_CODE
WHERE A.LOAN_CODE='JK2016021600000049'
),TEMP_CONTACT AS (
SELECT A.LOAN_CODE,A.CERT_NUM,A.PHONE_ONE,A.PHONE_TWO,A.CUSTOMER_NAME,A.N_CUSTOMTER_ID,B.COMP_NAME,B.COMP_TEL,C.CONTACT_NAME,C.CONTACT_MOBILE,C.RELATION_TYPE
FROM TEMP_R_RULE A LEFT JOIN JK.T_JK_LOAN_COMPANY B ON A.LOAN_CODE=B.LOAN_CODE AND A.N_CUSTOMTER_ID=B.R_ID
                         LEFT JOIN JK.T_JK_CONTACT C ON A.LOAN_CODE=C.LOAN_CODE AND A.N_CUSTOMTER_ID=C.R_CUSTOMER_COBORROWER_ID
)
,TEMP_R001_R002 AS (
SELECT A.LOAN_CODE N_LOAN_CODE,CASE WHEN A.CUSTOMER_NAME=B.CUSTOMER_NAME THEN 'R001' ELSE 'R002' END RULES_CODE,B.LOAN_CODE O_LOAN_CODE,B.CUSTOMER_NAME,B.CUSTOMER_CERT_NUM,
       C.CUSTOMER_INTO_TIME,D.OPERATE_RESULT,CASE WHEN A.CUSTOMER_NAME!=B.CUSTOMER_NAME THEN B.CUSTOMER_NAME ELSE '' END RESULT_MSG
FROM TEMP_R_RULE A INNER JOIN JK.T_JK_LOAN_CUSTOMER B ON ((A.PHONE_ONE!='' AND (A.PHONE_ONE=B.CUSTOMER_PHONE_FIRST OR A.PHONE_ONE=B.CUSTOMER_PHONE_SECOND)) 
                                                                 OR (A.PHONE_TWO!='' AND (A.PHONE_TWO=B.CUSTOMER_PHONE_FIRST OR A.PHONE_TWO=B.CUSTOMER_PHONE_SECOND))
                                                               ) AND A.CERT_NUM!=B.CUSTOMER_CERT_NUM
                         INNER JOIN JK.T_JK_LOAN_INFO C ON B.LOAN_CODE=C.LOAN_CODE
                          LEFT JOIN JK.T_JK_AUDIT_RECORD D ON C.AUDIT_ID=D.ID
),TEMP_R004 AS (
SELECT A.LOAN_CODE N_LOAN_CODE,C.LOAN_CODE O_LOAN_CODE,C.CUSTOMER_NAME,C.CUSTOMER_CERT_NUM,D.CUSTOMER_INTO_TIME,
       E.OPERATE_RESULT,'身份证号:'||B.MATE_CERT_NUM RESULT_MSG,'配偶('||B.MATE_NAME||')' REPEAT_RELATION
FROM TEMP_R_RULE A INNER JOIN JK.T_JK_LOAN_MATE B ON ((A.PHONE_ONE!='' AND A.PHONE_ONE=B.MATE_TEL) OR (A.PHONE_TWO!='' AND A.PHONE_TWO=B.MATE_TEL)) 
                                AND A.CUSTOMER_NAME!=B.MATE_NAME AND A.CERT_NUM!=B.MATE_CERT_NUM AND A.LOAN_CODE!=B.LOAN_CODE
                         INNER JOIN JK.T_JK_LOAN_CUSTOMER C ON B.LOAN_CODE=C.LOAN_CODE AND A.CERT_NUM!=C.CUSTOMER_CERT_NUM
                         INNER JOIN JK.T_JK_LOAN_INFO D ON C.LOAN_CODE=D.LOAN_CODE
                          LEFT JOIN JK.T_JK_AUDIT_RECORD E ON D.AUDIT_ID=E.ID
WHERE (SELECT COUNT(1) FROM TEMP_R_RULE A INNER JOIN JK.T_JK_LOAN_MATE B ON ((A.PHONE_ONE!='' AND A.PHONE_ONE=B.MATE_TEL) OR (A.PHONE_TWO!='' AND A.PHONE_TWO=B.MATE_TEL)) 
                                AND A.CUSTOMER_NAME!=B.MATE_NAME AND A.CERT_NUM!=B.MATE_CERT_NUM AND A.LOAN_CODE!=B.LOAN_CODE
                         INNER JOIN JK.T_JK_LOAN_CUSTOMER C ON B.LOAN_CODE=C.LOAN_CODE AND A.CERT_NUM!=C.CUSTOMER_CERT_NUM
                         INNER JOIN JK.T_JK_LOAN_INFO D ON C.LOAN_CODE=D.LOAN_CODE)>=2
),TEMP_R003_R013 AS (
SELECT A.LOAN_CODE N_LOAN_CODE,B.LOAN_CODE O_LOAN_CODE,C.CUSTOMER_NAME,C.CUSTOMER_CERT_NUM,D.CUSTOMER_INTO_TIME,E.OPERATE_RESULT,B.MATE_NAME,B.MATE_CERT_NUM,B.MATE_TEL,
       CASE WHEN ((A.PHONE_ONE!='' AND A.PHONE_ONE=B.MATE_TEL) OR (A.PHONE_TWO!='' AND A.PHONE_TWO=B.MATE_TEL)) AND A.CUSTOMER_NAME=B.MATE_NAME AND A.CERT_NUM!=B.MATE_CERT_NUM THEN 'R003'
            WHEN A.CERT_NUM=B.MATE_CERT_NUM AND A.CUSTOMER_NAME=B.MATE_NAME AND ((A.PHONE_ONE!='' AND A.PHONE_ONE=B.MATE_TEL) OR (A.PHONE_TWO!='' AND A.PHONE_TWO=B.MATE_TEL)) THEN 'R005'
            WHEN A.CERT_NUM=B.MATE_CERT_NUM AND A.CUSTOMER_NAME!=B.MATE_NAME AND ((A.PHONE_ONE!='' AND A.PHONE_ONE=B.MATE_TEL) OR (A.PHONE_TWO!='' AND A.PHONE_TWO=B.MATE_TEL)) THEN 'R006'
            WHEN A.CERT_NUM=B.MATE_CERT_NUM AND A.CUSTOMER_NAME!=B.MATE_NAME AND A.PHONE_ONE!=COALESCE(B.MATE_TEL,'') AND A.PHONE_TWO=COALESCE(B.MATE_TEL,'') THEN 'R007'
            WHEN A.MATE_CERT_NUM=B.MATE_CERT_NUM AND A.MATE_NAME=B.MATE_NAME AND A.MATE_TEL=B.MATE_TEL THEN 'R008'
            WHEN A.MATE_CERT_NUM=B.MATE_CERT_NUM AND A.MATE_NAME=B.MATE_NAME AND A.MATE_TEL!=B.MATE_TEL THEN 'R009'
            WHEN A.MATE_CERT_NUM=B.MATE_CERT_NUM AND A.MATE_NAME!=B.MATE_NAME AND A.MATE_TEL=B.MATE_TEL THEN 'R010'
            WHEN A.MATE_CERT_NUM=B.MATE_CERT_NUM AND A.MATE_NAME!=B.MATE_NAME AND A.MATE_TEL!=B.MATE_TEL THEN 'R011'
            WHEN A.MATE_CERT_NUM!=B.MATE_CERT_NUM AND A.MATE_NAME=B.MATE_NAME AND A.MATE_TEL=B.MATE_TEL THEN 'R012'
            WHEN A.MATE_CERT_NUM!=B.MATE_CERT_NUM AND A.MATE_NAME!=B.MATE_NAME AND A.MATE_TEL=B.MATE_TEL THEN 'R013'
       ELSE '' END RULES_CODE
FROM TEMP_R_RULE A INNER JOIN JK.T_JK_LOAN_MATE B ON (((A.PHONE_ONE!='' AND A.PHONE_ONE=B.MATE_TEL) OR (A.PHONE_TWO!='' AND A.PHONE_TWO=B.MATE_TEL))
                                                        OR A.CERT_NUM=B.MATE_CERT_NUM OR A.MATE_CERT_NUM=B.MATE_CERT_NUM OR A.MATE_TEL=B.MATE_TEL)
                         INNER JOIN JK.T_JK_LOAN_CUSTOMER C ON B.LOAN_CODE=C.LOAN_CODE AND A.CERT_NUM<>C.CUSTOMER_CERT_NUM
                         INNER JOIN JK.T_JK_LOAN_INFO D ON C.LOAN_CODE=D.LOAN_CODE
                          LEFT JOIN JK.T_JK_AUDIT_RECORD E ON D.AUDIT_ID=E.ID
),TEMP_R014_R023 AS (
SELECT A.LOAN_CODE N_LOAN_CODE,B.LOAN_CODE O_LOAN_CODE,C.CUSTOMER_NAME,C.CUSTOMER_CERT_NUM,D.CUSTOMER_INTO_TIME,B.CONTACT_NAME,E.COMP_NAME,F.OPERATE_RESULT,
CASE WHEN A.PHONE_ONE=B.CONTACT_MOBILE AND B.RELATION_TYPE='0' AND A.CUSTOMER_NAME!=B.CONTACT_NAME THEN 1 ELSE 0 END R014,
CASE WHEN A.PHONE_ONE=B.CONTACT_MOBILE AND B.RELATION_TYPE='1' AND A.CUSTOMER_NAME!=B.CONTACT_NAME THEN 1 ELSE 0 END R015,
CASE WHEN A.PHONE_ONE=B.CONTACT_MOBILE AND B.RELATION_TYPE='2' AND A.CUSTOMER_NAME!=B.CONTACT_NAME THEN 1 ELSE 0 END R016,
CASE WHEN A.CONTACT_MOBILE=B.CONTACT_MOBILE AND A.RELATION_TYPE='0' AND B.RELATION_TYPE='0' AND A.CUSTOMER_NAME!=B.CONTACT_NAME THEN 1 ELSE 0 END R017,
CASE WHEN A.CONTACT_MOBILE=B.CONTACT_MOBILE AND A.RELATION_TYPE='0' AND B.RELATION_TYPE='1' AND A.CUSTOMER_NAME!=B.CONTACT_NAME THEN 1 ELSE 0 END R018,
CASE WHEN A.CONTACT_MOBILE=B.CONTACT_MOBILE AND A.RELATION_TYPE='0' AND B.RELATION_TYPE='2' AND A.CUSTOMER_NAME!=B.CONTACT_NAME THEN 1 ELSE 0 END R019,
CASE WHEN A.CONTACT_MOBILE=B.CONTACT_MOBILE AND A.RELATION_TYPE='1' AND B.RELATION_TYPE='0' AND A.CUSTOMER_NAME!=B.CONTACT_NAME THEN 1 ELSE 0 END R020,
CASE WHEN A.CONTACT_MOBILE=B.CONTACT_MOBILE AND A.RELATION_TYPE='1' AND B.RELATION_TYPE='1' AND A.CUSTOMER_NAME=B.CONTACT_NAME AND A.COMP_NAME!=E.COMP_NAME THEN 1 ELSE 0 END R021,
CASE WHEN A.CONTACT_MOBILE=B.CONTACT_MOBILE AND A.RELATION_TYPE='1' AND B.RELATION_TYPE='1' AND A.CUSTOMER_NAME!=B.CONTACT_NAME AND A.COMP_NAME!=E.COMP_NAME THEN 1 ELSE 0 END R022,
CASE WHEN A.CONTACT_MOBILE=B.CONTACT_MOBILE AND A.RELATION_TYPE='1' AND B.RELATION_TYPE='2' AND A.CUSTOMER_NAME!=B.CONTACT_NAME THEN 1 ELSE 0 END R023
FROM TEMP_CONTACT A INNER JOIN JK.T_JK_CONTACT B ON ((A.PHONE_ONE!='' AND A.PHONE_ONE=B.CONTACT_MOBILE) OR (A.PHONE_TWO!='' AND A.PHONE_TWO=B.CONTACT_MOBILE) OR A.CONTACT_MOBILE=B.CONTACT_MOBILE) AND A.LOAN_CODE<>B.LOAN_CODE
                    INNER JOIN JK.T_JK_LOAN_CUSTOMER C ON B.LOAN_CODE=C.LOAN_CODE AND B.R_CUSTOMER_COBORROWER_ID=C.ID AND A.CERT_NUM!=C.CUSTOMER_CERT_NUM
                    INNER JOIN JK.T_JK_LOAN_INFO D ON C.LOAN_CODE=D.LOAN_CODE
                     LEFT JOIN JK.T_JK_LOAN_COMPANY E ON C.LOAN_CODE=E.LOAN_CODE AND C.ID=E.R_ID
                     LEFT JOIN JK.T_JK_AUDIT_RECORD F ON D.AUDIT_ID=F.ID
),TEMP_R014_R023_MAX_1 AS (
SELECT N_LOAN_CODE,O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,CONTACT_NAME,OPERATE_RESULT,MAX(R014) R014,
       MAX(R015) R015,MAX(R016) R016,MAX(R017) R017,MAX(R018) R018,MAX(R019) R019,MAX(R020) R020,MAX(R023) R023
FROM TEMP_R014_R023
GROUP BY N_LOAN_CODE,O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,CONTACT_NAME,OPERATE_RESULT
),TEMP_R014_R023_MAX_2 AS (
SELECT N_LOAN_CODE,O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,CONTACT_NAME,COMP_NAME,OPERATE_RESULT,MAX(R021) R021,MAX(R022) R022
FROM TEMP_R014_R023
GROUP BY N_LOAN_CODE,O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,CONTACT_NAME,COMP_NAME,OPERATE_RESULT
),TEMP_R014_R023_SUM_1 AS (
SELECT N_LOAN_CODE,SUM(R014) R014,SUM(R015) R015,SUM(R016) R016,SUM(R017) R017,SUM(R018) R018,SUM(R019) R019,SUM(R020) R020,SUM(R023) R023
FROM TEMP_R014_R023_MAX_1
GROUP BY N_LOAN_CODE
),TEMP_R014_R023_SUM_2 AS (
SELECT N_LOAN_CODE,SUM(R021) R021,SUM(R022) R022
FROM TEMP_R014_R023_MAX_2
GROUP BY N_LOAN_CODE
),TEMP_R024_R026 AS (
SELECT A.LOAN_CODE N_LOAN_CODE,C.LOAN_CODE O_LOAN_CODE,D.CUSTOMER_NAME,D.CUSTOMER_CERT_NUM,E.CUSTOMER_INTO_TIME,C.COMP_TEL,C.COMP_NAME,F.OPERATE_RESULT,
       CASE WHEN B.COMP_NAME=C.COMP_NAME AND B.COMP_TEL=C.COMP_TEL AND COALESCE(DATE_PART('DAY',A.CUSTOMER_INTO_TIME - E.CUSTOMER_INTO_TIME),0)<60 THEN 1 ELSE 0 END R024,
       CASE WHEN B.COMP_NAME=C.COMP_NAME AND B.COMP_TEL!=C.COMP_TEL AND COALESCE(DATE_PART('DAY',A.CUSTOMER_INTO_TIME - E.CUSTOMER_INTO_TIME),0)<90 THEN 1 ELSE 0 END R025,
       CASE WHEN B.COMP_NAME!=C.COMP_NAME AND B.COMP_TEL=C.COMP_TEL AND COALESCE(DATE_PART('DAY',A.CUSTOMER_INTO_TIME - E.CUSTOMER_INTO_TIME),0)<90 THEN 1 ELSE 0 END R026
FROM TEMP_R_RULE A INNER JOIN JK.T_JK_LOAN_COMPANY B ON A.LOAN_CODE=B.LOAN_CODE AND A.N_CUSTOMTER_ID=B.R_ID
                         INNER JOIN JK.T_JK_LOAN_COMPANY C ON (B.COMP_NAME=C.COMP_NAME OR B.COMP_TEL=C.COMP_TEL) AND B.LOAN_CODE!=C.LOAN_CODE
                         INNER JOIN JK.T_JK_LOAN_CUSTOMER D ON C.LOAN_CODE=D.LOAN_CODE AND A.CERT_NUM!=D.CUSTOMER_CERT_NUM
                         INNER JOIN JK.T_JK_LOAN_INFO E ON C.LOAN_CODE=E.LOAN_CODE
                          LEFT JOIN JK.T_JK_AUDIT_RECORD F ON E.AUDIT_ID=F.ID
),TEMP_R024_R026_MAX AS (
SELECT N_LOAN_CODE,O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,COMP_TEL,COMP_NAME,OPERATE_RESULT,MAX(R024) R024,MAX(R025) R025,MAX(R026) R026
FROM TEMP_R024_R026
GROUP BY N_LOAN_CODE,O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,COMP_TEL,COMP_NAME,OPERATE_RESULT
),TEMP_R024_R026_SUM AS (
SELECT N_LOAN_CODE,SUM(R024) R024,SUM(R025) R025,SUM(R026) R026
FROM TEMP_R024_R026_MAX
GROUP BY N_LOAN_CODE
)
INSERT INTO T_JK_ANTIFRAUD_REPEAT(ID,LOAN_CODE_NOW,RULES_CODE,LOAN_CODE,CUSTOMER_NAME,REPEAT_CERT_NUM,REPEAT_INTO_TIME,REPEAT_RESULT, 
                                 REPEAT_RESULT_MSG,REPEAT_RELATION,REPEAT_NAME_DIFF_FLAG,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME)
SELECT GETUUID32(),N_LOAN_CODE,RULES_CODE,O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,RESULT_MSG,'本人' REPEAT_RELATION,'0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R001_R002
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R004',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,RESULT_MSG,REPEAT_RELATION,'1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R004
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,RULES_CODE,O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,
CASE WHEN RULES_CODE='R003' OR RULES_CODE='R012' OR RULES_CODE='R013' THEN '身份证号:'||MATE_CERT_NUM
     WHEN RULES_CODE='R007' OR RULES_CODE='R009' OR RULES_CODE='R011' THEN '手机号码:'||MATE_TEL
ELSE '' END RESULT_MSG,'配偶('||MATE_NAME||')' REPEAT_RELATION,
CASE WHEN RULES_CODE='R006' OR RULES_CODE='R007' OR RULES_CODE='R010' OR RULES_CODE='R011' OR RULES_CODE='R013' THEN '1' ELSE '0' END NAME_DIFF_FLAG,
'BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R003_R013
WHERE RULES_CODE!=''
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R014',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','家庭联系人('||CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R014_R023_MAX_1
WHERE R014=1 AND (SELECT R014 FROM TEMP_R014_R023_SUM_1)>=2
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R015',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','工作证明人('||CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R014_R023_MAX_1
WHERE R015=1 AND (SELECT R015 FROM TEMP_R014_R023_SUM_1)>=2
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R016',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','其他联系人('||CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R014_R023_MAX_1
WHERE R016=1 AND (SELECT R016 FROM TEMP_R014_R023_SUM_1)>=2
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R017',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','家庭联系人('||CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R014_R023_MAX_1
WHERE R017=1 AND (SELECT R017 FROM TEMP_R014_R023_SUM_1)>=2
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R018',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','工作证明人('||CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R014_R023_MAX_1
WHERE R018=1 AND (SELECT R018 FROM TEMP_R014_R023_SUM_1)>=2
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R019',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','其他联系人('||CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R014_R023_MAX_1
WHERE R019=1 AND (SELECT R019 FROM TEMP_R014_R023_SUM_1)>=2
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R020',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','家庭联系人('||CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R014_R023_MAX_1
WHERE R020=1 AND (SELECT R020 FROM TEMP_R014_R023_SUM_1)>=2
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R021',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'单位名称:'||COMP_NAME,'工作证明人('||CONTACT_NAME||')','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R014_R023_MAX_2
WHERE R021=1 AND (SELECT R021 FROM TEMP_R014_R023_SUM_2)>=2
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R022',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'单位名称:'||COMP_NAME,'工作证明人('||CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R014_R023_MAX_2
WHERE R022=1 AND (SELECT R022 FROM TEMP_R014_R023_SUM_2)>=2
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R023',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','其他联系人('||CONTACT_NAME||')','1','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R014_R023_MAX_1
WHERE R023=1 AND (SELECT R023 FROM TEMP_R014_R023_SUM_1)>=2
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R024',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'','本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R024_R026_MAX
WHERE R024=1 AND (SELECT R024 FROM TEMP_R024_R026_SUM)>=4
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R025',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'单位固话:'||COMP_TEL,'本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R024_R026_MAX
WHERE R025=1 AND (SELECT R025 FROM TEMP_R024_R026_SUM)>=3
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,'R026',O_LOAN_CODE,CUSTOMER_NAME,CUSTOMER_CERT_NUM,CUSTOMER_INTO_TIME,OPERATE_RESULT,'单位名称:'||COMP_NAME,'本人','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_R024_R026_MAX
WHERE R026=1 AND (SELECT R026 FROM TEMP_R024_R026_SUM)>=3;
--查重触犯规则主表插入
INSERT INTO T_JK_ANTIFRAUD_OFFEND_INFO(ID,LOAN_CODE,RULES_CODE,DICT_OFFEND_TYPE,OFFEND_RELIEVE_STATUS,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME)
SELECT GETUUID32(),LOAN_CODE_NOW,RULES_CODE,'3','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM T_JK_ANTIFRAUD_REPEAT 
WHERE LOAN_CODE_NOW='JK2016021600000049'
GROUP BY LOAN_CODE_NOW,RULES_CODE;
GET DIAGNOSTICS T_COUNT = ROW_COUNT;
SUM_COUNT:=SUM_COUNT+T_COUNT;
/*****************************查重规则匹配结束******************************/

/*****************************销售人员匹配开始******************************/
WITH TEMP_SALES AS (
SELECT A.LOAN_CODE,COALESCE(A.CUSTOMER_NAME,'') CUSTOMER_NAME,COALESCE(A.CUSTOMER_PHONE_FIRST,'') PHONE_ONE,COALESCE(A.CUSTOMER_PHONE_SECOND,'') PHONE_TWO,
       COALESCE(B.MATE_NAME,'') MATE_NAME,COALESCE(B.MATE_TEL,'') MATE_TEL,COALESCE(C.CONTACT_NAME,'') CONTACT_NAME,COALESCE(C.CONTACT_MOBILE,'') CONTACT_MOBILE,C.RELATION_TYPE 
FROM JK.T_JK_LOAN_CUSTOMER A LEFT JOIN JK.T_JK_LOAN_MATE B ON A.LOAN_CODE=B.LOAN_CODE AND B.LOAN_CUSTOMTER_TYPE='0'
                             LEFT JOIN JK.T_JK_CONTACT C ON A.LOAN_CODE=C.LOAN_CODE AND A.ID=C.R_CUSTOMER_COBORROWER_ID 
                                   AND COALESCE(C.CONTACT_MOBILE,'')<>'' AND C.RELATION_TYPE IN('0','1','2')
WHERE A.LOAN_CODE='JK2016021600000049'
)
INSERT INTO T_JK_ANTIFRAUD_OFFEND_SALES(ID,LOAN_CODE_NOW,RULES_CODE,OFFEND_SALES_NAME,OFFEND_TEL,OFFEND_NAME,WORK_FLAG,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME)
SELECT GETUUID32(),A.LOAN_CODE,'S001',B.SALES_NAME,B.SALES_TEL,'本人('||A.CUSTOMER_NAME||')',B.WORK_FLAG,'BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_SALES A INNER JOIN T_JK_ANTIFRAUD_SALES_STAFF B ON (A.PHONE_ONE!='' AND A.PHONE_ONE=B.SALES_TEL) OR (A.PHONE_TWO!='' AND A.PHONE_TWO=B.SALES_TEL)
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'S002',B.SALES_NAME,B.SALES_TEL,'配偶('||A.MATE_NAME||')',B.WORK_FLAG,'BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_SALES A INNER JOIN T_JK_ANTIFRAUD_SALES_STAFF B ON (A.MATE_TEL!='' AND A.MATE_TEL=B.SALES_TEL)
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,CASE WHEN A.RELATION_TYPE='0' THEN 'S003' WHEN A.RELATION_TYPE='1' THEN 'S004' ELSE 'S005' END,B.SALES_NAME,B.SALES_TEL, 
       CASE WHEN A.RELATION_TYPE='0' THEN '家庭联系人('||A.CONTACT_NAME||')' 
            WHEN A.RELATION_TYPE='1' THEN '工作证明人('||A.CONTACT_NAME||')' 
            ELSE '其他联系人('||A.CONTACT_NAME||')' END ,B.WORK_FLAG,'BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_SALES A INNER JOIN T_JK_ANTIFRAUD_SALES_STAFF B ON (A.CONTACT_MOBILE!='' AND A.CONTACT_MOBILE=B.SALES_TEL);
--销售人员主表插入
INSERT INTO T_JK_ANTIFRAUD_OFFEND_INFO(ID,LOAN_CODE,RULES_CODE,DICT_OFFEND_TYPE,OFFEND_RELIEVE_STATUS,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME)
SELECT GETUUID32(),LOAN_CODE_NOW,RULES_CODE,'1','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM T_JK_ANTIFRAUD_OFFEND_SALES 
WHERE LOAN_CODE_NOW='JK2016021600000049'
GROUP BY LOAN_CODE_NOW,RULES_CODE;
GET DIAGNOSTICS T_COUNT = ROW_COUNT;
SUM_COUNT:=SUM_COUNT+T_COUNT;
/*****************************销售人员匹配结束******************************/

/*****************************欺诈案件匹配开始******************************/
WITH TEMP_CASE AS (
SELECT A.LOAN_CODE,A.CUSTOMER_CERT_NUM,COALESCE(A.CUSTOMER_NAME,'') CUSTOMER_NAME,COALESCE(A.CUSTOMER_PHONE_FIRST,'') PHONE_ONE,COALESCE(A.CUSTOMER_PHONE_SECOND,'') PHONE_TWO,
       COALESCE(B.MATE_NAME,'') MATE_NAME,B.MATE_CERT_NUM,COALESCE(B.MATE_TEL,'') MATE_TEL,COALESCE(C.CONTACT_NAME,'') CONTACT_NAME,COALESCE(C.CONTACT_MOBILE,'') CONTACT_MOBILE,
       C.RELATION_TYPE,D.COMP_NAME,D.COMP_TEL
FROM JK.T_JK_LOAN_CUSTOMER A LEFT JOIN JK.T_JK_LOAN_MATE B ON A.LOAN_CODE=B.LOAN_CODE AND B.LOAN_CUSTOMTER_TYPE='0'
                             LEFT JOIN JK.T_JK_CONTACT C ON A.LOAN_CODE=C.LOAN_CODE AND A.ID=C.R_CUSTOMER_COBORROWER_ID 
                                   AND COALESCE(C.CONTACT_MOBILE,'')!='' AND C.RELATION_TYPE IN('0','1','2')
                             LEFT JOIN JK.T_JK_LOAN_COMPANY D ON A.LOAN_CODE=D.LOAN_CODE AND A.ID=D.R_ID AND (COALESCE(D.COMP_NAME,'')!='' OR COALESCE(D.COMP_TEL,'')!='')
WHERE A.LOAN_CODE='JK2016021600000049'
)
INSERT INTO T_JK_ANTIFRAUD_CASE(ID,LOAN_CODE_NOW,RULES_CODE,CASE_CODE,LOAN_CODE,CASE_HANDLE_DAY,CASE_HANDLE_BY,
                                LOAN_CUSTOMER_NAME,DICT_ANTIFRAUD_TYPE,CASE_RISK_MSG,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME)
SELECT GETUUID32(),A.LOAN_CODE,'A001',C.JUDGE_CASE_CODE,B.LOAN_CODE,C.JUDGE_PROC_DATE,C.JUDGE_PROC_BY,C.LOAN_CUSTOMER_NAME,
       C.DICT_JUDGE_SECOND_CODE,C.DETAIL_JUDGE_RISK_MSG,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_CASE A INNER JOIN JK.T_JK_BACKLIST_ALL B ON B.DICT_MARK_TYPE='0' AND (A.PHONE_ONE!='' AND A.PHONE_ONE=B.BLACK_MSG) OR (A.PHONE_TWO!='' AND A.PHONE_TWO=B.BLACK_MSG) 
                 INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT='0'
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'A002',C.JUDGE_CASE_CODE,B.LOAN_CODE,C.JUDGE_PROC_DATE,C.JUDGE_PROC_BY,C.LOAN_CUSTOMER_NAME,
       C.DICT_JUDGE_SECOND_CODE,C.DETAIL_JUDGE_RISK_MSG,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_CASE A INNER JOIN JK.T_JK_BACKLIST_ALL B ON B.DICT_MARK_TYPE='0' AND A.MATE_TEL=B.BLACK_MSG
                 INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT='0'
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,CASE WHEN RELATION_TYPE='0' THEN 'A003' WHEN RELATION_TYPE='1' THEN 'A004' WHEN RELATION_TYPE='2' THEN 'A005' END,
       C.JUDGE_CASE_CODE,B.LOAN_CODE,C.JUDGE_PROC_DATE,C.JUDGE_PROC_BY,C.LOAN_CUSTOMER_NAME,C.DICT_JUDGE_SECOND_CODE,C.DETAIL_JUDGE_RISK_MSG,'BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_CASE A INNER JOIN JK.T_JK_BACKLIST_ALL B ON B.DICT_MARK_TYPE='0' AND A.CONTACT_MOBILE=B.BLACK_MSG
                 INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT='0'
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'A006',C.JUDGE_CASE_CODE,B.LOAN_CODE,C.JUDGE_PROC_DATE,C.JUDGE_PROC_BY,C.LOAN_CUSTOMER_NAME,
       C.DICT_JUDGE_SECOND_CODE,C.DETAIL_JUDGE_RISK_MSG,'BATCH',SYSDATE,'BATCH',SYSDATE
FROM TEMP_CASE A INNER JOIN JK.T_JK_BACKLIST_ALL B ON B.DICT_MARK_TYPE='0' AND A.COMP_NAME=B.BLACK_MSG
                 INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT='0'
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'A007',C.JUDGE_CASE_CODE,B.LOAN_CODE,C.JUDGE_PROC_DATE,C.JUDGE_PROC_BY,C.LOAN_CUSTOMER_NAME,
       C.DICT_JUDGE_SECOND_CODE,C.DETAIL_JUDGE_RISK_MSG,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_CASE A INNER JOIN JK.T_JK_BACKLIST_ALL B ON B.DICT_MARK_TYPE='0' AND A.COMP_TEL=B.BLACK_MSG
                 INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT='0'
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'A008',C.JUDGE_CASE_CODE,B.LOAN_CODE,C.JUDGE_PROC_DATE,C.JUDGE_PROC_BY,C.LOAN_CUSTOMER_NAME,
       C.DICT_JUDGE_SECOND_CODE,C.DETAIL_JUDGE_RISK_MSG,'BATCH',SYSDATE,'BATCH',SYSDATE  
FROM TEMP_CASE A INNER JOIN JK.T_JK_BACKLIST_ALL B ON B.DICT_MARK_TYPE='0' AND A.CUSTOMER_CERT_NUM=B.BLACK_MSG
                 INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT='0'
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'A009',C.JUDGE_CASE_CODE,B.LOAN_CODE,C.JUDGE_PROC_DATE,C.JUDGE_PROC_BY,C.LOAN_CUSTOMER_NAME,
       C.DICT_JUDGE_SECOND_CODE,C.DETAIL_JUDGE_RISK_MSG,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_CASE A INNER JOIN JK.T_JK_BACKLIST_ALL B ON B.DICT_MARK_TYPE='0' AND A.MATE_CERT_NUM=B.BLACK_MSG
                 INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT='0';
--欺诈案件主表插入
INSERT INTO T_JK_ANTIFRAUD_OFFEND_INFO(ID,LOAN_CODE,RULES_CODE,DICT_OFFEND_TYPE,OFFEND_RELIEVE_STATUS,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME)
SELECT GETUUID32(),LOAN_CODE_NOW,RULES_CODE,'4','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM T_JK_ANTIFRAUD_CASE 
WHERE LOAN_CODE_NOW='JK2016021600000049'
GROUP BY LOAN_CODE_NOW,RULES_CODE;
GET DIAGNOSTICS T_COUNT = ROW_COUNT;
SUM_COUNT:=SUM_COUNT+T_COUNT;
/*****************************欺诈案件匹配结束******************************/

/*****************************黑灰名单匹配开始******************************/
WITH TEMP_BACKLIST AS (
SELECT A.LOAN_CODE,A.CUSTOMER_CERT_NUM,COALESCE(A.CUSTOMER_NAME,'') CUSTOMER_NAME,COALESCE(A.CUSTOMER_PHONE_FIRST,'') PHONE_ONE,COALESCE(A.CUSTOMER_PHONE_SECOND,'') PHONE_TWO,
       COALESCE(B.MATE_NAME,'') MATE_NAME,B.MATE_CERT_NUM,COALESCE(B.MATE_TEL,'') MATE_TEL,COALESCE(C.CONTACT_NAME,'') CONTACT_NAME,COALESCE(C.CONTACT_MOBILE,'') CONTACT_MOBILE,
       C.RELATION_TYPE,D.COMP_NAME,D.COMP_TEL
FROM JK.T_JK_LOAN_CUSTOMER A LEFT JOIN JK.T_JK_LOAN_MATE B ON A.LOAN_CODE=B.LOAN_CODE AND B.LOAN_CUSTOMTER_TYPE='0'
                             LEFT JOIN JK.T_JK_CONTACT C ON A.LOAN_CODE=C.LOAN_CODE AND A.ID=C.R_CUSTOMER_COBORROWER_ID 
                                   AND COALESCE(C.CONTACT_MOBILE,'')<>'' AND C.RELATION_TYPE IN('0','1','2')
                             LEFT JOIN JK.T_JK_LOAN_COMPANY D ON A.LOAN_CODE=D.LOAN_CODE AND A.ID=D.R_ID AND (COALESCE(D.COMP_NAME,'')!='' OR COALESCE(D.COMP_TEL,'')!='')
WHERE A.LOAN_CODE='JK2016021600000049'
)
INSERT INTO T_JK_ANTIFRAUD_BLACKLIST(ID,LOAN_CODE_NOW,RULES_CODE,LOAN_CODE,DICT_MARK_TYPE,DICT_BLACKLIST_TYPE,BLACKLIST_MSG,BLACKLIST_RISK_MSG,
                                     BLACKLIST_RELATION,ADD_BLACK_TIME,ADD_BLACK_TYPE,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME)
SELECT GETUUID32(),A.LOAN_CODE,'B001',B.LOAN_CODE,B.DICT_MARK_TYPE,B.DICT_BLACK_TYPE,B.BLACK_MSG,C.DETAIL_JUDGE_RISK_MSG,'本人('||CUSTOMER_NAME||')',
       B.CREATE_TIME,B.DICT_SOURCE,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_BACKLIST A INNER JOIN JK.T_JK_BACKLIST_ALL B ON (A.PHONE_ONE!='' AND A.PHONE_ONE=B.BLACK_MSG) OR (A.PHONE_TWO!='' AND A.PHONE_TWO=B.BLACK_MSG) 
                     INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT IN('0','1')
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'B002',B.LOAN_CODE,B.DICT_MARK_TYPE,B.DICT_BLACK_TYPE,B.BLACK_MSG,C.DETAIL_JUDGE_RISK_MSG,'配偶('||CUSTOMER_NAME||')',
       B.CREATE_TIME,B.DICT_SOURCE,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_BACKLIST A INNER JOIN JK.T_JK_BACKLIST_ALL B ON A.MATE_TEL=B.BLACK_MSG
                     INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT IN('0','1')
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,CASE WHEN RELATION_TYPE='0' THEN 'B003' WHEN RELATION_TYPE='1' THEN 'B004' WHEN RELATION_TYPE='2' THEN 'B005' END,
       B.LOAN_CODE,B.DICT_MARK_TYPE,B.DICT_BLACK_TYPE,B.BLACK_MSG,C.DETAIL_JUDGE_RISK_MSG,
       CASE WHEN RELATION_TYPE='0' THEN '家庭联系人('||CONTACT_NAME||')' 
            WHEN RELATION_TYPE='1' THEN '工作证明人('||CONTACT_NAME||')' 
            WHEN RELATION_TYPE='2' THEN '其他联系人('||CONTACT_NAME||')' END,
       B.CREATE_TIME,B.DICT_SOURCE,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_BACKLIST A INNER JOIN JK.T_JK_BACKLIST_ALL B ON A.CONTACT_MOBILE=B.BLACK_MSG
                     INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT IN('0','1')
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'B006',B.LOAN_CODE,B.DICT_MARK_TYPE,B.DICT_BLACK_TYPE,B.BLACK_MSG,C.DETAIL_JUDGE_RISK_MSG,'本人('||CUSTOMER_NAME||')',
       B.CREATE_TIME,B.DICT_SOURCE,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_BACKLIST A INNER JOIN JK.T_JK_BACKLIST_ALL B ON A.COMP_NAME=B.BLACK_MSG
                     INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT IN('0','1')
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'B007',B.LOAN_CODE,B.DICT_MARK_TYPE,B.DICT_BLACK_TYPE,B.BLACK_MSG,C.DETAIL_JUDGE_RISK_MSG,'本人('||CUSTOMER_NAME||')',
       B.CREATE_TIME,B.DICT_SOURCE,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_BACKLIST A INNER JOIN JK.T_JK_BACKLIST_ALL B ON A.COMP_TEL=B.BLACK_MSG
                     INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT IN('0','1')
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'B008',B.LOAN_CODE,B.DICT_MARK_TYPE,B.DICT_BLACK_TYPE,B.BLACK_MSG,C.DETAIL_JUDGE_RISK_MSG,'本人('||CUSTOMER_NAME||')',
       B.CREATE_TIME,B.DICT_SOURCE,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_BACKLIST A INNER JOIN JK.T_JK_BACKLIST_ALL B ON A.CUSTOMER_CERT_NUM=B.BLACK_MSG
                     INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT IN('0','1')
UNION ALL
SELECT GETUUID32(),A.LOAN_CODE,'B009',B.LOAN_CODE,B.DICT_MARK_TYPE,B.DICT_BLACK_TYPE,B.BLACK_MSG,C.DETAIL_JUDGE_RISK_MSG,'配偶('||CUSTOMER_NAME||')',
       B.CREATE_TIME,B.DICT_SOURCE,'BATCH',SYSDATE,'BATCH',SYSDATE 
FROM TEMP_BACKLIST A INNER JOIN JK.T_JK_BACKLIST_ALL B ON A.MATE_CERT_NUM=B.BLACK_MSG
                     INNER JOIN JK.T_JK_ANTIFRAUD_JUDGE C ON B.LOAN_CODE=C.LOAN_CODE AND C.DICT_CASE_RESULT IN('0','1');
--黑灰名单主表插入
INSERT INTO T_JK_ANTIFRAUD_OFFEND_INFO(ID,LOAN_CODE,RULES_CODE,DICT_OFFEND_TYPE,OFFEND_RELIEVE_STATUS,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME)
SELECT GETUUID32(),LOAN_CODE_NOW,RULES_CODE,'2','0','BATCH',SYSDATE,'BATCH',SYSDATE
FROM T_JK_ANTIFRAUD_BLACKLIST 
WHERE LOAN_CODE_NOW='JK2016021600000049'
GROUP BY LOAN_CODE_NOW,RULES_CODE;
GET DIAGNOSTICS T_COUNT = ROW_COUNT;
SUM_COUNT:=SUM_COUNT+T_COUNT;
/*****************************黑灰名单匹配结束******************************/
END;
$BODY$
LANGUAGE plsrsql VOLATILE
COST 100;