DROP FUNCTION insertpoolforother(character varying);
/**
 * 入池操作（号码码、单位名称、地址）--非首次场合
 * @修改履历  V1.0 2016/2/20 创建
 *        V2.0 
 */
CREATE OR REPLACE FUNCTION insertpoolforother(loancode character varying)
RETURNS void AS
$BODY$
BEGIN
/*****************************号码类开始******************************/
INSERT INTO  JK.T_JK_PHONE_POOL (ID,LOAN_CODE,R_ID,R_NAME,RELATION,DICT_CUSTOMER_TYPE,PHONE,RESOURCE,INCREMENT_ID,REPEAT_VIEW_TYPE) 
SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,COBO_NAME AS R_NAME,'共借人'  AS RELATION,'1' AS DICT_CUSTOMER_TYPE,COBO_MOBILE AS PHONE,
		'JK.T_JK_LOAN_COBORROWER' AS RESOURCE,ID AS INCREMENT_ID,'手机号码' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_COBORROWER 
WHERE  (INCLUDE_POOL_FLAG IS NULL OR INCLUDE_POOL_FLAG <> '1') AND CHAR_LENGTH(COALESCE(COBO_MOBILE,''))<>0  AND LOAN_CODE=loancode
UNION ALL
SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,COBO_NAME AS R_NAME,'共借人'  AS RELATION,
		'1' AS DICT_CUSTOMER_TYPE,COBO_MOBILE2 AS PHONE,'JK.T_JK_LOAN_COBORROWER' AS RESOURCE,ID AS INCREMENT_ID,'手机号码' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_COBORROWER 
WHERE  (INCLUDE_POOL_FLAG IS NULL OR INCLUDE_POOL_FLAG <> '1') AND CHAR_LENGTH(COALESCE(COBO_MOBILE2,''))<>0 AND LOAN_CODE=loancode
UNION ALL
SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,COBO_NAME AS R_NAME,'共借人'  AS RELATION,
		'1' AS DICT_CUSTOMER_TYPE,COBO_NOW_TEL AS PHONE,'JK.T_JK_LOAN_COBORROWER' AS RESOURCE,ID AS INCREMENT_ID,'家庭固话' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_COBORROWER 
WHERE  (INCLUDE_POOL_FLAG IS NULL OR INCLUDE_POOL_FLAG <> '1') AND CHAR_LENGTH(COALESCE(COBO_NOW_TEL,''))<>0  AND LOAN_CODE=loancode
UNION ALL
SELECT GETUUID32() AS ID,A.LOAN_CODE,A.R_CUSTOMER_COBORROWER_ID AS R_ID,A.MATE_NAME AS R_NAME,
		'家庭联系人-配偶'  AS RELATION,A.LOAN_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,MATE_TEL AS PHONE,
		'JK.T_JK_LOAN_MATE' AS RESOURCE,A.ID AS INCREMENT_ID,'家庭联系人(配偶)手机号码' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_MATE A
		LEFT JOIN JK.T_GL_DICT B ON B.TYPE='jk_loan_man_flag' AND A.LOAN_CUSTOMTER_TYPE = B.VALUE
WHERE  (INCLUDE_POOL_FLAG IS NULL OR INCLUDE_POOL_FLAG <> '1') AND CHAR_LENGTH(COALESCE(MATE_TEL,''))<>0  AND LOAN_CODE=loancode
UNION ALL
SELECT GETUUID32() AS ID,A.LOAN_CODE,A.R_CUSTOMER_COBORROWER_ID AS R_ID,A.CONTACT_NAME AS R_NAME,
		CONCAT(B.LABEL,'-',C.LABEL) AS RELATION,A.LOAN_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,
		CONTACT_MOBILE AS PHONE,'JK.T_JK_CONTACT' AS RESOURCE,A.ID AS INCREMENT_ID,CONCAT(B.LABEL,'-',C.LABEL,'(',CONTACT_NAME,')手机号码') AS REPEAT_VIEW_TYPE
FROM JK.T_JK_CONTACT A
		LEFT JOIN JK.T_GL_DICT B ON B.TYPE='jk_relation_type' AND A.RELATION_TYPE = B.VALUE
		LEFT JOIN JK.T_GL_DICT C ON C.PARENT_ID=B.ID AND A.CONTACT_RELATION = C.VALUE
WHERE  (INCLUDE_POOL_FLAG IS NULL OR INCLUDE_POOL_FLAG <> '1') AND CHAR_LENGTH(COALESCE(CONTACT_MOBILE,''))<>0 AND LOAN_CODE=loancode
UNION ALL
SELECT GETUUID32() AS ID,A.LOAN_CODE,A.R_ID,CASE WHEN A.DICT_R_CUSTOMTER_TYPE='0' THEN B.CUSTOMER_NAME WHEN 
		A.DICT_R_CUSTOMTER_TYPE='1' THEN C.COBO_NAME WHEN A.DICT_R_CUSTOMTER_TYPE='2' THEN D.MATE_NAME END AS R_NAME,
		CASE WHEN A.DICT_R_CUSTOMTER_TYPE='0' THEN '本人' WHEN A.DICT_R_CUSTOMTER_TYPE='1' THEN '共借人' 
	    WHEN A.DICT_R_CUSTOMTER_TYPE='2' THEN '家庭联系人-配偶' END AS RELATION,A.DICT_R_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,COMP_TEL AS PHONE,
		'JK.T_JK_LOAN_COMPANY' AS RESOURCE,A.ID AS INCREMENT_ID,'单位固话' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_COMPANY A
		LEFT JOIN JK.T_JK_LOAN_CUSTOMER B ON A.R_ID = B.ID AND A.DICT_R_CUSTOMTER_TYPE='0'
		LEFT JOIN JK.T_JK_LOAN_COBORROWER C ON A.R_ID = C.ID AND A.DICT_R_CUSTOMTER_TYPE='1'
		LEFT JOIN JK.T_JK_LOAN_MATE D ON A.R_ID = D.ID AND A.DICT_R_CUSTOMTER_TYPE='2'
WHERE (A.INCLUDE_POOL_FLAG IS NULL OR A.INCLUDE_POOL_FLAG <> '1') AND COMP_TEL IS NOT NULL
		AND A.LOAN_CODE=loancode;

/*****************************号码类结束******************************/

/*****************************地址类开始******************************/
INSERT INTO  JK.T_JK_ADDRESS_POOL  (ID,LOAN_CODE,R_ID,R_NAME,RELATION,DICT_CUSTOMER_TYPE,PROVINCE,CITY,AREA,ADDRESS,RESOURCE,INCREMENT_ID,REPEAT_VIEW_TYPE) 
SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,COBO_NAME AS R_NAME,'共借人' AS RELATION,'1' AS DICT_CUSTOMER_TYPE,
	COBO_LIVEING_PROVINCE AS PROVINCE,COBO_LIVEING_CITY AS CITY,COBO_LIVEING_AREA AS AREA,COBO_NOW_ADDRESS AS ADDRESS,
	'JK.T_JK_LOAN_COBORROWER' AS RESOURCE,ID AS INCREMENT_ID,'家庭地址' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_COBORROWER 
WHERE  (INCLUDE_POOL_FLAG IS NULL OR INCLUDE_POOL_FLAG <> '1') AND LOAN_CODE=loancode
 	AND (COBO_LIVEING_PROVINCE IS NOT NULL AND COBO_LIVEING_CITY IS NOT NULL  AND COBO_LIVEING_AREA IS NOT NULL AND CHAR_LENGTH(COBO_NOW_ADDRESS)<>0)
UNION ALL
SELECT GETUUID32() AS ID,A.LOAN_CODE,A.R_ID,CASE WHEN
	A.DICT_R_CUSTOMTER_TYPE='0' THEN B.CUSTOMER_NAME WHEN  A.DICT_R_CUSTOMTER_TYPE='1' THEN
	C.COBO_NAME END AS R_NAME,CASE WHEN A.DICT_R_CUSTOMTER_TYPE='0' THEN '本人'
	WHEN A.DICT_R_CUSTOMTER_TYPE='1' THEN '共借人' END  AS RELATION,A.DICT_R_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,
	A.COMP_PROVINCE AS PROVINCE,A.COMP_CITY AS CITY,
	A.COMP_ARER AS AREA,A.COMP_ADDRESS AS ADDRESS,'JK.T_JK_LOAN_COMPANY' AS RESOURCE,A.ID AS INCREMENT_ID,'单位地址' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_COMPANY A
	LEFT JOIN JK.T_JK_LOAN_CUSTOMER B ON A.R_ID = B.ID AND A.DICT_R_CUSTOMTER_TYPE='0'
	LEFT JOIN JK.T_JK_LOAN_COBORROWER C ON A.R_ID = C.ID AND A.DICT_R_CUSTOMTER_TYPE='1'
WHERE (A.INCLUDE_POOL_FLAG IS NULL OR A.INCLUDE_POOL_FLAG <> '1')
	AND (A.COMP_PROVINCE IS NOT NULL AND A.COMP_CITY IS NOT NULL  AND A.COMP_ARER IS NOT NULL AND CHAR_LENGTH(COALESCE(A.COMP_ADDRESS,''))<>0)
	AND A.LOAN_CODE=loancode; 
/*****************************地址类结束******************************/
END;
$BODY$
LANGUAGE plsrsql VOLATILE
COST 100;