DROP FUNCTION jk.verifyrepeatsecond(character varying, character varying);
/**
 * 内网匹配（查重、归户、异常对比）  退回的门店，补充资料返回的时候，再次进行
 * @修改履历  V1.0 2016/2/1 创建
 *        V2.0 
 */
CREATE OR REPLACE FUNCTION jk.verifyrepeatSecond(loancode character varying,checkType character varying )
RETURNS void AS
$BODY$
DECLARE NUM INT:=0;--是否有更改 0表示没有更改
DECLARE TEMP_NUM INT:=0;--查询某些信息的中间量
DECLARE DATA_UPDATE RECORD; --记录所有有更新身份证号的信息
BEGIN
/**
 * 本次借款申请的本人证件号码，与所有其他历史借款申请的借款人的证件号码进行匹配，匹配后一致
 * 数据对象：共借人
 */
/*****************************历史归户开始******************************/
SELECT INTO NUM COUNT(ID) FROM JK.T_JK_CHANGER_INFO WHERE CHANGE_CODE=loancode AND SELECT_FLAG='0';
IF  NUM>0
THEN 
/**
 * 判断是否有新的变更信息 如果有 则取出所有的变更记录，并进行遍历
 */
FOR DATA_UPDATE IN 
	SELECT CHANGE_CODE,CHANGE_TYPE,CHANGE_RESULT,CHANGE_BEGIN,CHANGE_AFTER,COB_ID,UPDATE_ID,DEL_FLAG  FROM(
		SELECT CHANGE_CODE,CHANGE_TYPE,CHANGE_RESULT,CHANGE_BEGIN,CHANGE_AFTER,COB_ID,DEL_FLAG,UPDATE_ID,
				ROW_NUMBER() OVER(PARTITION BY CHANGE_CODE,CHANGE_TYPE,CHANGE_RESULT,CHANGE_BEGIN,CHANGE_AFTER,COB_ID,DEL_FLAG ORDER BY CREATE_TIME DESC) AS ROW_NO 
		FROM JK.T_JK_CHANGER_INFO WHERE CHANGE_CODE=loancode AND SELECT_FLAG='0'
	) WHERE ROW_NO=1
LOOP
	/**
	 * 如果是删除  则有删除共借人和删除联系人
	 */
	IF DATA_UPDATE.DEL_FLAG = '1'
		THEN
			IF DATA_UPDATE.CHANGE_RESULT = '16'
			/**
			 * 如果删除的是共借人
			 */
			THEN
				DELETE FROM JK.T_JK_INNER_REPEAT  
				WHERE LOAN_CUSTOMER_CODE=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_INNER_APPLY_CONTRAST 
				WHERE LOAN_CUSTOMER_CODE=DATA_UPDATE.COB_ID AND  LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_INNER_CUSTOMER_HIS 
				WHERE CUSTOMER_CODE=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND  LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_DHZH_DHLYXX WHERE R_GX_ID=DATA_UPDATE.COB_ID AND LOAN_CODE=loancode;  
				DELETE FROM JK.T_JK_CREDIT_RISK 
				WHERE R_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_ZLSH_YXXJC 
				WHERE R_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_ZLSH_CCZM 
				WHERE R_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_ZLSH_SBGJJ 
				WHERE R_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM  T_JK_DHZH_DHLYXX A
				USING 
				(
					SELECT B.ID,A.LOAN_CODE FROM JK.T_JK_TEL_AUDIT_WORK A
					LEFT JOIN JK.T_JK_DHZH_WORK_TELNUM  B ON B.WORK_ID = A.ID
					WHERE A.R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND A.DICT_CUSTOMER_TYPE ='1' AND A.LOAN_CODE=loancode
				) B
				WHERE A.R_GX_ID=B.ID AND B.LOAN_CODE=loancode; 
				DELETE FROM JK.T_JK_DHZH_WORK_TELNUM A 
				USING JK.T_JK_TEL_AUDIT_WORK B
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode
						AND  A.WORK_ID = B.ID;
				DELETE FROM JK.T_JK_TEL_AUDIT_WORK 
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_ZLSH_JYDZZM  A
				USING JK.T_JK_ZLSH_JYZM B
				WHERE B.R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID  AND B.DICT_CUSTOMER_TYPE ='1' AND B.LOAN_CODE=loancode AND A.R_JYZM_ID=B.ID;
				DELETE FROM JK.T_JK_ZLSH_JYZM_GDXX  A
				USING JK.T_JK_ZLSH_JYZM  B
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID  AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode AND A.R_JYZM_ID=B.ID;
				DELETE FROM JK.T_JK_ZLSH_JYZM 
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID  AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_ZLSH_GXHT 
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_PRIVATE_NETWORK_CHECK 
				WHERE REL_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_ZLSH_ZCZM 
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_ZLSH_LOAN_ACCOUNT 
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_DHZH_DHLYXX A
				USING  JK.T_JK_DHZH_DHGXSH B
				WHERE B.R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND B.DICT_CUSTOMER_TYPE ='1' AND B.LOAN_CODE=loancode
					AND A.R_GX_ID=B.ID AND B.LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_DHZH_DHGXSH 
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_DHZH_DHLYXX A
				USING  (
							SELECT B.ID,A.LOAN_CODE FROM JK.T_JK_DHZH_BRHS A 
							LEFT JOIN JK.T_JK_DHZH_BRHS_DHXX B ON B.R_BRHS_ID=A.ID
							WHERE A.R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND A.DICT_CUSTOMER_TYPE ='1' AND A.LOAN_CODE=loancode
						) B
				WHERE A.R_GX_ID=B.ID AND B.LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_DHZH_BRHS_DHXX A
				USING JK.T_JK_DHZH_BRHS B
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode AND A.R_BRHS_ID=B.ID;
				DELETE FROM JK.T_JK_DHZH_BRHS_JKJE A
				USING JK.T_JK_DHZH_BRHS B
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode AND  A.R_BRHS_ID=B.ID;
				DELETE FROM JK.T_JK_DHZH_DHGXBRSHD A
				USING JK.T_JK_DHZH_BRHS B
				WHERE B.R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND B.DICT_CUSTOMER_TYPE ='1' AND B.LOAN_CODE=loancode AND A.R_CUSTOMER_COBORROWER_ID=B.ID;
				DELETE FROM JK.T_JK_DHZH_BRHS 
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_OUTSIDE_DATACHECK 
				WHERE R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND LOAN_CUSTOMTER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_ADDRESS_POOL WHERE LOAN_CODE=loancode AND DICT_CUSTOMER_TYPE='1' AND  R_ID= DATA_UPDATE.COB_ID;
				DELETE FROM JK.T_JK_PHONE_POOL WHERE LOAN_CODE=loancode AND DICT_CUSTOMER_TYPE='1' AND  R_ID= DATA_UPDATE.COB_ID;
				DELETE FROM JK.T_JK_WORK_NAME_POOL WHERE LOAN_CODE=loancode AND DICT_CUSTOMER_TYPE='1' AND  R_ID= DATA_UPDATE.COB_ID;
				DELETE FROM JK.T_JK_CREDIT_RISK WHERE LOAN_CODE=loancode AND DICT_CUSTOMER_TYPE='1' AND  R_ID= DATA_UPDATE.COB_ID;
		ELSIF DATA_UPDATE.CHANGE_RESULT = '15' THEN 
		/**
		 * 如果删除的是联系人
		 */
			--DELETE FROM JK.T_JK_DHZH_DHLYXX A
			--USING  JK.T_JK_DHZH_DHGXSH B
			--WHERE B.LOAN_ID=DATA_UPDATE.UPDATE_ID AND B.R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND B.DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE
			--	AND A.R_GX_ID=B.ID AND B.LOAN_CODE=loancode ;
			--DELETE JK.T_JK_DHZH_DHGXSH WHERE LOAN_CODE=loancode AND LOAN_ID=DATA_UPDATE.UPDATE_ID AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE;
			--DELETE FROM JK.T_JK_INNER_REPEAT  
			--WHERE LOAN_CUSTOMER_CODE=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE AND LOAN_CODE=loancode AND REPEAT_VIEW_CONTENT=DATA_UPDATE.CHANGE_AFTER;
			--DELETE FROM JK.T_JK_PHONE_POOL WHERE LOAN_CODE=loancode AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE AND  R_ID= DATA_UPDATE.COB_ID AND INCREMENT_ID=DATA_UPDATE.UPDATE_ID;
		END IF;
/**	
 * 如果是修改
 */
	ELSIF DATA_UPDATE.DEL_FLAG = '0' THEN
		IF DATA_UPDATE.CHANGE_RESULT = '0' THEN
		/**
		 * 修改主借人或共借人手机号
		 */
			UPDATE JK.T_JK_INNER_APPLY_CONTRAST SET CONTRAST_EXCEPTION_MSG=REPLACE(CONTRAST_EXCEPTION_MSG,DATA_UPDATE.CHANGE_BEGIN,DATA_UPDATE.CHANGE_AFTER)
			WHERE CONTRAST_EXCEPTION_TYPE='本人手机' AND LOAN_CODE=loancode AND LOAN_CUSTOMER_CODE=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE;
				/**
				 * 如果之前是空，之后有值，则新加入一条信息，如果之前有值，之后为空，则删一条数据，其他则对应修改
				 */
				IF  CHAR_LENGTH(DATA_UPDATE.CHANGE_BEGIN)=0 THEN
					INSERT INTO JK.T_JK_DHZH_BRHS_DHXX(ID,R_BRHS_ID,BRHS_PHONE,BRHS_NEW_ADD,WORK_NET_ASSESS_RESULT,IS_REPEAT,IS_IN_POOL,TYPE,SOURCE,EDIT_REMARK,LOAN_ID)
					SELECT GETUUID32(),ID,DATA_UPDATE.CHANGE_AFTER,'0','0','1','1','1','01','1',DATA_UPDATE.UPDATE_ID
					FROM JK.T_JK_DHZH_BRHS
					WHERE  LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
						   AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND DICT_CHECK_TYPE=checkType; 
				ELSIF CHAR_LENGTH(DATA_UPDATE.CHANGE_AFTER)=0  THEN
					DELETE FROM JK.T_JK_DHZH_BRHS_DHXX B
					USING JK.T_JK_DHZH_BRHS A
					WHERE B.R_BRHS_ID=A.ID AND B.BRHS_PHONE=DATA_UPDATE.CHANGE_BEGIN AND B.LOAN_ID=DATA_UPDATE.UPDATE_ID 
						   AND A.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND A.DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
						   AND A.R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID; 
				ELSE
					SELECT INTO TEMP_NUM COUNT(B.ID) FROM JK.T_JK_DHZH_BRHS_DHXX B
					LEFT JOIN T_JK_DHZH_BRHS A ON A.ID=B.R_BRHS_ID
					WHERE B.BRHS_PHONE=DATA_UPDATE.CHANGE_BEGIN AND B.LOAN_ID=DATA_UPDATE.UPDATE_ID 
						   AND A.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND A.DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
						   AND A.R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID; 
					IF TEMP_NUM = 0 THEN
						INSERT INTO JK.T_JK_DHZH_BRHS_DHXX(ID,R_BRHS_ID,BRHS_PHONE,BRHS_NEW_ADD,WORK_NET_ASSESS_RESULT,IS_REPEAT,IS_IN_POOL,TYPE,SOURCE,EDIT_REMARK,LOAN_ID)
						SELECT GETUUID32(),ID,DATA_UPDATE.CHANGE_AFTER,'0','0','1','1','1','01','1',DATA_UPDATE.UPDATE_ID
						FROM JK.T_JK_DHZH_BRHS
						WHERE  LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
						       AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND DICT_CHECK_TYPE=checkType; 
					ELSE 
						UPDATE JK.T_JK_DHZH_BRHS_DHXX B SET BRHS_PHONE=DATA_UPDATE.CHANGE_AFTER
						FROM JK.T_JK_DHZH_BRHS A WHERE B.R_BRHS_ID=A.ID AND B.BRHS_PHONE=DATA_UPDATE.CHANGE_BEGIN AND B.LOAN_ID=DATA_UPDATE.UPDATE_ID 
							AND A.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND A.DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE AND A.R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID; 
					END IF;
				END IF;
			INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,
			            EXCEPTION_FLAG,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
			SELECT GETUUID32(),DATA_UPDATE.CHANGE_CODE,A.LOAN_CODE,A.R_NAME,DATA_UPDATE.COB_ID,DATA_UPDATE.CHANGE_TYPE,
					A.RELATION,'2','手机号码',DATA_UPDATE.CHANGE_AFTER,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
			FROM JK.T_JK_PHONE_POOL A
			WHERE A.PHONE=DATA_UPDATE.CHANGE_AFTER  AND A.LOAN_CODE<>DATA_UPDATE.CHANGE_CODE
				AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE B.PHONE_NUM = DATA_UPDATE.CHANGE_AFTER);
			/**
			 * 入池操作
			 */
			INSERT INTO  JK.T_JK_PHONE_POOL (ID,LOAN_CODE,R_ID,R_NAME,RELATION,DICT_CUSTOMER_TYPE,PHONE,RESOURCE,INCREMENT_ID,REPEAT_VIEW_TYPE) 
			SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,COBO_NAME AS R_NAME,'共借人'  AS RELATION,'1' AS DICT_CUSTOMER_TYPE,COBO_MOBILE AS PHONE,
					'JK.T_JK_LOAN_COBORROWER' AS RESOURCE,ID AS INCREMENT_ID,'手机号码' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COBORROWER 
			WHERE  LOAN_CODE=loancode AND DATA_UPDATE.CHANGE_TYPE='1' AND ID=DATA_UPDATE.COB_ID
					AND COBO_MOBILE= DATA_UPDATE.CHANGE_AFTER
			UNION ALL
			SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,COBO_NAME AS R_NAME,'共借人'  AS RELATION,
					'1' AS DICT_CUSTOMER_TYPE,COBO_MOBILE2 AS PHONE,'JK.T_JK_LOAN_COBORROWER' AS RESOURCE,ID AS INCREMENT_ID,'手机号码' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COBORROWER 
			WHERE  LOAN_CODE=loancode AND DATA_UPDATE.CHANGE_TYPE='1' AND ID=DATA_UPDATE.COB_ID
					AND COBO_MOBILE2= DATA_UPDATE.CHANGE_AFTER
			UNION ALL
			SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,CUSTOMER_NAME AS R_NAME,'本人'  AS RELATION,
					'0' AS DICT_CUSTOMER_TYPE,CUSTOMER_PHONE_FIRST AS PHONE,'JK.T_JK_LOAN_CUSTOMER' AS RESOURCE,ID AS INCREMENT_ID,'手机号码' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_CUSTOMER 
			WHERE LOAN_CODE=loancode AND DATA_UPDATE.CHANGE_TYPE='0' AND ID=DATA_UPDATE.COB_ID
					AND CUSTOMER_PHONE_FIRST= DATA_UPDATE.CHANGE_AFTER
			UNION ALL
			SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,CUSTOMER_NAME AS R_NAME,'本人'  AS RELATION,
					'0' AS DICT_CUSTOMER_TYPE,CUSTOMER_PHONE_SECOND AS PHONE,'JK.T_JK_LOAN_CUSTOMER' AS RESOURCE,ID AS INCREMENT_ID,'手机号码' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_CUSTOMER 
			WHERE  LOAN_CODE=loancode AND DATA_UPDATE.CHANGE_TYPE='0' AND ID=DATA_UPDATE.COB_ID
					AND CUSTOMER_PHONE_SECOND= DATA_UPDATE.CHANGE_AFTER;
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '1' THEN
		/**
		 * 修改主借人或共借人姓名
		 */
			UPDATE JK.T_JK_DHZH_BRHS SET NAME=DATA_UPDATE.CHANGE_AFTER WHERE LOAN_CODE=loancode AND R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE;
			UPDATE JK.T_JK_PRIVATE_NETWORK_CHECK A SET NAME=DATA_UPDATE.CHANGE_AFTER
			FROM JK.T_JK_DHZH_BRHS B
			WHERE B.DICT_CHECK_TYPE=checkType AND B.DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE  AND A.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND B.LOAN_CODE=DATA_UPDATE.CHANGE_CODE
				  AND A.CONTENT=B.CUSTOMER_CERT_NUM  AND A.REL_ID=B.R_CUSTOMER_COBORROWER_ID AND B.R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID
				  AND A.NAME=DATA_UPDATE.CHANGE_BEGIN;
			/**
			 * 更新查重信息  和 查重池中对应的名字
			 */
			UPDATE JK.T_JK_INNER_REPEAT SET REPEAT_VIEW_TYPE=REPLACE(REPEAT_VIEW_TYPE,DATA_UPDATE.CHANGE_BEGIN,DATA_UPDATE.CHANGE_AFTER)
			WHERE LOAN_CODE=loancode AND LOAN_CUSTOMER_CODE=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE;
			
			UPDATE JK.T_JK_ADDRESS_POOL SET R_NAME=DATA_UPDATE.CHANGE_AFTER
			WHERE LOAN_CODE=loancode AND R_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
			AND R_NAME=DATA_UPDATE.CHANGE_BEGIN AND INCREMENT_ID=DATA_UPDATE.UPDATE_ID;
			
			UPDATE JK.T_JK_PHONE_POOL SET R_NAME=DATA_UPDATE.CHANGE_AFTER
			WHERE LOAN_CODE=loancode AND R_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
			AND R_NAME=DATA_UPDATE.CHANGE_BEGIN AND INCREMENT_ID=DATA_UPDATE.UPDATE_ID;
			
			UPDATE JK.T_JK_WORK_NAME_POOL SET R_NAME=DATA_UPDATE.CHANGE_AFTER
			WHERE LOAN_CODE=loancode AND R_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
			AND R_NAME=DATA_UPDATE.CHANGE_BEGIN AND INCREMENT_ID=DATA_UPDATE.UPDATE_ID;
			
			
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '2' THEN
		/**
		 * 修改共借人身份证
		 */	
				--DELETE FROM JK.T_JK_INNER_REPEAT  
				--WHERE LOAN_CUSTOMER_CODE=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_INNER_APPLY_CONTRAST 
				WHERE LOAN_CUSTOMER_CODE=DATA_UPDATE.COB_ID AND  LOAN_CODE=loancode;
				DELETE FROM JK.T_JK_INNER_CUSTOMER_HIS 
				WHERE CUSTOMER_CODE=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE ='1' AND  LOAN_CODE=loancode;
				/**
				 * 修改本人核实和专网核查
				 */
				
				UPDATE JK.T_JK_PRIVATE_NETWORK_CHECK A SET CONTENT=DATA_UPDATE.CHANGE_AFTER
				FROM JK.T_JK_DHZH_BRHS B
				WHERE B.DICT_CHECK_TYPE=checkType AND B.DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE  AND A.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND B.LOAN_CODE=DATA_UPDATE.CHANGE_CODE
			    AND A.CONTENT=B.CUSTOMER_CERT_NUM  AND A.REL_ID=B.R_CUSTOMER_COBORROWER_ID AND B.R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID
			    AND A.CONTENT=DATA_UPDATE.CHANGE_BEGIN;
				
			    UPDATE JK.T_JK_DHZH_BRHS SET CUSTOMER_CERT_NUM=DATA_UPDATE.CHANGE_AFTER WHERE LOAN_CODE=loancode AND R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE;
				/**
				 * 重新走共借人的归户和历史异常对比
				 */
				INSERT INTO JK.T_JK_INNER_CUSTOMER_HIS(ID, CUSTOMER_CODE,LOAN_CODE, APPLY_TIME, 
								    PRODUCT_TYPE, DICT_CHECK_STATUS, HIS_REFUSE_RESON,
				                    HIS_AMOUNT_MONTHS,DICT_CUSTOMER_TYPE, CREATE_BY, CREATE_TIME,
				                    MODIFY_BY, MODIFY_TIME,HIS_LOAN_CODE)
				SELECT GETUUID32() AS ID,A.CUSTOMER_CODE,loancode,B.OUTTO_LOAN_TIME,F.PRODUCT_NAME,G.LABEL AS DICT_CHECK_STATUS,
				      C.REFUSE_REASON AS HIS_REFUSE_RESON,B.LOAN_AUDIT_AMOUNT ||'/'|| B.LOAN_AUDIT_MONTHS AS HIS_AMOUNT_MONTHS,
				       A.DICT_CUSTOMER_TYPE,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,A.LOAN_CODE AS HIS_LOAN_CODE
				FROM
					(   
						SELECT A.ID AS CUSTOMER_CODE,B.LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE
						FROM JK.T_JK_LOAN_COBORROWER A 
						INNER JOIN JK.T_JK_LOAN_COBORROWER B ON A.LOAN_CODE=loancode AND B.LOAN_CODE<>loancode  
									AND A.COBO_CERT_NUM=B.COBO_CERT_NUM AND A.ID=DATA_UPDATE.COB_ID
						UNION ALL
						SELECT A.ID AS CUSTOMER_CODE,B.LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE
						FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_CUSTOMER B ON A.LOAN_CODE=loancode
									 AND A.COBO_CERT_NUM=B.CUSTOMER_CERT_NUM AND A.ID=DATA_UPDATE.COB_ID
					) A
				INNER JOIN JK.T_JK_LOAN_INFO B ON A.LOAN_CODE=B.LOAN_CODE AND B.OUTTO_LOAN_TIME IS NOT NULL
				LEFT JOIN JK.T_JK_AUDIT_RECORD C ON B.AUDIT_ID=C.ID
				LEFT JOIN JK.T_GL_JK_PRODUCT F ON B.PRODUCT_TYPE=F.PRODUCT_CODE
				LEFT JOIN JK.T_GL_DICT G ON G.VALUE=B.DICT_LOAN_STATUS AND G.TYPE='jk_loan_apply_status'
				GROUP BY A.LOAN_CODE,B.LOAN_APPLY_TIME,F.PRODUCT_NAME,G.LABEL,C.REFUSE_REASON,B.OUTTO_LOAN_TIME,
				B.LOAN_AUDIT_AMOUNT,B.LOAN_AUDIT_MONTHS,A.DICT_CUSTOMER_TYPE,A.CUSTOMER_CODE;
				/*****************************历史归户结束******************************/
				/**
				 * 当前借款申请的信息，与同一个借款人的前一次历史借款申请的信息进行比较
				 * 数据对象：共借人
				 * 比较对象：手机号码1、手机号码2、居住地址、单位名称、家庭联系人-关系|姓名|手机号
				 */
				/****************************历史异常对比开始****************************/
				WITH TMEP_COBO AS (--共借人
				SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,
				       O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,
				       DICT_CUSTOMER_TYPE
				FROM
				(
					SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,
					       O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,
					       DICT_CUSTOMER_TYPE,ROW_NUMBER() OVER(PARTITION BY N_CUSTOMER_CODE ORDER BY CREATE_TIME DESC) AS ROW_NO
					FROM
					(
						SELECT COALESCE(A.COBO_MOBILE,'') AS N_PHONE_ONE,COALESCE(A.COBO_MOBILE2,'') AS N_PHONE_TWO,A.LOAN_CODE AS N_LOAN_CODE,
						       NM1.AREA_NAME||NM2.AREA_NAME||NM3.AREA_NAME||A.COBO_NOW_ADDRESS AS N_ADDERSS,A.ID AS N_CUSTOMER_CODE,A.COBO_FAMILY_TEL N_FAMILY_TEL,
						       B.CUSTOMER_PHONE_FIRST AS O_PHONE_ONE,B.CUSTOMER_PHONE_SECOND AS O_PHONE_TWO,B.LOAN_CODE AS O_LOAN_CODE,
						       OM1.AREA_NAME||OM2.AREA_NAME||OM3.AREA_NAME||B.CUSTOMER_ADDRESS AS O_ADDERSS,B.ID AS O_CUSTOMER_CODE,B.CUSTOMER_TEL O_FAMILY_TEL,
						       '1' AS DICT_CUSTOMER_TYPE,B.CREATE_TIME
						FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_CUSTOMER B ON A.LOAN_CODE=loancode--'400000316621921' 
									  					AND A.COBO_CERT_NUM=B.CUSTOMER_CERT_NUM AND B.LOAN_CODE<>loancode--'400000316621921'
									  				  LEFT JOIN JK.T_GL_PROVINCE_CITY NM1 ON A.COBO_LIVEING_PROVINCE = NM1.AREA_CODE AND NM1.AREA_TYPE = '1'
													  LEFT JOIN JK.T_GL_PROVINCE_CITY NM2 ON A.COBO_LIVEING_CITY = NM2.AREA_CODE AND NM2.AREA_TYPE = '2'
						                              LEFT JOIN JK.T_GL_PROVINCE_CITY NM3 ON A.COBO_LIVEING_AREA = NM3.AREA_CODE AND NM3.AREA_TYPE = '3'
									                  LEFT JOIN JK.T_GL_PROVINCE_CITY OM1 ON B.CUSTOMER_LIVE_PROVINCE = OM1.AREA_CODE AND OM1.AREA_TYPE = '1'
						                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM2 ON B.CUSTOMER_LIVE_CITY = OM2.AREA_CODE AND OM2.AREA_TYPE = '2'
						                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM3 ON B.CUSTOMER_LIVE_AREA = OM3.AREA_CODE AND OM3.AREA_TYPE = '3'
						WHERE A.ID=DATA_UPDATE.COB_ID
						UNION ALL
						SELECT COALESCE(A.COBO_MOBILE,'') AS N_PHONE_ONE,COALESCE(A.COBO_MOBILE2,'') AS N_PHONE_TWO,A.LOAN_CODE AS N_LOAN_CODE,
						       NM1.AREA_NAME||NM2.AREA_NAME||NM3.AREA_NAME||A.COBO_NOW_ADDRESS AS N_ADDERSS,A.ID AS N_CUSTOMER_CODE,A.COBO_FAMILY_TEL N_FAMILY_TEL,
						       B.COBO_MOBILE AS O_PHONE_ONE,B.COBO_MOBILE2 AS O_PHONE_TWO,B.LOAN_CODE AS O_LOAN_CODE,
						       OM1.AREA_NAME||OM2.AREA_NAME||OM3.AREA_NAME||B.COBO_NOW_ADDRESS AS O_ADDERSS,B.ID AS O_CUSTOMER_CODE,B.COBO_FAMILY_TEL O_FAMILY_TEL,
						       '1' AS DICT_CUSTOMER_TYPE,B.CREATE_TIME
						FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_COBORROWER B ON A.LOAN_CODE=loancode--'400000316621921' 
									  					AND A.COBO_CERT_NUM=B.COBO_CERT_NUM AND B.LOAN_CODE<>loancode--'400000316621921'
								  				  LEFT JOIN JK.T_GL_PROVINCE_CITY NM1 ON A.COBO_LIVEING_PROVINCE = NM1.AREA_CODE AND NM1.AREA_TYPE = '1'
												  LEFT JOIN JK.T_GL_PROVINCE_CITY NM2 ON A.COBO_LIVEING_CITY = NM2.AREA_CODE AND NM2.AREA_TYPE = '2'
					                              LEFT JOIN JK.T_GL_PROVINCE_CITY NM3 ON A.COBO_LIVEING_AREA = NM3.AREA_CODE AND NM3.AREA_TYPE = '3'
								                  LEFT JOIN JK.T_GL_PROVINCE_CITY OM1 ON B.COBO_LIVEING_PROVINCE = OM1.AREA_CODE AND OM1.AREA_TYPE = '1'
					                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM2 ON B.COBO_LIVEING_CITY = OM2.AREA_CODE AND OM2.AREA_TYPE = '2'
					                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM3 ON B.COBO_LIVEING_AREA = OM3.AREA_CODE AND OM3.AREA_TYPE = '3'
					  WHERE A.ID=DATA_UPDATE.COB_ID                            
					) A
				) B
				WHERE ROW_NO=1
				),
				TEMP_FINAL AS (--共借人
				SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,DICT_CUSTOMER_TYPE
				FROM TMEP_COBO
				),
				TEMP_UNIT AS (--单位名称
				SELECT A.DICT_CUSTOMER_TYPE,A.N_CUSTOMER_CODE,A.N_LOAN_CODE,B.COMP_NAME AS N_COMP_NAME,C.COMP_NAME AS O_COMP_NAME
				FROM TEMP_FINAL A LEFT JOIN JK.T_JK_LOAN_COMPANY B ON A.N_LOAN_CODE=B.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=B.DICT_R_CUSTOMTER_TYPE AND A.N_CUSTOMER_CODE=B.R_ID
				                  LEFT JOIN JK.T_JK_LOAN_COMPANY C ON A.O_LOAN_CODE=C.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=C.DICT_R_CUSTOMTER_TYPE AND A.O_CUSTOMER_CODE=C.R_ID
				WHERE COALESCE(B.COMP_NAME,'')<>COALESCE(C.COMP_NAME,'') 
				),
				TEMP_FAMILY AS (--家庭联系人
				SELECT A.DICT_CUSTOMER_TYPE,A.N_LOAN_CODE,A.N_CUSTOMER_CODE,
				       B.CONTACT_NAME AS N_CONTACT_NAME,E.LABEL AS N_CONTACT_TYPE,B.CONTACT_MOBILE AS N_CONTACT_MOBILE,
				       C.CONTACT_NAME AS O_CONTACT_NAME,F.LABEL AS O_CONTACT_TYPE,C.CONTACT_MOBILE AS O_CONTACT_MOBILE
				FROM TEMP_FINAL A LEFT JOIN JK.T_JK_CONTACT B ON A.N_LOAN_CODE=B.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=B.LOAN_CUSTOMTER_TYPE
				                        AND A.N_CUSTOMER_CODE=B.R_CUSTOMER_COBORROWER_ID AND B.RELATION_TYPE='0'
				                  LEFT JOIN JK.T_JK_CONTACT C ON A.O_LOAN_CODE=C.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=C.LOAN_CUSTOMTER_TYPE 
				                        AND A.O_CUSTOMER_CODE=C.R_CUSTOMER_COBORROWER_ID AND C.RELATION_TYPE='0'
				                  LEFT JOIN JK.T_GL_DICT E ON B.CONTACT_RELATION=E.VALUE AND E.TYPE='jk_loan_family_relation'
				                  LEFT JOIN JK.T_GL_DICT F ON C.CONTACT_RELATION=F.VALUE AND F.TYPE='jk_loan_family_relation'
				WHERE (COALESCE(B.CONTACT_NAME,'')=COALESCE(C.CONTACT_NAME,'') AND COALESCE(B.CONTACT_MOBILE,'')<>COALESCE(C.CONTACT_MOBILE,'')) 
				      OR (COALESCE(B.CONTACT_NAME,'')<>COALESCE(C.CONTACT_NAME,'') AND COALESCE(B.CONTACT_MOBILE,'')=COALESCE(C.CONTACT_MOBILE,''))
				)
				INSERT INTO JK.T_JK_INNER_APPLY_CONTRAST
				SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'本人手机',CONCAT_WS(',',NULLIF(N_PHONE_ONE,NULL),NULLIF(N_PHONE_TWO,NULL)),
				       '前次为:'||CONCAT_WS(',',NULLIF(O_PHONE_ONE,NULL),NULLIF(O_PHONE_TWO,NULL)),SYSDATE,'BACK_ADD','BACK_ADD',SYSDATE
				FROM TEMP_FINAL 
				WHERE (COALESCE(N_PHONE_ONE,'')||COALESCE(N_PHONE_TWO,'')) <> (COALESCE(O_PHONE_ONE,'')||COALESCE(O_PHONE_TWO,'')) OR 
				      (COALESCE(N_PHONE_ONE,'')||COALESCE(N_PHONE_TWO,'')) <> (COALESCE(O_PHONE_TWO,'')||COALESCE(O_PHONE_ONE,''))
				UNION ALL
				SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'单位名称',COALESCE(N_COMP_NAME,''),
				       '前次为:'||COALESCE(O_COMP_NAME,''),SYSDATE,'BACK_ADD','BACK_ADD',SYSDATE
				FROM TEMP_UNIT
				UNION ALL
				SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'家庭固话',COALESCE(N_FAMILY_TEL,''),
				       '前次为:'||COALESCE(O_FAMILY_TEL,''),SYSDATE,'BACK_ADD','BACK_ADD',SYSDATE
				FROM TEMP_FINAL
				WHERE COALESCE(N_FAMILY_TEL,'')<>COALESCE(O_FAMILY_TEL,'')
				UNION ALL
				SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'家庭联系人',COALESCE(N_CONTACT_NAME,'')||COALESCE(N_CONTACT_TYPE,'')||COALESCE(N_CONTACT_MOBILE,''),
				       '前次为:'||COALESCE(O_CONTACT_NAME,'')||COALESCE(O_CONTACT_TYPE,'')||COALESCE(O_CONTACT_MOBILE,''),SYSDATE,'BACK_ADD','BACK_ADD',SYSDATE
				FROM TEMP_FAMILY
				UNION ALL
				SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'居住地址',COALESCE(N_ADDERSS,''),
				       '前次为:'||COALESCE(O_ADDERSS,''),SYSDATE,'BACK_ADD','BACK_ADD',SYSDATE
				FROM TEMP_FINAL 
				WHERE COALESCE(N_ADDERSS,'') <> COALESCE(O_ADDERSS,'');
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '3' THEN
		/**
		 * 修改家庭地址  先修改家庭地址信息，再进行查重  
		 */
			UPDATE JK.T_JK_DHZH_DHGXBRSHD B SET LIVE_PROVINCE=SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',1), 
			LIVE_CITY= SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',2), LIVE_AREA= SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',3), 
			LIVE_ADDRESS= SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',4)
			FROM JK.T_JK_DHZH_BRHS A  
			WHERE A.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND A.DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE AND B.R_CUSTOMER_COBORROWER_ID=A.ID
				  AND A.R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND LOAN_ID=DATA_UPDATE.UPDATE_ID;
			INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION, 
			            EXCEPTION_FLAG,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
			SELECT GETUUID32(),DATA_UPDATE.CHANGE_CODE,A.LOAN_CODE,A.R_NAME,DATA_UPDATE.COB_ID,DATA_UPDATE.CHANGE_TYPE,
					A.RELATION,'2','家庭地址',COALESCE(OM2.PNAME,'')||COALESCE(OM2.CNAME,'')||COALESCE(OM2.ANAME,'')||COALESCE(SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',4),''),'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
			FROM JK.T_JK_ADDRESS_POOL A
			LEFT JOIN JK.MVIEW_PROVINCE_CITY OM2 ON SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',3) = OM2.AID
			WHERE A.PROVINCE=SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',1) AND A.CITY = SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',2)
					AND  A.AREA=SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',3) AND A.ADDRESS=SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',4)
					AND A.LOAN_CODE<>DATA_UPDATE.CHANGE_CODE;
			/**
			 * 入池操作
			 */
			INSERT INTO  JK.T_JK_ADDRESS_POOL (ID,LOAN_CODE,R_ID,R_NAME,RELATION,DICT_CUSTOMER_TYPE,PROVINCE,CITY,AREA,ADDRESS,RESOURCE,INCREMENT_ID,REPEAT_VIEW_TYPE) 
			SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,CUSTOMER_NAME AS R_NAME,'本人' AS RELATION,DATA_UPDATE.CHANGE_TYPE AS DICT_CUSTOMER_TYPE,CUSTOMER_LIVE_PROVINCE AS PROVINCE,
				CUSTOMER_LIVE_CITY AS CITY,CUSTOMER_LIVE_AREA AS AREA,CUSTOMER_ADDRESS AS ADDRESS,
				'JK.T_JK_LOAN_CUSTOMER' AS RESOURCE,ID AS INCREMENT_ID,'家庭地址' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_CUSTOMER 
			WHERE LOAN_CODE=loancode AND DATA_UPDATE.CHANGE_TYPE='0' AND ID=DATA_UPDATE.COB_ID
			UNION ALL
			SELECT JK.GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,COBO_NAME AS R_NAME,'共借人' AS RELATION,'1' AS DICT_CUSTOMER_TYPE,COBO_LIVEING_PROVINCE AS PROVINCE,
				COBO_LIVEING_CITY AS CITY,COBO_LIVEING_AREA AS AREA,COBO_NOW_ADDRESS AS ADDRESS,
				'JK.T_JK_LOAN_COBORROWER' AS RESOURCE,ID AS INCREMENT_ID,'家庭地址' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COBORROWER 
			WHERE  LOAN_CODE=loancode AND DATA_UPDATE.CHANGE_TYPE='1' AND ID=DATA_UPDATE.COB_ID;
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '5' THEN
		/**
		 * 修改配偶手机号
		 */
			UPDATE JK.T_JK_DHZH_DHGXSH SET DHGXSH_TEL=DATA_UPDATE.CHANGE_AFTER 
			WHERE LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE 
				  AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND LOAN_ID=DATA_UPDATE.UPDATE_ID;
			INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,
			            EXCEPTION_FLAG,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
			SELECT JK.GETUUID32(),DATA_UPDATE.CHANGE_CODE,A.LOAN_CODE,A.R_NAME,DATA_UPDATE.COB_ID,DATA_UPDATE.CHANGE_TYPE,
					A.RELATION,'2','家庭联系人(配偶)手机号',DATA_UPDATE.CHANGE_AFTER,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
			FROM JK.T_JK_PHONE_POOL A
			WHERE A.PHONE=DATA_UPDATE.CHANGE_AFTER  AND A.LOAN_CODE<>DATA_UPDATE.CHANGE_CODE
					AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE B.PHONE_NUM = DATA_UPDATE.CHANGE_AFTER);
			/**
			 * 入池操作
			 */
			INSERT INTO  JK.T_JK_PHONE_POOL (ID,LOAN_CODE,R_ID,R_NAME,RELATION,DICT_CUSTOMER_TYPE,PHONE,RESOURCE,INCREMENT_ID,REPEAT_VIEW_TYPE)		
			SELECT GETUUID32() AS ID,A.LOAN_CODE,A.R_CUSTOMER_COBORROWER_ID AS R_ID,A.MATE_NAME AS R_NAME,
					'家庭联系人-配偶'  AS RELATION,A.LOAN_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,MATE_TEL AS PHONE,
					'JK.T_JK_LOAN_MATE' AS RESOURCE,A.ID AS INCREMENT_ID,'家庭联系人(配偶)手机号码' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_MATE A LEFT JOIN JK.T_GL_DICT B ON B.TYPE='jk_loan_man_flag' AND A.LOAN_CUSTOMTER_TYPE = B.VALUE
			WHERE A.LOAN_CODE=loancode AND A.LOAN_CUSTOMTER_TYPE=DATA_UPDATE.CHANGE_TYPE AND A.ID=DATA_UPDATE.UPDATE_ID;
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '6' THEN
		/**
		 * 修改配偶身份证
		 */
			
			UPDATE JK.T_JK_DHZH_DHGXSH SET CUSTOMER_CERT_NUM=DATA_UPDATE.CHANGE_AFTER 
			WHERE LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE 
				  AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND LOAN_ID=DATA_UPDATE.UPDATE_ID;
			UPDATE 	JK.T_JK_PRIVATE_NETWORK_CHECK SET CONTENT=DATA_UPDATE.CHANGE_AFTER
			WHERE LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND CONTENT=DATA_UPDATE.CHANGE_BEGIN;
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '7' THEN
		/**
		 * 修改配偶姓名
		 */
			UPDATE JK.T_JK_DHZH_DHGXSH SET NAME=DATA_UPDATE.CHANGE_AFTER 
			WHERE LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE 
				  AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND LOAN_ID=DATA_UPDATE.UPDATE_ID;
			UPDATE JK.T_JK_PRIVATE_NETWORK_CHECK A SET NAME=DATA_UPDATE.CHANGE_AFTER
			FROM JK.T_JK_DHZH_DHGXSH B
			WHERE B.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND B.LOAN_ID=DATA_UPDATE.UPDATE_ID  AND B.DICT_CHECK_TYPE=checkType
				  AND A.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND a.content=b.CUSTOMER_CERT_NUM AND A.NAME=DATA_UPDATE.CHANGE_BEGIN;
			/**
			 * 更新查重信息  和 查重池中对应的名字
			 */	  
			UPDATE JK.T_JK_INNER_REPEAT SET REPEAT_VIEW_TYPE=REPLACE(REPEAT_VIEW_TYPE,DATA_UPDATE.CHANGE_BEGIN,DATA_UPDATE.CHANGE_AFTER)
			WHERE LOAN_CODE=loancode AND LOAN_CUSTOMER_CODE=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE;
			
			UPDATE JK.T_JK_PHONE_POOL SET R_NAME=DATA_UPDATE.CHANGE_AFTER
			WHERE LOAN_CODE=loancode AND R_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
			AND R_NAME=DATA_UPDATE.CHANGE_BEGIN AND INCREMENT_ID=DATA_UPDATE.UPDATE_ID;
			
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '8' THEN
		/**
		 * 修改单位名称
		 */
			UPDATE JK.T_JK_TEL_AUDIT_WORK SET WORK_UNITNAME=DATA_UPDATE.CHANGE_AFTER 
			WHERE LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE 
				  AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND LOAN_ID=DATA_UPDATE.UPDATE_ID;	
			UPDATE JK.T_JK_PRIVATE_NETWORK_CHECK A SET CONTENT=DATA_UPDATE.CHANGE_AFTER
			FROM JK.T_JK_TEL_AUDIT_WORK B
			WHERE B.LOAN_ID=DATA_UPDATE.UPDATE_ID AND A.WORK_ID=B.ID AND A.LOAN_CODE=DATA_UPDATE.CHANGE_CODE
					AND B.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND A.CONTENT=DATA_UPDATE.CHANGE_BEGIN;
					
			INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,
						REPEAT_RELATION,EXCEPTION_FLAG,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
			SELECT GETUUID32(),DATA_UPDATE.CHANGE_CODE,A.LOAN_CODE,A.R_NAME,DATA_UPDATE.COB_ID,DATA_UPDATE.CHANGE_TYPE,
					A.RELATION,'2','单位名称',DATA_UPDATE.CHANGE_AFTER,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
			FROM JK.T_JK_WORK_NAME_POOL A
			WHERE A.WORK_NAME=DATA_UPDATE.CHANGE_AFTER  AND A.LOAN_CODE<>DATA_UPDATE.CHANGE_CODE;
		/**
		 * 入池
		 */	  
			INSERT INTO  JK.T_JK_WORK_NAME_POOL (ID,LOAN_CODE,R_ID,R_NAME,RELATION,DICT_CUSTOMER_TYPE,WORK_NAME,RESOURCE,INCREMENT_ID,REPEAT_VIEW_TYPE) 
			SELECT GETUUID32() AS ID,A.LOAN_CODE,A.R_ID,CASE WHEN A.DICT_R_CUSTOMTER_TYPE='0' THEN B.CUSTOMER_NAME WHEN 
				 A.DICT_R_CUSTOMTER_TYPE='1' THEN C.COBO_NAME END AS R_NAME,CASE WHEN A.DICT_R_CUSTOMTER_TYPE='0' THEN '本人' WHEN A.DICT_R_CUSTOMTER_TYPE='1' THEN '共借人' 
				 END AS RELATION,A.DICT_R_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,JK.FILTERCOMPANYNAME(A.COMP_NAME) AS WORK_NAME,
				'JK.T_JK_LOAN_COMPANY' AS RESOURCE,A.ID AS INCREMENT_ID,'单位名称' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COMPANY A
				LEFT JOIN JK.T_JK_LOAN_CUSTOMER B ON A.R_ID = B.ID AND A.DICT_R_CUSTOMTER_TYPE='0'
				LEFT JOIN JK.T_JK_LOAN_COBORROWER C ON A.R_ID = C.ID AND A.DICT_R_CUSTOMTER_TYPE='1'
			WHERE  A.LOAN_CODE=loancode AND A.ID=DATA_UPDATE.UPDATE_ID;	 	  
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '9' THEN
		/**
		 * 修改单位地址
		 */
			UPDATE JK.T_JK_TEL_AUDIT_WORK  SET WORK_PROVINCE=SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',1), 
											WORK_CITY= SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',2), 
											WORK_DISTRICT= SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',3), 
											WORK_ADDRESS= SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',4)
			WHERE LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE 
				  AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND LOAN_ID=DATA_UPDATE.UPDATE_ID;
			INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,
			            EXCEPTION_FLAG,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
			SELECT GETUUID32(),DATA_UPDATE.CHANGE_CODE,A.LOAN_CODE,A.R_NAME,DATA_UPDATE.COB_ID,DATA_UPDATE.CHANGE_TYPE,
					A.RELATION,'2','单位地址',COALESCE(OM2.PNAME,'')||COALESCE(OM2.CNAME,'')||COALESCE(OM2.ANAME,'')||COALESCE(SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',4),''),'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
			FROM JK.T_JK_ADDRESS_POOL A
			LEFT JOIN JK.MVIEW_PROVINCE_CITY OM2 ON SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',3) = OM2.AID
			WHERE A.PROVINCE=SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',1) AND A.CITY = SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',2)
					AND  A.AREA=SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',3) AND A.ADDRESS=SPLIT_PART(DATA_UPDATE.CHANGE_AFTER,',',4)
					AND A.LOAN_CODE<>DATA_UPDATE.CHANGE_CODE;
			/**
			 * 单位地址
			 */		
			INSERT INTO  JK.T_JK_ADDRESS_POOL (ID,LOAN_CODE,R_ID,R_NAME,RELATION,DICT_CUSTOMER_TYPE,PROVINCE,CITY,AREA,ADDRESS,RESOURCE,INCREMENT_ID,REPEAT_VIEW_TYPE)
			SELECT GETUUID32() AS ID,A.LOAN_CODE,A.R_ID,CASE WHEN A.DICT_R_CUSTOMTER_TYPE='0' THEN B.CUSTOMER_NAME WHEN  A.DICT_R_CUSTOMTER_TYPE='1' THEN C.COBO_NAME
			 	END AS R_NAME,CASE WHEN A.DICT_R_CUSTOMTER_TYPE='0' THEN '本人'
			  	WHEN A.DICT_R_CUSTOMTER_TYPE='1' THEN '共借人' END  AS RELATION,
			 	A.DICT_R_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,A.COMP_PROVINCE AS PROVINCE,A.COMP_CITY AS CITY,
				A.COMP_ARER AS AREA,A.COMP_ADDRESS AS ADDRESS,'JK.T_JK_LOAN_COMPANY' AS RESOURCE,A.ID AS INCREMENT_ID,'单位地址' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COMPANY A
				LEFT JOIN JK.T_JK_LOAN_CUSTOMER B ON A.R_ID = B.ID AND A.DICT_R_CUSTOMTER_TYPE='0'
				LEFT JOIN JK.T_JK_LOAN_COBORROWER C ON A.R_ID = C.ID AND A.DICT_R_CUSTOMTER_TYPE='1'
			WHERE A.LOAN_CODE=loancode AND A.DICT_R_CUSTOMTER_TYPE=DATA_UPDATE.CHANGE_TYPE AND A.ID=DATA_UPDATE.UPDATE_ID;
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '10'  THEN
		/**
		 * 修改家庭固话
		 */
				IF  CHAR_LENGTH(DATA_UPDATE.CHANGE_BEGIN)=0 THEN
					INSERT INTO JK.T_JK_DHZH_BRHS_DHXX(ID,R_BRHS_ID,BRHS_PHONE,BRHS_NEW_ADD,WORK_NET_ASSESS_RESULT,IS_REPEAT,IS_IN_POOL,TYPE,SOURCE,EDIT_REMARK,LOAN_ID)
					SELECT GETUUID32(),ID,DATA_UPDATE.CHANGE_AFTER,'0','0','1','1','0','01','1',DATA_UPDATE.UPDATE_ID
					FROM JK.T_JK_DHZH_BRHS
					WHERE  LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
						   AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND DICT_CHECK_TYPE=checkType; 
				ELSIF CHAR_LENGTH(DATA_UPDATE.CHANGE_AFTER)=0  THEN
					DELETE FROM JK.T_JK_DHZH_BRHS_DHXX B
					USING JK.T_JK_DHZH_BRHS A
					WHERE B.R_BRHS_ID=A.ID AND B.BRHS_PHONE=DATA_UPDATE.CHANGE_BEGIN AND B.LOAN_ID=DATA_UPDATE.UPDATE_ID 
						   AND A.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND A.DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
						   AND A.R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID; 
				ELSE
					SELECT INTO TEMP_NUM COUNT(B.ID) FROM JK.T_JK_DHZH_BRHS_DHXX B
					LEFT JOIN T_JK_DHZH_BRHS A ON A.ID=B.R_BRHS_ID
					WHERE B.BRHS_PHONE=DATA_UPDATE.CHANGE_BEGIN AND B.LOAN_ID=DATA_UPDATE.UPDATE_ID 
						   AND A.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND A.DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
						   AND A.R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID; 
					IF TEMP_NUM = 0 THEN
						INSERT INTO JK.T_JK_DHZH_BRHS_DHXX(ID,R_BRHS_ID,BRHS_PHONE,BRHS_NEW_ADD,WORK_NET_ASSESS_RESULT,IS_REPEAT,IS_IN_POOL,TYPE,SOURCE,EDIT_REMARK,LOAN_ID)
						SELECT GETUUID32(),ID,DATA_UPDATE.CHANGE_AFTER,'0','0','1','1','0','01','1',DATA_UPDATE.UPDATE_ID
						FROM JK.T_JK_DHZH_BRHS
						WHERE  LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
						       AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND DICT_CHECK_TYPE=checkType; 
					ELSE 
						UPDATE JK.T_JK_DHZH_BRHS_DHXX B SET BRHS_PHONE=DATA_UPDATE.CHANGE_AFTER
						FROM JK.T_JK_DHZH_BRHS A WHERE B.R_BRHS_ID=A.ID AND B.BRHS_PHONE=DATA_UPDATE.CHANGE_BEGIN AND B.LOAN_ID=DATA_UPDATE.UPDATE_ID 
						AND A.LOAN_CODE=loancode AND A.R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND A.DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE;
					END IF;
				END IF;
			/**
			 * 查重
			 */
			INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,
			            EXCEPTION_FLAG,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
			SELECT GETUUID32(),DATA_UPDATE.CHANGE_CODE,A.LOAN_CODE,A.R_NAME,DATA_UPDATE.COB_ID,DATA_UPDATE.CHANGE_TYPE,
					A.RELATION,'2','家庭固话',DATA_UPDATE.CHANGE_AFTER,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
			FROM JK.T_JK_PHONE_POOL A
			WHERE A.PHONE=DATA_UPDATE.CHANGE_AFTER  AND A.LOAN_CODE<>DATA_UPDATE.CHANGE_CODE
					AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE B.PHONE_NUM = DATA_UPDATE.CHANGE_AFTER);
			/**
			 * 入池
			 */
			INSERT INTO  JK.T_JK_PHONE_POOL (ID,LOAN_CODE,R_ID,R_NAME,RELATION,DICT_CUSTOMER_TYPE,PHONE,RESOURCE,INCREMENT_ID,REPEAT_VIEW_TYPE)
			SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,CUSTOMER_NAME AS R_NAME,'本人'  AS RELATION,
					'0' AS DICT_CUSTOMER_TYPE,CUSTOMER_TEL AS PHONE,'JK.T_JK_LOAN_CUSTOMER' AS RESOURCE,ID AS INCREMENT_ID,'家庭固话' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_CUSTOMER 
			WHERE LOAN_CODE=loancode AND DATA_UPDATE.CHANGE_TYPE='0' AND ID=DATA_UPDATE.UPDATE_ID
			UNION ALL
			SELECT GETUUID32() AS ID,LOAN_CODE,ID AS R_ID,COBO_NAME AS R_NAME,'共借人'  AS RELATION,
					'1' AS DICT_CUSTOMER_TYPE,COBO_NOW_TEL AS PHONE,'JK.T_JK_LOAN_COBORROWER' AS RESOURCE,ID AS INCREMENT_ID,'家庭固话' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COBORROWER 
			WHERE LOAN_CODE=loancode AND DATA_UPDATE.CHANGE_TYPE='0' AND ID=DATA_UPDATE.UPDATE_ID;
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '11' THEN
		/**
		 * 修改单位固话
		 */
			UPDATE JK.T_JK_DHZH_WORK_TELNUM B SET WORK_UNIT_TEL=DATA_UPDATE.CHANGE_AFTER
			FROM JK.T_JK_TEL_AUDIT_WORK A 
			WHERE B.WORK_ID=A.ID AND B.WORK_UNIT_TEL=DATA_UPDATE.CHANGE_BEGIN AND B.LOAN_ID=DATA_UPDATE.UPDATE_ID 
			AND A.LOAN_CODE=loancode AND A.R_CUSTOMER_COBORROWER_ID=DATA_UPDATE.COB_ID AND A.DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE;
			INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,
			            EXCEPTION_FLAG,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
			SELECT GETUUID32(),DATA_UPDATE.CHANGE_CODE,A.LOAN_CODE,A.R_NAME,DATA_UPDATE.COB_ID,DATA_UPDATE.CHANGE_TYPE,
					A.RELATION,'2','单位固话',DATA_UPDATE.CHANGE_AFTER,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
			FROM JK.T_JK_PHONE_POOL A
			WHERE A.PHONE=DATA_UPDATE.CHANGE_AFTER  AND A.LOAN_CODE<>DATA_UPDATE.CHANGE_CODE
				AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE B.PHONE_NUM = DATA_UPDATE.CHANGE_AFTER);
			/**
			 * 入池
			 */
			INSERT INTO  JK.T_JK_PHONE_POOL (ID,LOAN_CODE,R_ID,R_NAME,RELATION,DICT_CUSTOMER_TYPE,PHONE,RESOURCE,INCREMENT_ID,REPEAT_VIEW_TYPE)
			SELECT GETUUID32() AS ID,A.LOAN_CODE,A.R_ID AS R_ID,CASE WHEN A.DICT_R_CUSTOMTER_TYPE='0' THEN B.CUSTOMER_NAME
				    WHEN  A.DICT_R_CUSTOMTER_TYPE='0' THEN B.CUSTOMER_NAME WHEN A.DICT_R_CUSTOMTER_TYPE='1' THEN C.COBO_NAME END AS R_NAME,
					CASE WHEN A.DICT_R_CUSTOMTER_TYPE='0' THEN '本人' WHEN A.DICT_R_CUSTOMTER_TYPE='1' THEN '共借人' END AS RELATION,
					A.DICT_R_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,COMP_TEL AS PHONE,
					'JK.T_JK_LOAN_COMPANY' AS RESOURCE,A.ID AS INCREMENT_ID,'单位固话' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COMPANY A LEFT JOIN JK.T_JK_LOAN_CUSTOMER B ON A.R_ID = B.ID AND A.DICT_R_CUSTOMTER_TYPE='0'
					LEFT JOIN JK.T_JK_LOAN_COBORROWER C ON A.R_ID = C.ID AND A.DICT_R_CUSTOMTER_TYPE='1'
			WHERE  A.LOAN_CODE=loancode	AND A.DICT_R_CUSTOMTER_TYPE=DATA_UPDATE.CHANGE_TYPE AND A.ID=DATA_UPDATE.UPDATE_ID;
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '13' THEN
		/**
		 * 修改联系人电话
		 */
			UPDATE JK.T_JK_DHZH_DHGXSH SET DHGXSH_TEL=DATA_UPDATE.CHANGE_AFTER 
			WHERE LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE 
				  AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND LOAN_ID=DATA_UPDATE.UPDATE_ID;
			INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,
			            EXCEPTION_FLAG,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
			SELECT GETUUID32(),DATA_UPDATE.CHANGE_CODE,A.LOAN_CODE,A.R_NAME,DATA_UPDATE.COB_ID,DATA_UPDATE.CHANGE_TYPE,
					A.RELATION,'2',COALESCE(D.LABEL,'')||'-'||COALESCE(E.LABEL,'')||'('||COALESCE(C.NAME,'')||')'||'手机号码',
					DATA_UPDATE.CHANGE_AFTER,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
			FROM JK.T_JK_PHONE_POOL A
			LEFT JOIN JK.T_JK_DHZH_DHGXSH C ON C.LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND C.DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE 
				  AND C.R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND C.LOAN_ID=DATA_UPDATE.UPDATE_ID
			LEFT JOIN JK.T_GL_DICT D ON C.DICT_RELATION_TYPE=D.VALUE AND D.TYPE='jk_relation_type'
            LEFT JOIN JK.T_GL_DICT E ON C.LOAN_MAN_RELATION=E.VALUE AND D.ID=E.PARENT_ID	  
			WHERE A.PHONE=DATA_UPDATE.CHANGE_AFTER  AND A.LOAN_CODE<>DATA_UPDATE.CHANGE_CODE
				AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE B.PHONE_NUM = DATA_UPDATE.CHANGE_AFTER);
			/**
			 * 入池
			 */
			INSERT INTO  JK.T_JK_PHONE_POOL (ID,LOAN_CODE,R_ID,R_NAME,RELATION,DICT_CUSTOMER_TYPE,PHONE,RESOURCE,INCREMENT_ID,REPEAT_VIEW_TYPE)
						SELECT GETUUID32() AS ID,A.LOAN_CODE,A.R_CUSTOMER_COBORROWER_ID AS R_ID,A.CONTACT_NAME AS R_NAME,
					CONCAT(B.LABEL,'-',C.LABEL) AS RELATION,A.LOAN_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,
					CONTACT_MOBILE AS PHONE,'JK.T_JK_CONTACT' AS RESOURCE,A.ID AS INCREMENT_ID,CONCAT(B.LABEL,'-',C.LABEL,'(',CONTACT_NAME,')手机号码') AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_CONTACT A LEFT JOIN JK.T_GL_DICT B ON B.TYPE='jk_relation_type' AND A.RELATION_TYPE = B.VALUE
					LEFT JOIN JK.T_GL_DICT C ON C.PARENT_ID=B.ID AND A.CONTACT_RELATION = C.VALUE
			WHERE A.LOAN_CODE=loancode	 AND A.LOAN_CUSTOMTER_TYPE=DATA_UPDATE.CHANGE_TYPE AND A.ID=DATA_UPDATE.UPDATE_ID;
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '14' THEN
		/**
		 * 修改联系人姓名
		 */
			UPDATE JK.T_JK_DHZH_DHGXSH SET NAME=DATA_UPDATE.CHANGE_AFTER 
			WHERE LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE AND NAME=DATA_UPDATE.CHANGE_BEGIN
				  AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND LOAN_ID=DATA_UPDATE.UPDATE_ID;
			/**
			 * 更新查重信息  和 查重池中对应的名字
			 */		
			UPDATE JK.T_JK_INNER_REPEAT SET REPEAT_VIEW_TYPE=REPLACE(REPEAT_VIEW_TYPE,DATA_UPDATE.CHANGE_BEGIN,DATA_UPDATE.CHANGE_AFTER)
			WHERE LOAN_CODE=loancode AND LOAN_CUSTOMER_CODE=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE;
			
			UPDATE JK.T_JK_PHONE_POOL SET R_NAME=DATA_UPDATE.CHANGE_AFTER
			WHERE LOAN_CODE=loancode AND R_ID=DATA_UPDATE.COB_ID AND DICT_CUSTOMER_TYPE=DATA_UPDATE.CHANGE_TYPE
			AND R_NAME=DATA_UPDATE.CHANGE_BEGIN AND INCREMENT_ID=DATA_UPDATE.UPDATE_ID;
			
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '20' THEN
		/**
		 * 修改联系人大关系
		 */
			UPDATE JK.T_JK_DHZH_DHGXSH SET DICT_RELATION_TYPE=DATA_UPDATE.CHANGE_AFTER 
			WHERE LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE AND DICT_RELATION_TYPE=DATA_UPDATE.CHANGE_BEGIN
				  AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND LOAN_ID=DATA_UPDATE.UPDATE_ID;
		ELSIF  DATA_UPDATE.CHANGE_RESULT = '21' THEN
		/**
		 * 修改联系人小关系
		 */
			UPDATE JK.T_JK_DHZH_DHGXSH SET LOAN_MAN_RELATION=DATA_UPDATE.CHANGE_AFTER 
			WHERE LOAN_CODE=DATA_UPDATE.CHANGE_CODE AND DICT_CUSTOMER_TYPE = DATA_UPDATE.CHANGE_TYPE AND LOAN_MAN_RELATION=DATA_UPDATE.CHANGE_BEGIN
				  AND R_CUSTOMER_COBORROWER_ID = DATA_UPDATE.COB_ID AND LOAN_ID=DATA_UPDATE.UPDATE_ID;
		END IF;
	END IF;
END LOOP;
END IF;
/*****************************历史归户开始******************************/
INSERT INTO JK.T_JK_INNER_CUSTOMER_HIS(ID, CUSTOMER_CODE,LOAN_CODE, APPLY_TIME, 
				    PRODUCT_TYPE, DICT_CHECK_STATUS, HIS_REFUSE_RESON,
                    HIS_AMOUNT_MONTHS,DICT_CUSTOMER_TYPE, CREATE_BY, CREATE_TIME,
                    MODIFY_BY, MODIFY_TIME,HIS_LOAN_CODE)
SELECT GETUUID32() AS ID,A.CUSTOMER_CODE,loancode,B.OUTTO_LOAN_TIME,F.PRODUCT_NAME,G.LABEL AS DICT_CHECK_STATUS,
      C.REFUSE_REASON AS HIS_REFUSE_RESON,B.LOAN_AUDIT_AMOUNT ||'/'|| B.LOAN_AUDIT_MONTHS AS HIS_AMOUNT_MONTHS,
       A.DICT_CUSTOMER_TYPE,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,A.LOAN_CODE AS HIS_LOAN_CODE
FROM
	(   
		SELECT A.ID AS CUSTOMER_CODE,B.LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE
		FROM JK.T_JK_LOAN_COBORROWER A 
		INNER JOIN JK.T_JK_LOAN_COBORROWER B ON A.LOAN_CODE=loancode AND B.LOAN_CODE<>loancode  
					AND A.COBO_CERT_NUM=B.COBO_CERT_NUM AND COALESCE(A.INCLUDE_POOL_FLAG,'') = ''
		UNION ALL
		SELECT A.ID AS CUSTOMER_CODE,B.LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE
		FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_CUSTOMER B ON A.LOAN_CODE=loancode
					AND COALESCE(A.INCLUDE_POOL_FLAG,'') = '' AND A.COBO_CERT_NUM=B.CUSTOMER_CERT_NUM) A
INNER JOIN JK.T_JK_LOAN_INFO B ON A.LOAN_CODE=B.LOAN_CODE AND B.OUTTO_LOAN_TIME IS NOT NULL
LEFT JOIN JK.T_JK_AUDIT_RECORD C ON B.AUDIT_ID=C.ID
LEFT JOIN JK.T_GL_JK_PRODUCT F ON B.PRODUCT_TYPE=F.PRODUCT_CODE
LEFT JOIN JK.T_GL_DICT G ON G.VALUE=B.DICT_LOAN_STATUS AND G.TYPE='jk_loan_apply_status'
GROUP BY A.LOAN_CODE,B.LOAN_APPLY_TIME,F.PRODUCT_NAME,G.LABEL,C.REFUSE_REASON,B.OUTTO_LOAN_TIME,
B.LOAN_AUDIT_AMOUNT,B.LOAN_AUDIT_MONTHS,A.DICT_CUSTOMER_TYPE,A.CUSTOMER_CODE;
/*****************************历史归户结束******************************/
/**
 * 当前借款申请的信息，与同一个借款人的前一次历史借款申请的信息进行比较
 * 数据对象：共借人
 * 比较对象：手机号码1、手机号码2、居住地址、单位名称、家庭联系人-关系|姓名|手机号
 */
/****************************历史异常对比开始****************************/
WITH TMEP_COBO AS (--共借人
SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,
       O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,
       DICT_CUSTOMER_TYPE
FROM
(
	SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,
	       O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,
	       DICT_CUSTOMER_TYPE,ROW_NUMBER() OVER(PARTITION BY N_CUSTOMER_CODE ORDER BY CREATE_TIME DESC) AS ROW_NO
	FROM
	(
		SELECT COALESCE(A.COBO_MOBILE,'') AS N_PHONE_ONE,COALESCE(A.COBO_MOBILE2,'') AS N_PHONE_TWO,A.LOAN_CODE AS N_LOAN_CODE,
		       NM1.AREA_NAME||NM2.AREA_NAME||NM3.AREA_NAME||A.COBO_NOW_ADDRESS AS N_ADDERSS,A.ID AS N_CUSTOMER_CODE,A.COBO_FAMILY_TEL N_FAMILY_TEL,
		       B.CUSTOMER_PHONE_FIRST AS O_PHONE_ONE,B.CUSTOMER_PHONE_SECOND AS O_PHONE_TWO,B.LOAN_CODE AS O_LOAN_CODE,
		       OM1.AREA_NAME||OM2.AREA_NAME||OM3.AREA_NAME||B.CUSTOMER_ADDRESS AS O_ADDERSS,B.ID AS O_CUSTOMER_CODE,B.CUSTOMER_TEL O_FAMILY_TEL,
		       '1' AS DICT_CUSTOMER_TYPE,B.CREATE_TIME
		FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_CUSTOMER B ON A.LOAN_CODE=loancode--'400000316621921' 
										AND COALESCE(A.INCLUDE_POOL_FLAG,'') = ''
					  					AND A.COBO_CERT_NUM=B.CUSTOMER_CERT_NUM AND B.LOAN_CODE<>loancode--'400000316621921'
					  				  LEFT JOIN JK.T_GL_PROVINCE_CITY NM1 ON A.COBO_LIVEING_PROVINCE = NM1.AREA_CODE AND NM1.AREA_TYPE = '1'
									  LEFT JOIN JK.T_GL_PROVINCE_CITY NM2 ON A.COBO_LIVEING_CITY = NM2.AREA_CODE AND NM2.AREA_TYPE = '2'
		                              LEFT JOIN JK.T_GL_PROVINCE_CITY NM3 ON A.COBO_LIVEING_AREA = NM3.AREA_CODE AND NM3.AREA_TYPE = '3'
					                  LEFT JOIN JK.T_GL_PROVINCE_CITY OM1 ON B.CUSTOMER_LIVE_PROVINCE = OM1.AREA_CODE AND OM1.AREA_TYPE = '1'
		                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM2 ON B.CUSTOMER_LIVE_CITY = OM2.AREA_CODE AND OM2.AREA_TYPE = '2'
		                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM3 ON B.CUSTOMER_LIVE_AREA = OM3.AREA_CODE AND OM3.AREA_TYPE = '3'
		UNION ALL
		SELECT COALESCE(A.COBO_MOBILE,'') AS N_PHONE_ONE,COALESCE(A.COBO_MOBILE2,'') AS N_PHONE_TWO,A.LOAN_CODE AS N_LOAN_CODE,
		       NM1.AREA_NAME||NM2.AREA_NAME||NM3.AREA_NAME||A.COBO_NOW_ADDRESS AS N_ADDERSS,A.ID AS N_CUSTOMER_CODE,A.COBO_FAMILY_TEL N_FAMILY_TEL,
		       B.COBO_MOBILE AS O_PHONE_ONE,B.COBO_MOBILE2 AS O_PHONE_TWO,B.LOAN_CODE AS O_LOAN_CODE,
		       OM1.AREA_NAME||OM2.AREA_NAME||OM3.AREA_NAME||B.COBO_NOW_ADDRESS AS O_ADDERSS,B.ID AS O_CUSTOMER_CODE,B.COBO_FAMILY_TEL O_FAMILY_TEL,
		       '1' AS DICT_CUSTOMER_TYPE,B.CREATE_TIME
		FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_COBORROWER B ON A.LOAN_CODE=loancode--'400000316621921' 
										AND COALESCE(A.INCLUDE_POOL_FLAG,'') = ''
					  					AND A.COBO_CERT_NUM=B.COBO_CERT_NUM AND B.LOAN_CODE<>loancode--'400000316621921'
				  				  LEFT JOIN JK.T_GL_PROVINCE_CITY NM1 ON A.COBO_LIVEING_PROVINCE = NM1.AREA_CODE AND NM1.AREA_TYPE = '1'
								  LEFT JOIN JK.T_GL_PROVINCE_CITY NM2 ON A.COBO_LIVEING_CITY = NM2.AREA_CODE AND NM2.AREA_TYPE = '2'
	                              LEFT JOIN JK.T_GL_PROVINCE_CITY NM3 ON A.COBO_LIVEING_AREA = NM3.AREA_CODE AND NM3.AREA_TYPE = '3'
				                  LEFT JOIN JK.T_GL_PROVINCE_CITY OM1 ON B.COBO_LIVEING_PROVINCE = OM1.AREA_CODE AND OM1.AREA_TYPE = '1'
	                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM2 ON B.COBO_LIVEING_CITY = OM2.AREA_CODE AND OM2.AREA_TYPE = '2'
	                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM3 ON B.COBO_LIVEING_AREA = OM3.AREA_CODE AND OM3.AREA_TYPE = '3'
	) A
) B
WHERE ROW_NO=1
),
TEMP_FINAL AS (--共借人
SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,DICT_CUSTOMER_TYPE
FROM TMEP_COBO
),
TEMP_UNIT AS (--单位名称
SELECT A.DICT_CUSTOMER_TYPE,A.N_CUSTOMER_CODE,A.N_LOAN_CODE,B.COMP_NAME AS N_COMP_NAME,C.COMP_NAME AS O_COMP_NAME
FROM TEMP_FINAL A LEFT JOIN JK.T_JK_LOAN_COMPANY B ON A.N_LOAN_CODE=B.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=B.DICT_R_CUSTOMTER_TYPE AND A.N_CUSTOMER_CODE=B.R_ID
                  LEFT JOIN JK.T_JK_LOAN_COMPANY C ON A.O_LOAN_CODE=C.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=C.DICT_R_CUSTOMTER_TYPE AND A.O_CUSTOMER_CODE=C.R_ID
WHERE COALESCE(B.COMP_NAME,'')<>COALESCE(C.COMP_NAME,'') 
),
TEMP_FAMILY AS (--家庭联系人
SELECT A.DICT_CUSTOMER_TYPE,A.N_LOAN_CODE,A.N_CUSTOMER_CODE,
       B.CONTACT_NAME AS N_CONTACT_NAME,E.LABEL AS N_CONTACT_TYPE,B.CONTACT_MOBILE AS N_CONTACT_MOBILE,
       C.CONTACT_NAME AS O_CONTACT_NAME,F.LABEL AS O_CONTACT_TYPE,C.CONTACT_MOBILE AS O_CONTACT_MOBILE
FROM TEMP_FINAL A LEFT JOIN JK.T_JK_CONTACT B ON A.N_LOAN_CODE=B.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=B.LOAN_CUSTOMTER_TYPE
                        AND A.N_CUSTOMER_CODE=B.R_CUSTOMER_COBORROWER_ID AND B.RELATION_TYPE='0'
                  LEFT JOIN JK.T_JK_CONTACT C ON A.O_LOAN_CODE=C.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=C.LOAN_CUSTOMTER_TYPE 
                        AND A.O_CUSTOMER_CODE=C.R_CUSTOMER_COBORROWER_ID AND C.RELATION_TYPE='0'
                  LEFT JOIN JK.T_GL_DICT E ON B.CONTACT_RELATION=E.VALUE AND E.TYPE='jk_loan_family_relation'
                  LEFT JOIN JK.T_GL_DICT F ON C.CONTACT_RELATION=F.VALUE AND F.TYPE='jk_loan_family_relation'
WHERE (COALESCE(B.CONTACT_NAME,'')=COALESCE(C.CONTACT_NAME,'') AND COALESCE(B.CONTACT_MOBILE,'')<>COALESCE(C.CONTACT_MOBILE,'')) 
      OR (COALESCE(B.CONTACT_NAME,'')<>COALESCE(C.CONTACT_NAME,'') AND COALESCE(B.CONTACT_MOBILE,'')=COALESCE(C.CONTACT_MOBILE,''))
)
INSERT INTO JK.T_JK_INNER_APPLY_CONTRAST
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'本人手机',CONCAT_WS(',',NULLIF(N_PHONE_ONE,NULL),NULLIF(N_PHONE_TWO,NULL)),
       '前次为:'||CONCAT_WS(',',NULLIF(O_PHONE_ONE,NULL),NULLIF(O_PHONE_TWO,NULL)),SYSDATE,'BACK_ADD','BACK_ADD',SYSDATE
FROM TEMP_FINAL 
WHERE (COALESCE(N_PHONE_ONE,'')||COALESCE(N_PHONE_TWO,'')) <> (COALESCE(O_PHONE_ONE,'')||COALESCE(O_PHONE_TWO,'')) OR 
      (COALESCE(N_PHONE_ONE,'')||COALESCE(N_PHONE_TWO,'')) <> (COALESCE(O_PHONE_TWO,'')||COALESCE(O_PHONE_ONE,''))
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'单位名称',COALESCE(N_COMP_NAME,''),
       '前次为:'||COALESCE(O_COMP_NAME,''),SYSDATE,'BACK_ADD','BACK_ADD',SYSDATE
FROM TEMP_UNIT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'家庭固话',COALESCE(N_FAMILY_TEL,''),
       '前次为:'||COALESCE(O_FAMILY_TEL,''),SYSDATE,'BACK_ADD','BACK_ADD',SYSDATE
FROM TEMP_FINAL
WHERE COALESCE(N_FAMILY_TEL,'')<>COALESCE(O_FAMILY_TEL,'')
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'家庭联系人',COALESCE(N_CONTACT_NAME,'')||COALESCE(N_CONTACT_TYPE,'')||COALESCE(N_CONTACT_MOBILE,''),
       '前次为:'||COALESCE(O_CONTACT_NAME,'')||COALESCE(O_CONTACT_TYPE,'')||COALESCE(O_CONTACT_MOBILE,''),SYSDATE,'BACK_ADD','BACK_ADD',SYSDATE
FROM TEMP_FAMILY
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'居住地址',COALESCE(N_ADDERSS,''),
       '前次为:'||COALESCE(O_ADDERSS,''),SYSDATE,'BACK_ADD','BACK_ADD',SYSDATE
FROM TEMP_FINAL 
WHERE COALESCE(N_ADDERSS,'') <> COALESCE(O_ADDERSS,'');
/****************************历史异常对比结束****************************/

/**
 * 当前借款申请的信息，与历史借款信息进行比较
 * 数据对象：共借人
 * 比较对象：手机号码1、手机号码2、家庭固话、联系人电话、配偶电话、居住地址、单位地址、单位名称、
 */
/*****************************内网查重开始******************************/
--------号码类
WITH TEMP_PHONE_FINAL AS (
SELECT A.*,C.OUTTO_LOAN_TIME AS O_INTO_TIME,C.LOAN_CUSTOMER_NAME AS O_MAIN_NAME,OM1.PRODUCT_NAME AS O_PRODUCT_NAME
FROM
(	SELECT 
	A.LOAN_CODE AS N_LOAN_CODE,A.DICT_CUSTOMER_TYPE AS N_DICT_CUSTOMER_TYPE,A.CUSTOMER_CODE AS N_CUSTOMER_CODE,A.PHONE_NUMBER,A.REPEAT_VIEW_TYPE N_REPEAT_VIEW_TYPE,
	B.LOAN_CODE AS O_LOAN_CODE,B.R_NAME AS O_NAME,B.DICT_CUSTOMER_TYPE AS O_DICT_CUSTOMER_TYPE,B.R_ID AS O_CUSTOMER_CODE,B.RELATION AS O_RELATION,B.REPEAT_VIEW_TYPE O_REPEAT_VIEW_TYPE,
	ROW_NUMBER() OVER(PARTITION BY A.LOAN_CODE,A.REPEAT_VIEW_TYPE,A.PHONE_NUMBER,A.CUSTOMER_CODE ORDER BY A.LOAN_CODE DESC) AS ROW_NO 
		FROM
			(
			SELECT ID AS CUSTOMER_CODE,LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE,COBO_MOBILE AS PHONE_NUMBER,'手机号码' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COBORROWER WHERE LOAN_CODE=loancode AND COALESCE(COBO_MOBILE,'')<>''
			AND COALESCE(INCLUDE_POOL_FLAG,'') = '' AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE JK.T_JK_LOAN_COBORROWER.COBO_MOBILE=B.PHONE_NUM)
			UNION ALL
			SELECT ID AS CUSTOMER_CODE,LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE,COBO_MOBILE2 AS PHONE_NUMBER,'手机号码' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COBORROWER WHERE LOAN_CODE=loancode AND COALESCE(COBO_MOBILE2,'')<>''
			AND COALESCE(INCLUDE_POOL_FLAG,'') = '' AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE JK.T_JK_LOAN_COBORROWER.COBO_MOBILE2=B.PHONE_NUM)
			UNION ALL
			SELECT ID AS CUSTOMER_CODE,LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE,COBO_FAMILY_TEL AS PHONE_NUMBER,'家庭固话' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COBORROWER WHERE LOAN_CODE=loancode AND COALESCE(COBO_FAMILY_TEL,'')<>''
			AND COALESCE(INCLUDE_POOL_FLAG,'') = '' AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE JK.T_JK_LOAN_COBORROWER.COBO_FAMILY_TEL=B.PHONE_NUM)
			UNION ALL
			SELECT A.ID AS CUSTOMER_CODE,A.LOAN_CODE,DICT_R_CUSTOMTER_TYPE,COMP_TEL AS PHONE_NUMBER,'单位固话' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_COMPANY B ON A.LOAN_CODE = B.LOAN_CODE AND A.LOAN_CODE=loancode     
                                      AND B.DICT_R_CUSTOMTER_TYPE = '1' AND COALESCE(B.COMP_TEL,'')<>'' AND COALESCE(A.INCLUDE_POOL_FLAG,'') = ''
            WHERE NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER C WHERE B.COMP_TEL=C.PHONE_NUM)
			UNION ALL
			SELECT R_CUSTOMER_COBORROWER_ID AS CUSTOMER_CODE,LOAN_CODE,LOAN_CUSTOMTER_TYPE AS DICT_R_CUSTOMTER_TYPE,CONTACT_MOBILE AS PHONE_NUMBER,
			       COALESCE(B.LABEL,'')||'-'||COALESCE(C.LABEL,'')||'('||COALESCE(A.CONTACT_NAME,'')||')'||'手机号码' AS REPEAT_VIEW_TYPE
			FROM JK.T_JK_CONTACT A LEFT JOIN JK.T_GL_DICT B ON A.RELATION_TYPE=B.VALUE AND B.TYPE='jk_relation_type'
			                       LEFT JOIN JK.T_GL_DICT C ON A.CONTACT_RELATION=C.VALUE AND B.ID=C.PARENT_ID
			WHERE LOAN_CODE=loancode AND COALESCE(CONTACT_MOBILE,'')<>'' AND COALESCE(A.INCLUDE_POOL_FLAG,'') = ''
				AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER D WHERE A.CONTACT_MOBILE=D.PHONE_NUM)
			) A INNER JOIN JK.T_JK_PHONE_POOL B ON A.PHONE_NUMBER = B.PHONE AND B.LOAN_CODE!=loancode
		LEFT JOIN JK.T_JK_INNER_CUSTOMER_HIS B1 ON A.LOAN_CODE=B1.LOAN_CODE AND B.LOAN_CODE=B1.HIS_LOAN_CODE
		WHERE B1.LOAN_CODE IS NULL
) A INNER JOIN JK.T_JK_LOAN_INFO C ON A.O_LOAN_CODE = C.LOAN_CODE AND C.OUTTO_LOAN_TIME IS NOT NULL AND A.ROW_NO<10
LEFT JOIN JK.T_GL_JK_PRODUCT OM1 ON C.PRODUCT_TYPE=OM1.PRODUCT_CODE
)
INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,REPEAT_INTO_TIME,REPEAT_MAIN_LOANER,
            EXCEPTION_FLAG,PRODUCT_TYPE,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
SELECT GETUUID32(),N_LOAN_CODE,O_LOAN_CODE,O_NAME,N_CUSTOMER_CODE,N_DICT_CUSTOMER_TYPE,O_RELATION,O_INTO_TIME,O_MAIN_NAME,'2',O_PRODUCT_NAME,N_REPEAT_VIEW_TYPE,
       PHONE_NUMBER,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
FROM TEMP_PHONE_FINAL;
--------单位名称
WITH TEMP_WORKNAME_FINAL AS (
SELECT A.*,C.OUTTO_LOAN_TIME AS O_INTO_TIME,C.LOAN_CUSTOMER_NAME AS O_MAIN_NAME,OM1.PRODUCT_NAME AS O_PRODUCT_NAME
FROM
(SELECT 
	A.LOAN_CODE AS N_LOAN_CODE,A.DICT_CUSTOMER_TYPE AS N_DICT_CUSTOMER_TYPE,A.CUSTOMER_CODE AS N_CUSTOMER_CODE,A.COMP_NAME,
	B.LOAN_CODE AS O_LOAN_CODE,B.R_NAME AS O_NAME,B.DICT_CUSTOMER_TYPE AS O_DICT_CUSTOMER_TYPE,B.R_ID AS O_CUSTOMER_CODE,B.RELATION AS O_RELATION,
	ROW_NUMBER() OVER(PARTITION BY A.LOAN_CODE,A.COMP_NAME,A.CUSTOMER_CODE ORDER BY A.LOAN_CODE DESC) AS ROW_NO 
FROM
	(SELECT A.R_ID AS CUSTOMER_CODE,A.LOAN_CODE,A.DICT_R_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,A.COMP_NAME
	FROM JK.T_JK_LOAN_COMPANY A  LEFT JOIN JK.T_JK_LOAN_COBORROWER C ON A.LOAN_CODE=C.LOAN_CODE AND A.R_ID=C.ID
	WHERE A.LOAN_CODE=loancode AND A.DICT_R_CUSTOMTER_TYPE = '1' AND COALESCE(A.COMP_NAME,'')<>''
	AND COALESCE(A.INCLUDE_POOL_FLAG,'') = ''
) A INNER JOIN JK.T_JK_WORK_NAME_POOL B ON FILTERCOMPANYNAME(A.COMP_NAME)=FILTERCOMPANYNAME(B.WORK_NAME) AND B.LOAN_CODE!=loancode
LEFT JOIN JK.T_JK_INNER_CUSTOMER_HIS B1 ON A.LOAN_CODE=B1.LOAN_CODE AND B.LOAN_CODE=B1.HIS_LOAN_CODE
) A INNER JOIN JK.T_JK_LOAN_INFO C ON A.O_LOAN_CODE = C.LOAN_CODE AND C.OUTTO_LOAN_TIME IS NOT NULL AND A.ROW_NO<10
LEFT JOIN JK.T_GL_JK_PRODUCT OM1 ON C.PRODUCT_TYPE=OM1.PRODUCT_CODE
)
INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,REPEAT_INTO_TIME,REPEAT_MAIN_LOANER,
            EXCEPTION_FLAG,PRODUCT_TYPE,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
SELECT GETUUID32(),N_LOAN_CODE,O_LOAN_CODE,O_NAME,N_CUSTOMER_CODE,N_DICT_CUSTOMER_TYPE,O_RELATION,O_INTO_TIME,O_MAIN_NAME,'2',O_PRODUCT_NAME,'单位名称',
       COMP_NAME,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
FROM TEMP_WORKNAME_FINAL;
--------地址
WITH TEMP_ADDRESS_FINAL AS (
SELECT A.*,C.OUTTO_LOAN_TIME AS O_INTO_TIME,C.LOAN_CUSTOMER_NAME AS O_MAIN_NAME,
OM1.PRODUCT_NAME AS O_PRODUCT_NAME
FROM
(SELECT 
A.LOAN_CODE AS N_LOAN_CODE,A.DICT_CUSTOMER_TYPE AS N_DICT_CUSTOMER_TYPE,A.CUSTOMER_CODE AS N_CUSTOMER_CODE,A.ADDRESS,A.REPEAT_VIEW_TYPE N_REPEAT_VIEW_TYPE,
B.LOAN_CODE AS O_LOAN_CODE,B.R_NAME AS O_NAME,B.DICT_CUSTOMER_TYPE AS O_DICT_CUSTOMER_TYPE,B.R_ID AS O_CUSTOMER_CODE,B.RELATION AS O_RELATION,B.REPEAT_VIEW_TYPE O_REPEAT_VIEW_TYPE,
ROW_NUMBER() OVER(PARTITION BY A.LOAN_CODE,A.REPEAT_VIEW_TYPE,A.ADDRESS,A.CUSTOMER_CODE ORDER BY A.LOAN_CODE DESC) AS ROW_NO 
FROM
(
SELECT A.R_ID AS CUSTOMER_CODE,A.LOAN_CODE,A.DICT_R_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,'单位地址' AS REPEAT_VIEW_TYPE,
       COALESCE(M1.AREA_NAME,'')||COALESCE(M2.AREA_NAME,'')||COALESCE(M3.AREA_NAME,'')||COALESCE(A.COMP_ADDRESS,'') AS ADDRESS,
       A.COMP_PROVINCE AS S_PROVINCE,A.COMP_CITY AS S_CITY,A.COMP_ARER AS S_ARER,A.COMP_ADDRESS AS S_ADDRESS
FROM JK.T_JK_LOAN_COMPANY A 
                            LEFT JOIN JK.T_JK_LOAN_COBORROWER C ON A.LOAN_CODE=C.LOAN_CODE AND A.R_ID=C.ID
                            LEFT JOIN JK.T_GL_PROVINCE_CITY M1 ON A.COMP_PROVINCE = M1.AREA_CODE AND M1.AREA_TYPE = '1'
			    LEFT JOIN JK.T_GL_PROVINCE_CITY M2 ON A.COMP_CITY = M2.AREA_CODE AND M2.AREA_TYPE = '2'
			    LEFT JOIN JK.T_GL_PROVINCE_CITY M3 ON A.COMP_ARER = M3.AREA_CODE AND M3.AREA_TYPE = '3'
WHERE A.LOAN_CODE=loancode AND A.DICT_R_CUSTOMTER_TYPE = '1' AND COALESCE(A.COMP_PROVINCE,'')<>''
      AND COALESCE(A.COMP_CITY,'')<>'' AND COALESCE(A.COMP_ARER,'')<>'' AND COALESCE(A.COMP_ADDRESS,'')<>''
      AND COALESCE(A.INCLUDE_POOL_FLAG,'') = ''
UNION ALL
SELECT A.ID AS CUSTOMER_CODE,A.LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE,'家庭地址' AS REPEAT_VIEW_TYPE,
       COALESCE(M1.AREA_NAME,'')||COALESCE(M2.AREA_NAME,'')||COALESCE(M3.AREA_NAME,'')||COALESCE(A.COBO_NOW_ADDRESS,'') AS ADDRESS,
       A.COBO_LIVEING_PROVINCE AS S_PROVINCE,A.COBO_LIVEING_CITY AS S_CITY,A.COBO_LIVEING_AREA AS S_ARER,A.COBO_NOW_ADDRESS AS S_ADDRESS
FROM JK.T_JK_LOAN_COBORROWER A LEFT JOIN JK.T_GL_PROVINCE_CITY M1 ON A.COBO_LIVEING_PROVINCE = M1.AREA_CODE AND M1.AREA_TYPE = '1'
			       LEFT JOIN JK.T_GL_PROVINCE_CITY M2 ON A.COBO_LIVEING_CITY = M2.AREA_CODE AND M2.AREA_TYPE = '2'
			       LEFT JOIN JK.T_GL_PROVINCE_CITY M3 ON A.COBO_LIVEING_AREA = M3.AREA_CODE AND M3.AREA_TYPE = '3'
WHERE A.LOAN_CODE='1' AND COALESCE(A.COBO_LIVEING_PROVINCE,'')<>'' AND COALESCE(A.COBO_LIVEING_CITY,'')<>'' 
      AND COALESCE(A.COBO_LIVEING_AREA,'')<>'' AND COALESCE(A.COBO_NOW_ADDRESS,'')<>''  AND COALESCE(A.INCLUDE_POOL_FLAG,'') = ''
) A INNER JOIN JK.T_JK_ADDRESS_POOL B ON A.S_PROVINCE=B.PROVINCE AND A.S_CITY=B.CITY AND A.S_ARER=B.AREA AND A.S_ADDRESS=B.ADDRESS AND B.LOAN_CODE!=loancode
LEFT JOIN JK.T_JK_INNER_CUSTOMER_HIS B1 ON A.LOAN_CODE=B1.LOAN_CODE AND B.LOAN_CODE=B1.HIS_LOAN_CODE
) A INNER JOIN JK.T_JK_LOAN_INFO C ON A.O_LOAN_CODE = C.LOAN_CODE AND C.OUTTO_LOAN_TIME IS NOT NULL AND A.ROW_NO<10
LEFT JOIN JK.T_GL_JK_PRODUCT OM1 ON C.PRODUCT_TYPE=OM1.PRODUCT_CODE
)
INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,REPEAT_INTO_TIME,REPEAT_MAIN_LOANER,
            EXCEPTION_FLAG,PRODUCT_TYPE,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
SELECT GETUUID32(),N_LOAN_CODE,O_LOAN_CODE,O_NAME,N_CUSTOMER_CODE,N_DICT_CUSTOMER_TYPE,O_RELATION,O_INTO_TIME,O_MAIN_NAME,'2',O_PRODUCT_NAME,N_REPEAT_VIEW_TYPE,
       ADDRESS,'BACK_ADD',SYSDATE,'BACK_ADD',SYSDATE,'2','2'
FROM TEMP_ADDRESS_FINAL;

/*****************************内网查重结束******************************/
/**
 * 把变更表的字段更新
 */     
UPDATE JK.T_JK_CHANGER_INFO SET SELECT_FLAG='1' WHERE CHANGE_CODE=loancode AND SELECT_FLAG='0';
END;
$BODY$
LANGUAGE plsrsql VOLATILE
COST 100;