DROP FUNCTION jk.verifyrepeatcheck(character varying);
/**
 * 内网匹配（查重、归户、异常对比）
 * @修改履历  V1.0 2016/2/1 创建
 *        V2.0 
 */
CREATE OR REPLACE FUNCTION jk.verifyrepeatcheck(loancode character varying)
RETURNS void AS
$BODY$
BEGIN
/**
 * 本次借款申请的本人证件号码，与所有其他历史借款申请的借款人的证件号码进行匹配，匹配后一致
 * 数据对象：主借人和共借人
 */
/*****************************历史归户开始******************************/
INSERT INTO JK.T_JK_INNER_CUSTOMER_HIS(ID, CUSTOMER_CODE,LOAN_CODE, APPLY_TIME, 
				    PRODUCT_TYPE, DICT_CHECK_STATUS, HIS_REFUSE_RESON,
                    HIS_AMOUNT_MONTHS,DICT_CUSTOMER_TYPE, CREATE_BY, CREATE_TIME,
                    MODIFY_BY, MODIFY_TIME,HIS_LOAN_CODE)
SELECT GETUUID32() AS ID,A.CUSTOMER_CODE,loancode,B.OUTTO_LOAN_TIME,F.PRODUCT_NAME,G.LABEL AS DICT_CHECK_STATUS,
      C.REFUSE_REASON AS HIS_REFUSE_RESON,B.LOAN_AUDIT_AMOUNT ||'/'|| B.LOAN_AUDIT_MONTHS AS HIS_AMOUNT_MONTHS,
       A.DICT_CUSTOMER_TYPE,'BATCH',SYSDATE,'BATCH',SYSDATE,A.LOAN_CODE AS HIS_LOAN_CODE
FROM
(SELECT A.ID AS CUSTOMER_CODE,B.LOAN_CODE,'0' AS DICT_CUSTOMER_TYPE
FROM JK.T_JK_LOAN_CUSTOMER A INNER JOIN JK.T_JK_LOAN_CUSTOMER B ON A.LOAN_CODE=loancode AND B.LOAN_CODE<>loancode 
				 AND A.CUSTOMER_CERT_NUM=B.CUSTOMER_CERT_NUM
UNION ALL
SELECT A.ID AS CUSTOMER_CODE,B.LOAN_CODE,'0' AS DICT_CUSTOMER_TYPE
FROM JK.T_JK_LOAN_CUSTOMER A INNER JOIN JK.T_JK_LOAN_COBORROWER B ON A.LOAN_CODE=loancode 
				 AND A.CUSTOMER_CERT_NUM=B.COBO_CERT_NUM
UNION ALL
SELECT A.ID AS CUSTOMER_CODE,B.LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE
FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_COBORROWER B ON A.LOAN_CODE=loancode AND B.LOAN_CODE<>loancode 
				 AND A.COBO_CERT_NUM=B.COBO_CERT_NUM
UNION ALL
SELECT A.ID AS CUSTOMER_CODE,B.LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE
FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_CUSTOMER B ON A.LOAN_CODE=loancode
				 AND A.COBO_CERT_NUM=B.CUSTOMER_CERT_NUM) A
LEFT JOIN JK.T_JK_LOAN_INFO B ON A.LOAN_CODE=B.LOAN_CODE AND B.OUTTO_LOAN_TIME IS NOT NULL
LEFT JOIN JK.T_JK_AUDIT_RECORD C ON B.AUDIT_ID=C.ID
LEFT JOIN JK.T_GL_JK_PRODUCT F ON B.PRODUCT_TYPE=F.PRODUCT_CODE
LEFT JOIN JK.T_GL_DICT G ON G.VALUE=B.DICT_LOAN_STATUS AND G.TYPE='jk_loan_apply_status'
LEFT JOIN JK.T_CJ_LOAN_INFO H ON A.LOAN_CODE=H.LOAN_CODE AND H.FIRST_ENTRY_APPROVE IS NOT NULL
WHERE B.LOAN_CODE IS NOT NULL OR H.LOAN_CODE IS NOT NULL
GROUP BY A.LOAN_CODE,B.LOAN_APPLY_TIME,F.PRODUCT_NAME,G.LABEL,C.REFUSE_REASON,B.OUTTO_LOAN_TIME,
B.LOAN_AUDIT_AMOUNT,B.LOAN_AUDIT_MONTHS,A.DICT_CUSTOMER_TYPE,A.CUSTOMER_CODE;
/*****************************历史归户结束******************************/
/**
 * 当前借款申请的信息，与同一个借款人的前一次历史借款申请的信息进行比较
 * 数据对象：主借人和共借人
 * 比较对象：手机号码1、手机号码2、居住地址、单位名称、家庭联系人-关系|姓名|手机号
 */
/****************************历史异常对比开始****************************/
WITH TEMP_MAIN AS (--主借人
SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,
       O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,DICT_CUSTOMER_TYPE
FROM
(
SELECT COALESCE(A.CUSTOMER_PHONE_FIRST,'') AS N_PHONE_ONE,COALESCE(A.CUSTOMER_PHONE_SECOND,'') AS N_PHONE_TWO,A.LOAN_CODE AS N_LOAN_CODE,
       NM1.AREA_NAME||NM2.AREA_NAME||NM3.AREA_NAME||A.CUSTOMER_ADDRESS AS N_ADDERSS,A.ID AS N_CUSTOMER_CODE,A.CUSTOMER_TEL N_FAMILY_TEL,
       B.CUSTOMER_PHONE_FIRST AS O_PHONE_ONE,B.CUSTOMER_PHONE_SECOND AS O_PHONE_TWO,B.LOAN_CODE AS O_LOAN_CODE,
       OM1.AREA_NAME||OM2.AREA_NAME||OM3.AREA_NAME||B.CUSTOMER_ADDRESS AS O_ADDERSS,B.ID AS O_CUSTOMER_CODE,B.CUSTOMER_TEL O_FAMILY_TEL,
       '0' AS DICT_CUSTOMER_TYPE,B.CREATE_TIME
FROM JK.T_JK_LOAN_CUSTOMER A INNER JOIN JK.T_JK_LOAN_CUSTOMER B ON A.LOAN_CODE=loancode--'400000316621921'
			                        AND A.CUSTOMER_CERT_NUM=B.CUSTOMER_CERT_NUM AND B.LOAN_CODE<>loancode--'400000316621921'
			                  LEFT JOIN JK.T_GL_PROVINCE_CITY NM1 ON A.CUSTOMER_LIVE_PROVINCE = NM1.AREA_CODE AND NM1.AREA_TYPE = '1'
							  LEFT JOIN JK.T_GL_PROVINCE_CITY NM2 ON A.CUSTOMER_LIVE_CITY = NM2.AREA_CODE AND NM2.AREA_TYPE = '2'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY NM3 ON A.CUSTOMER_LIVE_AREA = NM3.AREA_CODE AND NM3.AREA_TYPE = '3'
			                  LEFT JOIN JK.T_GL_PROVINCE_CITY OM1 ON B.CUSTOMER_LIVE_PROVINCE = OM1.AREA_CODE AND OM1.AREA_TYPE = '1'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM2 ON B.CUSTOMER_LIVE_CITY = OM2.AREA_CODE AND OM2.AREA_TYPE = '2'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM3 ON B.CUSTOMER_LIVE_AREA = OM3.AREA_CODE AND OM3.AREA_TYPE = '3'
                              
UNION ALL
SELECT COALESCE(A.CUSTOMER_PHONE_FIRST,'') AS N_PHONE_ONE,COALESCE(A.CUSTOMER_PHONE_SECOND,'') AS N_PHONE_TWO,A.LOAN_CODE AS N_LOAN_CODE,
       NM1.AREA_NAME||NM2.AREA_NAME||NM3.AREA_NAME||A.CUSTOMER_ADDRESS AS N_ADDERSS,A.ID AS N_CUSTOMER_CODE,A.CUSTOMER_TEL N_FAMILY_TEL,
       B.COBO_MOBILE AS O_PHONE_ONE,B.COBO_MOBILE2 AS O_PHONE_TWO,B.LOAN_CODE AS O_LOAN_CODE,
       OM1.AREA_NAME||OM2.AREA_NAME||OM3.AREA_NAME||B.COBO_NOW_ADDRESS AS O_ADDERSS,B.ID AS O_CUSTOMER_CODE,B.COBO_FAMILY_TEL O_FAMILY_TEL,
       '0' AS DICT_CUSTOMER_TYPE,B.CREATE_TIME
FROM JK.T_JK_LOAN_CUSTOMER A INNER JOIN JK.T_JK_LOAN_COBORROWER B ON A.LOAN_CODE=loancode--'400000316621921'
			  					AND A.CUSTOMER_CERT_NUM=B.COBO_CERT_NUM AND B.LOAN_CODE<>loancode--'400000316621921'
			  				  LEFT JOIN JK.T_GL_PROVINCE_CITY NM1 ON A.CUSTOMER_LIVE_PROVINCE = NM1.AREA_CODE AND NM1.AREA_TYPE = '1'
							  LEFT JOIN JK.T_GL_PROVINCE_CITY NM2 ON A.CUSTOMER_LIVE_CITY = NM2.AREA_CODE AND NM2.AREA_TYPE = '2'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY NM3 ON A.CUSTOMER_LIVE_AREA = NM3.AREA_CODE AND NM3.AREA_TYPE = '3'
			                  LEFT JOIN JK.T_GL_PROVINCE_CITY OM1 ON B.COBO_LIVEING_PROVINCE = OM1.AREA_CODE AND OM1.AREA_TYPE = '1'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM2 ON B.COBO_LIVEING_CITY = OM2.AREA_CODE AND OM2.AREA_TYPE = '2'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM3 ON B.COBO_LIVEING_AREA = OM3.AREA_CODE AND OM3.AREA_TYPE = '3'
) A
ORDER BY A.CREATE_TIME DESC
LIMIT 1
),
TMEP_COBO AS (--共借人
SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,
       O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,
       DICT_CUSTOMER_TYPE
FROM
(
SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,
       O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,
       DICT_CUSTOMER_TYPE,ROW_NUMBER() OVER(PARTITION BY N_CUSTOMER_CODE ORDER BY CREATE_TIME DESC) AS ROW_NO
FROM
(
SELECT COALESCE(A.COBO_MOBILE,'') AS N_PHONE_ONE,COALESCE(A.COBO_MOBILE2,'') AS N_PHONE_TWO,A.LOAN_CODE AS N_LOAN_CODE,
       NM1.AREA_NAME||NM2.AREA_NAME||NM3.AREA_NAME||A.COBO_NOW_ADDRESS AS N_ADDERSS,A.ID AS N_CUSTOMER_CODE,A.COBO_FAMILY_TEL N_FAMILY_TEL,
       B.CUSTOMER_PHONE_FIRST AS O_PHONE_ONE,B.CUSTOMER_PHONE_SECOND AS O_PHONE_TWO,B.LOAN_CODE AS O_LOAN_CODE,
       OM1.AREA_NAME||OM2.AREA_NAME||OM3.AREA_NAME||B.CUSTOMER_ADDRESS AS O_ADDERSS,B.ID AS O_CUSTOMER_CODE,B.CUSTOMER_TEL O_FAMILY_TEL,
       '1' AS DICT_CUSTOMER_TYPE,B.CREATE_TIME
FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_CUSTOMER B ON A.LOAN_CODE=loancode--'400000316621921' 
			  					AND A.COBO_CERT_NUM=B.CUSTOMER_CERT_NUM AND B.LOAN_CODE<>loancode--'400000316621921'
			  				  LEFT JOIN JK.T_GL_PROVINCE_CITY NM1 ON A.COBO_LIVEING_PROVINCE = NM1.AREA_CODE AND NM1.AREA_TYPE = '1'
							  LEFT JOIN JK.T_GL_PROVINCE_CITY NM2 ON A.COBO_LIVEING_CITY = NM2.AREA_CODE AND NM2.AREA_TYPE = '2'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY NM3 ON A.COBO_LIVEING_AREA = NM3.AREA_CODE AND NM3.AREA_TYPE = '3'
			                  LEFT JOIN JK.T_GL_PROVINCE_CITY OM1 ON B.CUSTOMER_LIVE_PROVINCE = OM1.AREA_CODE AND OM1.AREA_TYPE = '1'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM2 ON B.CUSTOMER_LIVE_CITY = OM2.AREA_CODE AND OM2.AREA_TYPE = '2'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM3 ON B.CUSTOMER_LIVE_AREA = OM3.AREA_CODE AND OM3.AREA_TYPE = '3'
UNION ALL
SELECT COALESCE(A.COBO_MOBILE,'') AS N_PHONE_ONE,COALESCE(A.COBO_MOBILE2,'') AS N_PHONE_TWO,A.LOAN_CODE AS N_LOAN_CODE,
       NM1.AREA_NAME||NM2.AREA_NAME||NM3.AREA_NAME||A.COBO_NOW_ADDRESS AS N_ADDERSS,A.ID AS N_CUSTOMER_CODE,A.COBO_FAMILY_TEL N_FAMILY_TEL,
       B.COBO_MOBILE AS O_PHONE_ONE,B.COBO_MOBILE2 AS O_PHONE_TWO,B.LOAN_CODE AS O_LOAN_CODE,
       OM1.AREA_NAME||OM2.AREA_NAME||OM3.AREA_NAME||B.COBO_NOW_ADDRESS AS O_ADDERSS,B.ID AS O_CUSTOMER_CODE,B.COBO_FAMILY_TEL O_FAMILY_TEL,
       '1' AS DICT_CUSTOMER_TYPE,B.CREATE_TIME
FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_COBORROWER B ON A.LOAN_CODE=loancode--'400000316621921' 
			  					AND A.COBO_CERT_NUM=B.COBO_CERT_NUM AND B.LOAN_CODE<>loancode--'400000316621921'
			  				  LEFT JOIN JK.T_GL_PROVINCE_CITY NM1 ON A.COBO_LIVEING_PROVINCE = NM1.AREA_CODE AND NM1.AREA_TYPE = '1'
							  LEFT JOIN JK.T_GL_PROVINCE_CITY NM2 ON A.COBO_LIVEING_CITY = NM2.AREA_CODE AND NM2.AREA_TYPE = '2'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY NM3 ON A.COBO_LIVEING_AREA = NM3.AREA_CODE AND NM3.AREA_TYPE = '3'
			                  LEFT JOIN JK.T_GL_PROVINCE_CITY OM1 ON B.COBO_LIVEING_PROVINCE = OM1.AREA_CODE AND OM1.AREA_TYPE = '1'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM2 ON B.COBO_LIVEING_CITY = OM2.AREA_CODE AND OM2.AREA_TYPE = '2'
                              LEFT JOIN JK.T_GL_PROVINCE_CITY OM3 ON B.COBO_LIVEING_AREA = OM3.AREA_CODE AND OM3.AREA_TYPE = '3'
) A
) B
WHERE ROW_NO=1
),
TEMP_FINAL AS (--主借人和共借人
SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,DICT_CUSTOMER_TYPE
FROM TEMP_MAIN
UNION ALL
SELECT N_CUSTOMER_CODE,N_PHONE_ONE,N_PHONE_TWO,N_ADDERSS,N_LOAN_CODE,N_FAMILY_TEL,O_CUSTOMER_CODE,O_PHONE_ONE,O_PHONE_TWO,O_ADDERSS,O_LOAN_CODE,O_FAMILY_TEL,DICT_CUSTOMER_TYPE
FROM TMEP_COBO
),
TEMP_UNIT AS (--单位名称
SELECT A.DICT_CUSTOMER_TYPE,A.N_CUSTOMER_CODE,A.N_LOAN_CODE,B.COMP_NAME AS N_COMP_NAME,C.COMP_NAME AS O_COMP_NAME
FROM TEMP_FINAL A LEFT JOIN JK.T_JK_LOAN_COMPANY B ON A.N_LOAN_CODE=B.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=B.DICT_R_CUSTOMTER_TYPE AND A.N_CUSTOMER_CODE=B.R_ID
                  LEFT JOIN JK.T_JK_LOAN_COMPANY C ON A.O_LOAN_CODE=C.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=C.DICT_R_CUSTOMTER_TYPE AND A.O_CUSTOMER_CODE=C.R_ID
WHERE COALESCE(B.COMP_NAME,'')<>COALESCE(C.COMP_NAME,'')
),
TEMP_FAMILY AS (--家庭联系人
SELECT A.DICT_CUSTOMER_TYPE,A.N_LOAN_CODE,A.N_CUSTOMER_CODE,
       B.CONTACT_NAME AS N_CONTACT_NAME,E.LABEL AS N_CONTACT_TYPE,B.CONTACT_MOBILE AS N_CONTACT_MOBILE,
       C.CONTACT_NAME AS O_CONTACT_NAME,F.LABEL AS O_CONTACT_TYPE,C.CONTACT_MOBILE AS O_CONTACT_MOBILE
FROM TEMP_FINAL A LEFT JOIN JK.T_JK_CONTACT B ON A.N_LOAN_CODE=B.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=B.LOAN_CUSTOMTER_TYPE
                        AND A.N_CUSTOMER_CODE=B.R_CUSTOMER_COBORROWER_ID AND B.RELATION_TYPE='0'
                  LEFT JOIN JK.T_JK_CONTACT C ON A.O_LOAN_CODE=C.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=C.LOAN_CUSTOMTER_TYPE 
                        AND A.O_CUSTOMER_CODE=C.R_CUSTOMER_COBORROWER_ID AND C.RELATION_TYPE='0'
                  LEFT JOIN JK.T_GL_DICT E ON B.CONTACT_RELATION=E.VALUE AND E.TYPE='jk_loan_family_relation'
                  LEFT JOIN JK.T_GL_DICT F ON C.CONTACT_RELATION=F.VALUE AND F.TYPE='jk_loan_family_relation'
WHERE (COALESCE(B.CONTACT_NAME,'')=COALESCE(C.CONTACT_NAME,'') AND COALESCE(B.CONTACT_MOBILE,'')<>COALESCE(C.CONTACT_MOBILE,'')) 
      OR (COALESCE(B.CONTACT_NAME,'')<>COALESCE(C.CONTACT_NAME,'') AND COALESCE(B.CONTACT_MOBILE,'')=COALESCE(C.CONTACT_MOBILE,''))
),
TEMP_SPOUSE AS (--配偶信息
SELECT A.DICT_CUSTOMER_TYPE,A.N_CUSTOMER_CODE,A.N_LOAN_CODE,B.MATE_NAME AS N_MATE_NAME,B.MATE_TEL AS N_MATE_TEL,C.MATE_NAME AS O_MATE_NAME,C.MATE_TEL AS O_MATE_TEL
FROM TEMP_MAIN A LEFT JOIN JK.T_JK_LOAN_MATE B ON A.N_LOAN_CODE=B.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=B.LOAN_CUSTOMTER_TYPE
                  LEFT JOIN JK.T_JK_LOAN_MATE C ON A.O_LOAN_CODE=C.LOAN_CODE AND A.DICT_CUSTOMER_TYPE=C.LOAN_CUSTOMTER_TYPE
WHERE (COALESCE(B.MATE_NAME,'')=COALESCE(C.MATE_NAME,'') AND COALESCE(B.MATE_TEL,'')<>COALESCE(C.MATE_TEL,'')) 
      OR (COALESCE(B.MATE_NAME,'')<>COALESCE(C.MATE_NAME,'') AND COALESCE(B.MATE_TEL,'')=COALESCE(C.MATE_TEL,''))
)
INSERT INTO JK.T_JK_INNER_APPLY_CONTRAST
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'本人手机',CONCAT_WS(',',NULLIF(N_PHONE_ONE,''),NULLIF(N_PHONE_TWO,'')),
       '前次为:'||CONCAT_WS(',',COALESCE(O_PHONE_ONE,''),COALESCE(O_PHONE_TWO,NULL)),SYSDATE,'BATCH','BATCH',SYSDATE
FROM TEMP_FINAL 
WHERE (COALESCE(N_PHONE_ONE,'')||COALESCE(N_PHONE_TWO,'')) <> (COALESCE(O_PHONE_ONE,'')||COALESCE(O_PHONE_TWO,'')) OR 
      (COALESCE(N_PHONE_ONE,'')||COALESCE(N_PHONE_TWO,'')) <> (COALESCE(O_PHONE_TWO,'')||COALESCE(O_PHONE_ONE,''))
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'单位名称',COALESCE(N_COMP_NAME,''),
       '前次为:'||COALESCE(O_COMP_NAME,''),SYSDATE,'BATCH','BATCH',SYSDATE
FROM TEMP_UNIT
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'家庭固话',COALESCE(N_FAMILY_TEL,''),
       '前次为:'||COALESCE(O_FAMILY_TEL,''),SYSDATE,'BATCH','BATCH',SYSDATE
FROM TEMP_FINAL
WHERE COALESCE(N_FAMILY_TEL,'')<>COALESCE(O_FAMILY_TEL,'')
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'配偶',COALESCE(N_MATE_NAME,'')||'|'||COALESCE(N_MATE_TEL,''),
       '前次为:'||COALESCE(O_MATE_NAME,'')||'|'||COALESCE(O_MATE_TEL,''),SYSDATE,'BATCH','BATCH',SYSDATE
FROM TEMP_SPOUSE 
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'家庭联系人',COALESCE(N_CONTACT_NAME,'')||COALESCE(N_CONTACT_TYPE,'')||COALESCE(N_CONTACT_MOBILE,''),
       '前次为:'||COALESCE(O_CONTACT_NAME,'')||COALESCE(O_CONTACT_TYPE,'')||COALESCE(O_CONTACT_MOBILE,''),SYSDATE,'BATCH','BATCH',SYSDATE
FROM TEMP_FAMILY
UNION ALL
SELECT GETUUID32(),N_LOAN_CODE,N_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,'居住地址',COALESCE(N_ADDERSS,''),
       '前次为:'||COALESCE(O_ADDERSS,''),SYSDATE,'BATCH','BATCH',SYSDATE
FROM TEMP_FINAL 
WHERE COALESCE(N_ADDERSS,'') <> COALESCE(O_ADDERSS,'');
/****************************历史异常对比结束****************************/

/**
 * 当前借款申请的信息，与历史借款信息进行比较
 * 数据对象：主借人和共借人
 * 比较对象：手机号码1、手机号码2、家庭固话、联系人电话、配偶电话、居住地址、单位地址、单位名称、
 */
/*****************************内网查重开始******************************/
--------号码类
WITH TEMP_PHONE_FINAL AS (
SELECT A.*,C.OUTTO_LOAN_TIME AS O_INTO_TIME,C.LOAN_CUSTOMER_NAME AS O_MAIN_NAME,
OM1.PRODUCT_NAME AS O_PRODUCT_NAME,
ROW_NUMBER() OVER(PARTITION BY A.N_LOAN_CODE,A.PHONE_NUMBER,A.N_CUSTOMER_CODE ORDER BY A.N_REPEAT_VIEW_TYPE,A.O_LOAN_CODE DESC) AS ROW_LAST_NO 
FROM
(SELECT 
A.LOAN_CODE AS N_LOAN_CODE,A.PHONE_NUMBER,A.DICT_CUSTOMER_TYPE AS N_DICT_CUSTOMER_TYPE,A.CUSTOMER_CODE AS N_CUSTOMER_CODE,A.REPEAT_VIEW_TYPE N_REPEAT_VIEW_TYPE,
B.LOAN_CODE AS O_LOAN_CODE,B.R_NAME AS O_NAME,B.DICT_CUSTOMER_TYPE AS O_DICT_CUSTOMER_TYPE,B.R_ID AS O_CUSTOMER_CODE,B.RELATION AS O_RELATION,B.REPEAT_VIEW_TYPE O_REPEAT_VIEW_TYPE,
ROW_NUMBER() OVER(PARTITION BY A.LOAN_CODE,A.PHONE_NUMBER,A.CUSTOMER_CODE ORDER BY A.REPEAT_VIEW_TYPE,B.LOAN_CODE DESC) AS ROW_NO 
FROM
(SELECT ID AS CUSTOMER_CODE,LOAN_CODE,'0' AS DICT_CUSTOMER_TYPE,CUSTOMER_PHONE_FIRST AS PHONE_NUMBER,'手机号码' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_CUSTOMER 
WHERE LOAN_CODE=loancode AND COALESCE(CUSTOMER_PHONE_FIRST,'')<>''
	AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE JK.T_JK_LOAN_CUSTOMER.CUSTOMER_PHONE_FIRST=B.PHONE_NUM)
UNION ALL
SELECT ID AS CUSTOMER_CODE,LOAN_CODE,'0' AS DICT_CUSTOMER_TYPE,CUSTOMER_PHONE_SECOND AS PHONE_NUMBER, '手机号码' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_CUSTOMER 
WHERE LOAN_CODE=loancode AND COALESCE(CUSTOMER_PHONE_SECOND,'')<>''
	AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE JK.T_JK_LOAN_CUSTOMER.CUSTOMER_PHONE_SECOND=B.PHONE_NUM)
UNION ALL
SELECT ID AS CUSTOMER_CODE,LOAN_CODE,'0' AS DICT_CUSTOMER_TYPE,CUSTOMER_TEL AS PHONE_NUMBER,'家庭固话' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_CUSTOMER 
WHERE LOAN_CODE=loancode AND COALESCE(CUSTOMER_TEL,'')<>''
	AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE JK.T_JK_LOAN_CUSTOMER.CUSTOMER_TEL=B.PHONE_NUM)
UNION ALL
SELECT A.ID AS CUSTOMER_CODE,A.LOAN_CODE,DICT_R_CUSTOMTER_TYPE,COMP_TEL AS PHONE_NUMBER,'单位固话' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_CUSTOMER A INNER JOIN JK.T_JK_LOAN_COMPANY B ON A.LOAN_CODE = B.LOAN_CODE AND A.LOAN_CODE=loancode
                                    AND B.DICT_R_CUSTOMTER_TYPE = '0' AND COALESCE(B.COMP_TEL,'')<>''
WHERE NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER C WHERE B.COMP_TEL=C.PHONE_NUM)
UNION ALL
SELECT A.ID AS CUSTOMER_CODE,A.LOAN_CODE,LOAN_CUSTOMTER_TYPE,MATE_TEL AS PHONE_NUMBER,'家庭联系人(配偶)手机号' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_CUSTOMER A INNER JOIN JK.T_JK_LOAN_MATE B ON A.LOAN_CODE = B.LOAN_CODE AND A.LOAN_CODE=loancode 
                                    AND B.LOAN_CUSTOMTER_TYPE = '0' AND COALESCE(MATE_TEL,'')<>''
WHERE NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER C WHERE B.MATE_TEL=C.PHONE_NUM)
UNION ALL
SELECT ID AS CUSTOMER_CODE,LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE,COBO_MOBILE AS PHONE_NUMBER,'手机号码' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_COBORROWER 
WHERE LOAN_CODE=loancode AND COALESCE(COBO_MOBILE,'')<>''
	AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE JK.T_JK_LOAN_COBORROWER.COBO_MOBILE=B.PHONE_NUM)
UNION ALL
SELECT ID AS CUSTOMER_CODE,LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE,COBO_MOBILE2 AS PHONE_NUMBER,'手机号码' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_COBORROWER 
WHERE LOAN_CODE=loancode AND COALESCE(COBO_MOBILE2,'')<>''
	AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE JK.T_JK_LOAN_COBORROWER.COBO_MOBILE2=B.PHONE_NUM)
UNION ALL
SELECT ID AS CUSTOMER_CODE,LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE,COBO_FAMILY_TEL AS PHONE_NUMBER,'家庭固话' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_COBORROWER 
WHERE LOAN_CODE=loancode AND COALESCE(COBO_FAMILY_TEL,'')<>''
	AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE JK.T_JK_LOAN_COBORROWER.COBO_FAMILY_TEL=B.PHONE_NUM)
UNION ALL
SELECT A.ID AS CUSTOMER_CODE,A.LOAN_CODE,DICT_R_CUSTOMTER_TYPE,COMP_TEL AS PHONE_NUMBER,'单位固话' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_LOAN_COBORROWER A INNER JOIN JK.T_JK_LOAN_COMPANY B ON A.LOAN_CODE = B.LOAN_CODE AND A.LOAN_CODE=loancode     
                                      AND B.DICT_R_CUSTOMTER_TYPE = '1' AND COALESCE(B.COMP_TEL,'')<>''
WHERE NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER C WHERE B.COMP_TEL=C.PHONE_NUM)
UNION ALL
SELECT R_CUSTOMER_COBORROWER_ID AS CUSTOMER_CODE,LOAN_CODE,LOAN_CUSTOMTER_TYPE AS DICT_R_CUSTOMTER_TYPE,CONTACT_MOBILE AS PHONE_NUMBER,
       COALESCE(B.LABEL,'')||'-'||COALESCE(C.LABEL,'')||'('||COALESCE(A.CONTACT_NAME,'')||')'||'手机号码' AS REPEAT_VIEW_TYPE
FROM JK.T_JK_CONTACT A LEFT JOIN JK.T_GL_DICT B ON A.RELATION_TYPE=B.VALUE AND B.TYPE='jk_relation_type'
                       LEFT JOIN JK.T_GL_DICT C ON A.CONTACT_RELATION=C.VALUE AND B.ID=C.PARENT_ID
WHERE LOAN_CODE=loancode AND COALESCE(CONTACT_MOBILE,'')<>''
	AND NOT EXISTS(SELECT NULL FROM JK.T_JK_PHONENUM_FILTER B WHERE A.CONTACT_MOBILE=B.PHONE_NUM)
) A INNER JOIN JK.T_JK_PHONE_POOL B ON A.PHONE_NUMBER = B.PHONE AND B.LOAN_CODE<>loancode
LEFT JOIN JK.T_JK_INNER_CUSTOMER_HIS B1 ON A.LOAN_CODE=B1.LOAN_CODE AND B.LOAN_CODE=B1.HIS_LOAN_CODE AND A.CUSTOMER_CODE=B1.CUSTOMER_CODE
WHERE B1.LOAN_CODE IS NULL
) A INNER JOIN JK.T_JK_LOAN_INFO C ON A.O_LOAN_CODE = C.LOAN_CODE AND C.OUTTO_LOAN_TIME IS NOT NULL AND A.ROW_NO<10
LEFT JOIN JK.T_GL_JK_PRODUCT OM1 ON C.PRODUCT_TYPE=OM1.PRODUCT_CODE
)
INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,REPEAT_INTO_TIME,REPEAT_MAIN_LOANER,
            EXCEPTION_FLAG,PRODUCT_TYPE,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
SELECT JK.GETUUID32(),N_LOAN_CODE,O_LOAN_CODE,O_NAME,N_CUSTOMER_CODE,N_DICT_CUSTOMER_TYPE,O_RELATION,O_INTO_TIME,O_MAIN_NAME,'2',O_PRODUCT_NAME,N_REPEAT_VIEW_TYPE,
       PHONE_NUMBER,'BATCH',SYSDATE,'BATCH',SYSDATE,'2','2'
FROM TEMP_PHONE_FINAL
WHERE ROW_LAST_NO<9;
--------单位名称
WITH TEMP_WORKNAME_FINAL AS (
SELECT A.*,C.OUTTO_LOAN_TIME AS O_INTO_TIME,
	C.LOAN_CUSTOMER_NAME AS O_MAIN_NAME,OM1.PRODUCT_NAME AS O_PRODUCT_NAME,
	ROW_NUMBER() OVER(PARTITION BY A.N_LOAN_CODE,A.COMP_NAME,A.N_CUSTOMER_CODE ORDER BY A.O_LOAN_CODE DESC) AS ROW_LAST_NO 
FROM
(SELECT 
	A.LOAN_CODE AS N_LOAN_CODE,A.DICT_CUSTOMER_TYPE AS N_DICT_CUSTOMER_TYPE,A.CUSTOMER_CODE AS N_CUSTOMER_CODE,
	B.LOAN_CODE AS O_LOAN_CODE,B.R_NAME AS O_NAME,B.RELATION AS O_RELATION,A.COMP_NAME,
	ROW_NUMBER() OVER(PARTITION BY A.LOAN_CODE,A.CUSTOMER_CODE,A.COMP_NAME ORDER BY B.LOAN_CODE DESC) AS ROW_NO 
FROM
(SELECT A.R_ID AS CUSTOMER_CODE,A.LOAN_CODE,A.DICT_R_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,A.COMP_NAME,JK.FILTERCOMPANYNAME(A.COMP_NAME) AS FILTERNAME
	FROM JK.T_JK_LOAN_COMPANY A 
	WHERE A.LOAN_CODE=loancode AND A.DICT_R_CUSTOMTER_TYPE IN('0','1') AND COALESCE(A.COMP_NAME,'')<>''
) A INNER JOIN JK.T_JK_WORK_NAME_POOL B ON A.FILTERNAME=B.WORK_NAME AND B.LOAN_CODE!=loancode
LEFT JOIN JK.T_JK_INNER_CUSTOMER_HIS B1 ON A.LOAN_CODE=B1.LOAN_CODE AND B.LOAN_CODE=B1.HIS_LOAN_CODE AND A.CUSTOMER_CODE=B1.CUSTOMER_CODE
WHERE B1.LOAN_CODE IS NULL
) A INNER JOIN JK.T_JK_LOAN_INFO C ON A.O_LOAN_CODE = C.LOAN_CODE AND C.OUTTO_LOAN_TIME IS NOT NULL AND A.ROW_NO<10
LEFT JOIN JK.T_GL_JK_PRODUCT OM1 ON C.PRODUCT_TYPE=OM1.PRODUCT_CODE
)
INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,REPEAT_INTO_TIME,REPEAT_MAIN_LOANER,
            EXCEPTION_FLAG,PRODUCT_TYPE,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
SELECT JK.GETUUID32(),N_LOAN_CODE,O_LOAN_CODE,O_NAME,N_CUSTOMER_CODE,N_DICT_CUSTOMER_TYPE,O_RELATION,O_INTO_TIME,O_MAIN_NAME,'2',O_PRODUCT_NAME,'单位名称',
       COMP_NAME,'BATCH',SYSDATE,'BATCH',SYSDATE,'2','2'
FROM TEMP_WORKNAME_FINAL
WHERE ROW_LAST_NO<9;
--------地址
WITH TEMP_ADDRESS_FINAL AS (
SELECT A.*,C.OUTTO_LOAN_TIME AS O_INTO_TIME,C.LOAN_CUSTOMER_NAME AS O_MAIN_NAME,
OM1.PRODUCT_NAME AS O_PRODUCT_NAME,
ROW_NUMBER() OVER(PARTITION BY A.N_LOAN_CODE,A.ADDRESS,A.N_CUSTOMER_CODE ORDER BY A.N_REPEAT_VIEW_TYPE,A.O_LOAN_CODE DESC) AS ROW_LAST_NO 
FROM
(SELECT 
A.LOAN_CODE AS N_LOAN_CODE,A.DICT_CUSTOMER_TYPE AS N_DICT_CUSTOMER_TYPE,A.CUSTOMER_CODE AS N_CUSTOMER_CODE,A.ADDRESS,A.REPEAT_VIEW_TYPE N_REPEAT_VIEW_TYPE,
B.LOAN_CODE AS O_LOAN_CODE,B.R_NAME AS O_NAME,B.DICT_CUSTOMER_TYPE AS O_DICT_CUSTOMER_TYPE,B.R_ID AS O_CUSTOMER_CODE,B.RELATION AS O_RELATION,B.REPEAT_VIEW_TYPE O_REPEAT_VIEW_TYPE,
ROW_NUMBER() OVER(PARTITION BY A.LOAN_CODE,A.ADDRESS,A.CUSTOMER_CODE ORDER BY A.REPEAT_VIEW_TYPE,B.LOAN_CODE DESC) AS ROW_NO 
FROM
(
SELECT A.R_ID AS CUSTOMER_CODE,A.LOAN_CODE,A.DICT_R_CUSTOMTER_TYPE AS DICT_CUSTOMER_TYPE,'单位地址' AS REPEAT_VIEW_TYPE,
       COALESCE(M1.AREA_NAME,'')||COALESCE(M2.AREA_NAME,'')||COALESCE(M3.AREA_NAME,'')||COALESCE(A.COMP_ADDRESS,'') AS ADDRESS,
       CASE WHEN A.DICT_R_CUSTOMTER_TYPE='0' THEN '本人' ELSE '共借人' END AS N_RELATION,
       A.COMP_PROVINCE AS S_PROVINCE,A.COMP_CITY AS S_CITY,A.COMP_ARER AS S_ARER,A.COMP_ADDRESS AS S_ADDRESS
FROM JK.T_JK_LOAN_COMPANY A LEFT JOIN JK.T_JK_LOAN_CUSTOMER B ON A.LOAN_CODE=B.LOAN_CODE AND A.R_ID=B.ID
                            LEFT JOIN JK.T_JK_LOAN_COBORROWER C ON A.LOAN_CODE=C.LOAN_CODE AND A.R_ID=C.ID
                            LEFT JOIN JK.T_GL_PROVINCE_CITY M1 ON A.COMP_PROVINCE = M1.AREA_CODE AND M1.AREA_TYPE = '1'
			    LEFT JOIN JK.T_GL_PROVINCE_CITY M2 ON A.COMP_CITY = M2.AREA_CODE AND M2.AREA_TYPE = '2'
			    LEFT JOIN JK.T_GL_PROVINCE_CITY M3 ON A.COMP_ARER = M3.AREA_CODE AND M3.AREA_TYPE = '3'
WHERE A.LOAN_CODE=loancode AND A.DICT_R_CUSTOMTER_TYPE IN('0','1') AND COALESCE(A.COMP_PROVINCE,'')<>''
      AND COALESCE(A.COMP_CITY,'')<>'' AND COALESCE(A.COMP_ARER,'')<>'' AND COALESCE(A.COMP_ADDRESS,'')<>''
UNION ALL
SELECT A.ID AS CUSTOMER_CODE,A.LOAN_CODE,'0' AS DICT_CUSTOMER_TYPE,'家庭地址' AS REPEAT_VIEW_TYPE,
       COALESCE(M1.AREA_NAME,'')||COALESCE(M2.AREA_NAME,'')||COALESCE(M3.AREA_NAME,'')||COALESCE(A.CUSTOMER_ADDRESS,'') AS ADDRESS,
       '本人' AS N_RELATION,
       A.CUSTOMER_LIVE_PROVINCE AS S_PROVINCE,A.CUSTOMER_LIVE_CITY AS S_CITY,A.CUSTOMER_LIVE_AREA AS S_ARER,A.CUSTOMER_ADDRESS AS S_ADDRESS
FROM JK.T_JK_LOAN_CUSTOMER A LEFT JOIN JK.T_GL_PROVINCE_CITY M1 ON A.CUSTOMER_LIVE_PROVINCE = M1.AREA_CODE AND M1.AREA_TYPE = '1'
			     LEFT JOIN JK.T_GL_PROVINCE_CITY M2 ON A.CUSTOMER_LIVE_CITY = M2.AREA_CODE AND M2.AREA_TYPE = '2'
			     LEFT JOIN JK.T_GL_PROVINCE_CITY M3 ON A.CUSTOMER_LIVE_AREA = M3.AREA_CODE AND M3.AREA_TYPE = '3'
WHERE A.LOAN_CODE=loancode AND COALESCE(A.CUSTOMER_LIVE_PROVINCE,'')<>'' AND COALESCE(A.CUSTOMER_LIVE_CITY,'')<>'' 
      AND COALESCE(A.CUSTOMER_LIVE_AREA,'')<>'' AND COALESCE(A.CUSTOMER_ADDRESS,'')<>''
UNION ALL
SELECT A.ID AS CUSTOMER_CODE,A.LOAN_CODE,'1' AS DICT_CUSTOMER_TYPE,'家庭地址' AS REPEAT_VIEW_TYPE,
       COALESCE(M1.AREA_NAME,'')||COALESCE(M2.AREA_NAME,'')||COALESCE(M3.AREA_NAME,'')||COALESCE(A.COBO_NOW_ADDRESS,'') AS ADDRESS,
       '共借人' AS N_RELATION,
       A.COBO_LIVEING_PROVINCE AS S_PROVINCE,A.COBO_LIVEING_CITY AS S_CITY,A.COBO_LIVEING_AREA AS S_ARER,A.COBO_NOW_ADDRESS AS S_ADDRESS
FROM JK.T_JK_LOAN_COBORROWER A LEFT JOIN JK.T_GL_PROVINCE_CITY M1 ON A.COBO_LIVEING_PROVINCE = M1.AREA_CODE AND M1.AREA_TYPE = '1'
			       LEFT JOIN JK.T_GL_PROVINCE_CITY M2 ON A.COBO_LIVEING_CITY = M2.AREA_CODE AND M2.AREA_TYPE = '2'
			       LEFT JOIN JK.T_GL_PROVINCE_CITY M3 ON A.COBO_LIVEING_AREA = M3.AREA_CODE AND M3.AREA_TYPE = '3'
WHERE A.LOAN_CODE=loancode AND COALESCE(A.COBO_LIVEING_PROVINCE,'')<>'' AND COALESCE(A.COBO_LIVEING_CITY,'')<>'' 
      AND COALESCE(A.COBO_LIVEING_AREA,'')<>'' AND COALESCE(A.COBO_NOW_ADDRESS,'')<>''
) A INNER JOIN JK.T_JK_ADDRESS_POOL B ON A.S_PROVINCE=B.PROVINCE AND A.S_CITY=B.CITY AND A.S_ARER=B.AREA AND A.S_ADDRESS=B.ADDRESS AND B.LOAN_CODE!=loancode
LEFT JOIN JK.T_JK_INNER_CUSTOMER_HIS B1 ON A.LOAN_CODE=B1.LOAN_CODE AND B.LOAN_CODE=B1.HIS_LOAN_CODE AND A.CUSTOMER_CODE=B1.CUSTOMER_CODE
WHERE B1.LOAN_CODE IS NULL
) A INNER JOIN JK.T_JK_LOAN_INFO C ON A.O_LOAN_CODE = C.LOAN_CODE AND C.OUTTO_LOAN_TIME IS NOT NULL AND A.ROW_NO<10
LEFT JOIN JK.T_GL_JK_PRODUCT OM1 ON C.PRODUCT_TYPE=OM1.PRODUCT_CODE
)
INSERT INTO JK.T_JK_INNER_REPEAT(ID,LOAN_CODE,R_ID,REPEAT_NAME,LOAN_CUSTOMER_CODE,DICT_CUSTOMER_TYPE,REPEAT_RELATION,REPEAT_INTO_TIME,REPEAT_MAIN_LOANER,
            EXCEPTION_FLAG,PRODUCT_TYPE,REPEAT_VIEW_TYPE,REPEAT_VIEW_CONTENT,CREATE_BY,CREATE_TIME,MODIFY_BY,MODIFY_TIME,RESOURCE,EXCEPTION_RECONSIDER_FLAG)
SELECT JK.GETUUID32(),N_LOAN_CODE,O_LOAN_CODE,O_NAME,N_CUSTOMER_CODE,N_DICT_CUSTOMER_TYPE,O_RELATION,O_INTO_TIME,O_MAIN_NAME,'2',O_PRODUCT_NAME,N_REPEAT_VIEW_TYPE,
       ADDRESS,'BATCH',SYSDATE,'BATCH',SYSDATE,'2','2'
FROM TEMP_ADDRESS_FINAL
WHERE ROW_LAST_NO<9;

/*****************************内网查重结束******************************/
     
END;
$BODY$
LANGUAGE plsrsql VOLATILE
COST 100;