version: '2'
services:
  eureka-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: microservice-eureka
        source_port: 8761
        target_port: 8761
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  microservice-customerinfo-client:
    scale: 1
    start_on_create: true
  CUSTOMERINFO-CLIENT-LB:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: microservice-customerinfo-client
        source_port: 7005
        target_port: 7005
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  microservice-config:
    scale: 1
    start_on_create: true
  microservice-customerinfo-server:
    scale: 1
    start_on_create: true
  microservice-eureka:
    scale: 1
    start_on_create: true
  config-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: microservice-config
        source_port: 7001
        target_port: 7001
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  sleuth-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: microservice-sleuth
        source_port: 7002
        target_port: 7002
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  microservice-sleuth:
    scale: 1
    start_on_create: true
